### ISSUE TITLE
emqx ratelimit problem

### ISSUE THREAD

**Issue by mopybird** [emqx/emqx#5020] opened 2021-06-17 05:16 UTC
I have a setup of emqx with this config in v4.1

EMQX_ZONE__EXTERNAL__PUBLISH_LIMIT: 100,10s
EMQX_LISTENER__SSL__EXTERNAL: 8883
EMQX_STATSD__INTERVAL: "1000"
EMQX_LISTENER__TCP__EXTERNAL__MAX_CONN_RATE: 2000
EMQX_LISTENER__TCP__EXTERNAL__ACTIVE_N: 100

my clients for sure sending fewer packets then described in rate-limiting config
but logs show that : [MQTT] Pause 100ms due to rate limit
EMQX_ZONE__EXTERNAL__PUBLISH_LIMIT: 100,10s
EMQX_LISTENER__SSL__EXTERNAL: 8883
EMQX_STATSD__INTERVAL: "1000"
EMQX_LISTENER__TCP__EXTERNAL__MAX_CONN_RATE: 2000
EMQX_LISTENER__TCP__EXTERNAL__ACTIVE_N: 100

my clients for sure sending fewer packets then described in rate-limiting config
but logs show that : [MQTT] Pause 100ms due to rate limit

**Comment by k32** [comment] 2021-06-18 09:35
Duplicate of https://github.com/emqx/emqx/issues/4988 ?

**Closed** 2021-06-18 13:11 UTC
Labels: Support
