### ISSUE TITLE
Not worked updating emqx.config file by docker compose file in Emqx version 5

### ISSUE THREAD

**Issue by rezaulk** [emqx/emqx#10889] opened 2023-05-30 18:47 UTC
### What happened?

I try to build EMQX cluster by Docker Compose file. When excute compose file ,container successfully created with environment variable. I can see Environment varibales in container inspect but In emqx.conf file did’t updated which i mentioned environment variable in compose file.

### What did you expect to happen?

I attached compose file in below.Want to update config file which i mentioned in compose file. This is wokring in version 4 but didn't happend in version 5

### EMQX version

 
```console
version: '3'

services:
  emqx1:
    image: emqx:latest
    container_name: emqx1
    environment:
    - "EMQX_NODE_NAME=emqx@node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    - "EMQX_LISTENER__SSL__EXTERNAL__CERTFILE=etc/certs/emqx.pem"
    - "EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE=etc/certs/ca.pem"
    - "EMQX_LISTENER__SSL__EXTERNAL__KEYFILE=etc/certs/emqx.key"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
    ports:
      - 8883:8883
      - 18083:18083 
    volumes:
       - ./certs:/opt/emqx/etc/certs

  
networks:
  emqx-bridge:
    driver: bridge
```

**Comment by thalesmg** [comment] 2023-05-30 18:56
Hi @rezaulk .

This behavior is intentional.  The `emqx.conf` file is not changed by EMQX based on the values of environment variables.  The environment variables simply override other existing configurations, and are not persisted to disk.

Please see the docs about the configuration and the overriding of keys: https://www.emqx.io/docs/en/v5.0/configuration/configuration.html#configuration-files-2

**Comment by thalesmg** [comment] 2023-05-30 18:57
Closing as this is not a bug.  Feel free to open another issue if another problem arises.

**Closed by thalesmg** 2023-05-30 18:57 UTC
Labels: question

**Comment by rezaulk** [comment] 2023-05-30 19:42
As I am trying to enable Two way enable ssl. following this documents
https://www.emqx.com/en/blog/enable-two-way-ssl-for-emqx
 
add these 2 varibles in envrionment.
`
listener.ssl.external.verify = verify_peer
`
`
listener.ssl.external.fail_if_no_peer_cert = true
`

when try to connect from client without client certificate, client successfully connected but this should not be connect without client certificate.

**Comment by rezaulk** [comment] 2023-05-30 20:11
@thalesmg 
Thanks a ton. It works 👍
