### ISSUE TITLE
emqx console

### ISSUE THREAD

**Issue by servucn** [emqx/emqx#2183] opened 2019-01-25 07:20 UTC
#### Environment

- OS : window 2008 x64
- Erlang/OTP: 
- EMQ:  3.0

#### Description

C:\Users\Administrator>cd /d C:\Program Files\emqx\bin

C:\Program Files\emqx\bin>emqx console

C:\Program Files\emqx\bin>set args_file=-args_file "C:\Program Files\emqx\etc\vm
.args"

C:\Program Files\emqx\bin>set sys_config=-config "C:\Program Files\emqx\etc\sys.
config"

*A description of the issue*
[](url)

**Comment by IcyBridge** [comment] 2019-02-08 10:40
Environment

- OS : Windows Server 2016 x64

- Erlang/OTP:

- EMQ X 3.0.1


Is there any solutions for the problem yet? Problem is similar to this issue. Following line comes with console command.

C:\Program Files (x86)\EMQ X\Windows 10>set sys_config=-config "C:\Program Files (x86)\EMQ X\Windows 10\etc\sys.config" 
\EMQ was unexpected at this time.

C:\Program Files (x86)\EMQ X\Windows 10>  set boot_script=C:\Program Files (x86)\EMQ X\Windows 10\releases\3.0.1\emqx

**Comment by Gilbert-Wong** [comment] 2019-03-07 03:21
The path which run emqx should not contain space character or hyphen.

**Comment by zhanghongtong** [comment] 2019-03-20 01:46
Seems the issue is resolved. I am going to close this issue. Please feel free to re-open if you still have the same trouble.

**Closed by zhanghongtong** 2019-03-20 01:46 UTC
Labels: Support, windows
