### ISSUE TITLE
Clients with wildcard topics cannot connect to clustered brokers.

### ISSUE THREAD

**Issue by BorisPetelj** [emqx/emqx#2985] opened 2019-10-18 14:47 UTC
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 3.2.2

**Topology**: 
- **Nginx** as load balancer
  -  Nginx least connection load balancing strategy towards 2 EMQX nodes
- **Two EMQX nodes** in cluster (4 vCPUs, 4GB RAM each)
  -  Clean installation of EMQX nodes
  -  _/etc/emqx/acl.conf_ is set to allow all traffic (default config)
- **Test instance**
  - Used for running mqtt clients 

#### Problem:

- 10000 MQTT clients that are connecting to brokers (trough Nginx) and subscribing to a list of topics.
- If clients do not have wildcard topics in subscription list, everything works fine. However, just by inserting wildcard topics in the same topic structure, brokers are unable to establish those 10000 connections.

### Test cases:
Using _emqtt_bench_ we managed to reproduce this issue. There are 2 cases:

#### Test case 1, working:
- Topics list (total 8 topics). 
`./emqtt_bench sub -h "nginx_ip" -p 1883 -c 10000 -t "listed below" -V 3`
    - "1/%c/2/%i/wildcard/req",
    - "1/%c/2/%i/wildcard/wildcard/req",
    - "1/%c/2/%i/wildcard/rsp",
    - "1/%c/3/wildcard/2/%i/lwm",
    - "1/%c/3/wildcard/2/%i/evt",
    - "1/%c/4/wildcard/evt",
    - "1/%c/4/wildcard/lwm",
    - "1/3/wildcard/evt"
![bench_case_2](https://user-images.githubusercontent.com/7778135/67101637-4a0fa700-f1c2-11e9-8230-8b0d426ec30b.png)

* In the attached image it can be seen that if wildcard topics are not used (string "wildcard" instead of actual "+") all 5000 clients got connected with no errors.
  - **connections.count = connections.max** on broker stats

#### Test case 2, not working:

-  Topics list (total 8 topics)
`./emqtt_bench sub -h "nginx_ip" -p 1883 -c 10000 -t "listed below" -V 3`
    - "1/%c/2/%i/+/req",
    - "1/%c/2/%i/+/+/req",
    - "1/%c/2/%i/+/rsp",
    - "1/%c/3/+/2/%i/lwm",
    - "1/%c/3/+/2/%i/evt",
    - "1/%c/4/+/evt",
    - "1/%c/4/+/lwm",
    - "1/3/+/evt"
![bench_case_1](https://user-images.githubusercontent.com/7778135/67101592-32382300-f1c2-11e9-9847-8d5276d3f2d1.png)
* When "wildcard" string is replaced with "+", and tests re-run (**brokers stats cleared by restarting both brokers**) clients are not able to connect.
  - **connections.count < connections.max** on broker stats
  - If clients are configured to reconnect, brokers never recover from this state and constantly drops connections. 

### Additional description
Problem is reproducible with our custom NodeJS load_test script which is also attached [emqx_bench.zip](https://github.com/emqx/emqx/files/3744411/emqx_bench.zip).
Requires NodeJS 8.7.0. After unpack, execute by running: `node index.js`

Script executes 5000 clients and same behavior as with _emqtt_bench_ is observed. Images: [nodejs_load_test.zip](https://github.com/emqx/emqx/files/3744457/nodejs_load_test.zip)

### Versions of EMQX with same issue:
- [ ] 2.3.11  **not reproducible**
- [x] 3.0.1 
- [x] 3.2.2
- [x] 4.0.beta1
- [x] 4.0.beta2

**Comment by tigercl** [comment] 2019-10-21 02:01
Hi, @BorisPetelj  Could you provide the log of emqx?

**Comment by BorisPetelj** [comment] 2019-10-21 09:11
Attaching both warning and debug logs. In case when debug was enabled, less connections were established (somewhat expected).
#### Debug log level

![debug-log](https://user-images.githubusercontent.com/7778135/67192154-59c20200-f3f3-11e9-9ded-14b929492a3c.png)


[emqx1-log-debug.tar.gz](https://github.com/emqx/emqx/files/3749893/emqx1-log-debug.tar.gz)
[emqx2-log-debug.tar.gz](https://github.com/emqx/emqx/files/3749895/emqx2-log-debug.tar.gz)

#### Warning log level

![warning-log](https://user-images.githubusercontent.com/7778135/67192220-7f4f0b80-f3f3-11e9-9153-ee36f4bdd401.png)
[emqx1-log-warning.tar.gz](https://github.com/emqx/emqx/files/3749894/emqx1-log-warning.tar.gz)
[emqx2-log-warning.tar.gz](https://github.com/emqx/emqx/files/3749896/emqx2-log-warning.tar.gz)

**Comment by tigercl** [comment] 2019-10-24 01:51
Hi, @BorisPetelj, sorry for later reply, I checked your log and found that your wildcard topic has 39 levels so that the callings timeout. The correct subscription should be like [{Topic, SubOpt}, ...], but your subscription is [{[Topic, Topic, ...], SubOpt}].

Your Subscription:
```
[{<<"1/bdl-smwebd-01_bench_sub_5816_4074255960/2/5816/+/req,1/bdl-smwebd-01_bench_sub_5816_4074255960/2/5816/+/+/req,1/bdl-smwebd-01_bench_sub_5816_4074255960/2/5816/+/rsp,1/bdl-smwebd-01_bench_sub_5816_4074255960/3/+/2/5816/lwm,1/bdl-smwebd-01_bench_sub_5816_4074255960/3/+/2/5816/evt,1/bdl-smwebd-01_bench_sub_5816_4074255960/4/+/evt,1/bdl-smwebd-01_bench_sub_5816_4074255960/4/+/lwm,1/3/+/evt">>,#{nl => 0,qos => 0,rap => 0,rc => 0,rh => 0}}]
```

Your subscription without wildcard character works because the topic without wildcard character is faster to process.

**Comment by BorisPetelj** [comment] 2019-10-24 08:09
Hi @tigercl. Thanks for reply. Please find my observations below:


> I found that your wildcard topic has 39 levels so that the call time out.
 1. Why exactly 39?
 2. How can we get to this value? 
 3. How many levels we can have, and not to cause timeouts?


> The correct subscription should be like [{Topic, SubOpt}, ...], but your subscription is [{[Topic, Topic, ...], SubOpt}].

- Looks like emqtt_bench is using bulk subsribe, since this output ([{[Topic, Topic, ...], SubOpt}]). 
- In case of using our nodejs script, the object is as you suggest - [{Topic, SubOpt}, ...] - attached emqx logs for this case
- **The issue is reproduced even with proposed subscription.**

> Your subscription without wildcard character works because the topic without wildcard character is faster to process.

- We need cluster, and we need wildcards. What do you suggest? We can easily reproduce this issue with less than 1000 clients connected which really is not that much.


[emqx1-log-debug-nodejs.tar.gz](https://github.com/emqx/emqx/files/3766342/emqx1-log-debug-nodejs.tar.gz)
[emqx2-log-debug-nodejs.tar.gz](https://github.com/emqx/emqx/files/3766343/emqx2-log-debug-nodejs.tar.gz)
[emqx1-log-warning-nodejs.tar.gz](https://github.com/emqx/emqx/files/3766344/emqx1-log-warning-nodejs.tar.gz)
[emqx2-log-warning-nodejs.tar.gz](https://github.com/emqx/emqx/files/3766346/emqx2-log-warning-nodejs.tar.gz)

**Comment by BorisPetelj** [comment] 2019-10-25 13:29
Additional information:

Tried with EMQX Enterprise v3.4.2 (trial). Issue still occurs.

**Comment by zhengyupan** [comment] 2019-10-29 19:28
Hi @BorisPetelj 
It is the way you pass the topic to emqtt-bench. you will need multiple "-t" parameters to pass multiple topic for subscription. From the example you gave, it didn't show how the topics are passed exactly, but if the subscription worked as your expectation ,the output should be:
<img width="552" alt="Screenshot 2019-10-29 20 17 29" src="https://user-images.githubusercontent.com/3228288/67801299-2d5c5480-fa89-11e9-94ce-1d45664ddeb2.png">
Please note that there are multiple quotation pairs in the square brackets, each quotation represents one topic, not just one quotation.

here is the command line I used to test:
`./emqtt_bench sub -h 192.168.1.133 -c 10000 -Zhengyus-MBP:emqtt-bench apan$ ./emqtt_bench sub -h 192.168.1.133 -c 10000 -t "1/%c/2/%i/+/req" -t "1/%c/2/%i/+/+/req" -t "1/%c/2/%i/+/rsp" -t "1/%c/3/+/2/%i/lwm" -t "1/%c/3/+/2/%i/evt" -t "1/%c/4/+/evt" -t "1/%c/4/+/lwm" -t "1/3/+/evt"`

It created 10,000 (10 times as your test) connection to broker, each connection subscribe to 8 topics.
the broker is a VM with **1 cpu core** and **1GB memory.**

checked the borker stats with "emqx_ctl broker stats":
<img width="548" alt="Screenshot 2019-10-29 20 23 26" src="https://user-images.githubusercontent.com/3228288/67801679-f9356380-fa89-11e9-8f2e-ff4711bef990.png">

system load after all subscriptions are built:
<img width="638" alt="Screenshot 2019-10-29 20 25 13" src="https://user-images.githubusercontent.com/3228288/67801857-5d582780-fa8a-11e9-8d17-7e39fae67f99.png">

I hope the above can sort out your issue.

**Comment by BorisPetelj** [comment] 2019-10-29 20:42
Hi @zhengyupan. 

Please try with clustered brokers as that is the case we are facing this issue (2 clustered nodes).
   _In front, we have Nginx as load balancer with least connection balancing strategy (see first post)_

**Comment by tigercl** [comment] 2019-11-05 10:24
Hi, @BorisPetelj.
I mean there's something wrong with your subscription, it doesn't matter if emqx in a clustered environment.

**Comment by BorisPetelj** [comment] 2019-11-07 10:19
Hello @tigercl  and @zhengyupan 

We have changed the way of how we subscribe. Clients send subscribe per topic, not all together. Issue still exists in clustered EMQX broker.

Issue is reproduced with both emqtt_bench and our custom NodeJS load_test script.

Here is the topic structure (attached picture). EMQX team says that we have 39 level topic structure. The truth is that there is:

- 8 individual topics
-  max level is 6

![image002](https://user-images.githubusercontent.com/7778135/68380385-07e9dd80-0150-11ea-9272-d30523e7b0bf.png)

**May EMQX team explain in more detail how the topics and subscriptions are wrong?**

Refering to "I mean there's something wrong with your subscription, it doesn't matter if emqx in a clustered environment."

How is that single instance of EMQX has no issue with "wrong with your subscription"?

**Comment by tigercl** [comment] 2019-11-08 01:29
@BorisPetelj. Can you provide more details like emqx log and emqtt command you use?

**Comment by BorisPetelj** [comment] 2019-11-15 14:08
Hi @tigercl.
Sorry for late reply, but we are performing tests and will update with results.

To answer your question, command used is suggested by @zhengyupan in https://github.com/emqx/emqx/issues/2985#issuecomment-547590949

`$ ./emqtt_bench sub -h 192.168.1.133 -c 10000 -t "1/%c/2/%i/+/req" -t "1/%c/2/%i/+/+/req" -t "1/%c/2/%i/+/rsp" -t "1/%c/3/+/2/%i/lwm" -t "1/%c/3/+/2/%i/evt" -t "1/%c/4/+/evt" -t "1/%c/4/+/lwm" -t "1/3/+/evt"`

The behavior is same as described in previous cases. 
@zhengyupan managed to connect all models with no issues by decreasing connection rate. That is the reason why we are conducting tests with various parameters, and try to determine performance with our use-case - wildcard topics with clustered brokers.

**Comment by BorisPetelj** [comment] 2019-11-19 12:38
Hi @tigercl, @zhengyupan. 

Regarding EMQX team reply on successfully connecting 20k clients with our 8 wildcard topics:
> "Connection rate was decreased to 20conn/sec due to low instances performance (1vCPU + 1GB)
The test was successful."

We measured performance of Brokers in cluster with larger instances (4vCPUs/8GB) and found that CPUs and RAM memory was not fully utilized during load tests. CPUs max utilization was below 20%, RAM was almost fully free. During tests we had Nagios monitoring tool set. **The connections were still being dropped** after some time (based on conn_rate and subscription topics)

Even though resources was not fully utilized, we boosted instances to 8vCPUs/16GB and saw some improvements. This leads us to a conclusion that number of CPUs,  directly affect performances in terms of parallelization of connection/message handling. 

-----
The table below shows summary of load tests. There were 2 EMQX nodes in cluster, each on 8vCPUs 16GB instance:

![Screenshot from 2019-11-19 13-28-24](https://user-images.githubusercontent.com/7778135/69146638-89d2f280-0ad0-11ea-9ed2-8dbc6961c998.png)




- Connections established vary mainly from combination of client connection rate (per second), and number of topics each client subscribes to.

Column 5 shows number of topics each client subscribes to. E.x. 9/3 means there are 9 regular topics, and 3 wildcard topics (total 12 topics).


The table shows that if no wildcard subscriptions are used (row 11), we are able to acheve ~1250 conn per second.
On the other hand, test cases 6-10 (where 8 wildcard topics were used) shows performance degradation based on conn_rate. The best brokers can do is 22.8 conn/sec. 
Connection rate of 20 conn/sec causes too long ramp up time for larger setups (1M/20 = 50000 sec = 13h)

**In production environment, this is definitely not an option.** 
Another concern we have is: What are the next limits we did not reach, since we only performed tests with 50k clients?
Can the problem be related to EMQX configuration? 

We are in the process of scaling system to 1M but failing to perform basic load test due to this problem. Please advise us how to proceed.

**Comment by emqplus** [comment] 2019-11-19 12:45
@zhengyupan @turtleDeng Please check the benchmark issue.

**Comment by RodaBVB** [comment] 2019-11-22 12:52
As EMQX requested, logs attached.

[emqx_logs.zip](https://github.com/emqx/emqx/files/3879552/emqx_logs.zip)

**Comment by HJianBo** [comment] 2020-01-19 03:25
Hi, @BorisPetelj Thank you very much for providing such detailed test results and contents. It's very useful!

**The main cost is caused by the transaction of inserting the wildcard subscription `Topic Trie`**

We plan to improve it at the v5.0

**Comment by qzhuyan** [comment] 2021-04-07 21:02
hi @RodaBVB @BorisPetelj , I am assigned to look into this issue however I am not able to reproudce the issue (subscribe timeout) with latest EMQ X release. 

My test env is 2 emqx nodes with 2 cores, 4 GB mem each.  5 parallel emqtt_bench send traffic to two nodes without a proxy in the middle, the command I use is the same as in https://github.com/emqx/emqx/issues/2985#issuecomment-547590949

Do you keep the envioment so that we can do invetigation with?  I need to gather more info on you ngnix config, monitoring and kernel network configs.

**Comment by qzhuyan** [comment] 2021-04-08 11:35
Note, I managed to reproduce the issue by assigning more scheudlers to each node.

**Comment by gbrehmer** [comment] 2021-04-11 18:34
I can also confirm that there are no more errors with the current version (4.2.9). I had only tested up to version 4.0.1 and no newer version since then.

My results with an adapted version of emqtt_bench (our test devices needs special unique topics):
3 node cluster, each 8GB RAM & 4 CPUs

Case 1: 1200 clients, 600 subscriber, 600 publisher, 300 messages published/s, 300 messages received/s (0% loss)
Case 2: 2400 clients, 1200 subscriber, 1200 publisher, 300 messages published/s, 300 messages received/s (0% loss)
Case 3: 4800 clients, 2400 subscriber, 2400 publisher, 600 messages published/s, 600 messages received/s (0% loss)
Case 4: 4800 clients, 2400 subscriber, 2400 publisher, 1200 messages published/s, 1200 messages received/s (0% loss)
Case 5: 9600 clients, 4800 subscriber, 4800 publisher, 2400 messages published/s, 2400 messages received/s (0% loss)

> I managed to reproduce the issue by assigning more schedulers to each node.

Which setting can change the number of schedulers?

**Comment by qzhuyan** [comment] 2021-04-11 19:41
> Which setting can change the number of schedulers?


Thanks for your info,

I tested with a 4 cores system but only gives 2 schedulers (vmargs +S2:2) for emqx since I also run the emqtt_bench on the same machine. After I assigned 4 cores to the emqx and change emqtt bench's interval to 10 (100 reqs/s), I can reproduce the issue. Looks like it needs more concurrent tasks to reproduce it because the issue is about lock contentions across the processes of all nodes in the cluster.

So to reproduce the issue we need:

1. a cluster setup.
1. Subscribes 6 topics at a time per client
1. Topics has many levels (6)
1. Wildcard topics
1. high init connection rate


Would be interested to know if all conditions are met in your test?

**Comment by gbrehmer** [comment] 2021-04-12 07:21
Ah my notes from previous tests was outdated, I forgot the wildcard sorry. Now many errors are back, still with lower counts. The problem is bigger when we use more nodes (like @HJianBo mentioned in https://github.com/emqx/emqx/issues/2851#issuecomment-526795892). Last time with 4.0.1 we use 2 nodes, this time 3 nodes

test results:
Case 1: 200 clients, 100 subscriber, 100 publisher, 25 messages published/s, 25 messages received/s (0% loss)
Case 2: 200 clients, 100 subscriber, 100 publisher, 100 messages published/s, 100 messages received/s (0% loss)
Case 3: 400 clients, 200 subscriber, 200 publisher, 200 messages published/s, 195 messages received/s (2% loss)
Case 4: 600 clients, 300 subscriber, 300 publisher, 300 messages published/s, 196 messages received/s (35% loss)

Topics under test: `home/%d/%i/%u/job/1/status`
Subscriptions: `home/%d/%i/%u/job/+/status`

last successful tests uses `home/%d/%i/%u/job/1/status` for subscription, but this is not used on our devices

**Comment by qzhuyan** [comment] 2021-04-12 09:30
@gbrehmer 

really appreciated!  glad to know that we are on the same page.

You test with 600 clients which is a very low number of clients.  can you check if they are all connected and subscribed successfully since the issue is on the problem of subscribing timeout?  So I would like to check the counters on the emqx.

another question,
< 196 messages received/s (35% loss)
Is that MQTT message lost or subscription failure/timeout? 

In case of subscription timeout, I have a patch to improve it. 
this is one of them: 
https://github.com/emqx/emqx/pull/4514

**Comment by gbrehmer** [comment] 2021-04-12 10:09
short answer regarding message loss:
it's the output from the benchmark tool 

publisher:
```
sent(121000): total=35627, rate=300(msg/sec)
sent(122000): total=35927, rate=300(msg/sec)
sent(123000): total=36227, rate=300(msg/sec)
sent(124000): total=36527, rate=300(msg/sec)
sent(125000): total=36827, rate=300(msg/sec)
sent(126000): total=37127, rate=300(msg/sec)
```


subscriber:
```
recv(114001): total=21783, rate=196(msg/sec)
recv(115001): total=21979, rate=196(msg/sec)
recv(116001): total=22175, rate=196(msg/sec)
recv(117001): total=22370, rate=195(msg/sec)
recv(118001): total=22567, rate=197(msg/sec)
recv(119001): total=22763, rate=196(msg/sec)
```

on client side there is no error logged
from server log:

```
2021-04-12 07:20:06.556 [error]     supervisor: 'esockd_connection_sup - <0.1715.0>'
    errorContext: connection_crashed
    reason: {timeout,
                {gen_server,call,
                    [<0.1612.0>,
                     {subscribe,
                         <<"home/122/377/username_377/job/+/status">>}]}}
```

**Comment by qzhuyan** [comment] 2021-04-12 10:25
@gbrehmer thanks, the server log shows that it is subscribe timeout!

I guess there are 390 clients out of 600 clients get timeout from the log of benchmark tool.

we are on the same page!

Do you know the roundtip time between nodes in the cluster? a simple ping command can verify that.
such like, 

```
ping 192.168.1.1 -c 10
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=0.941 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=0.535 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=64 time=0.823 ms
64 bytes from 192.168.1.1: icmp_seq=4 ttl=64 time=2.28 ms
64 bytes from 192.168.1.1: icmp_seq=5 ttl=64 time=1.01 ms
64 bytes from 192.168.1.1: icmp_seq=6 ttl=64 time=0.834 ms
64 bytes from 192.168.1.1: icmp_seq=7 ttl=64 time=1.01 ms
64 bytes from 192.168.1.1: icmp_seq=8 ttl=64 time=0.673 ms
64 bytes from 192.168.1.1: icmp_seq=9 ttl=64 time=0.938 ms
64 bytes from 192.168.1.1: icmp_seq=10 ttl=64 time=3.70 ms
```

**Comment by gbrehmer** [comment] 2021-04-15 07:44
ping results:
from host 1 to 2:
```
PING dev-2 (10.3.10.192) 56(84) bytes of data.
64 bytes from dev-2 (10.3.10.192): icmp_seq=1 ttl=64 time=0.669 ms
64 bytes from dev-2 (10.3.10.192): icmp_seq=2 ttl=64 time=0.523 ms
64 bytes from dev-2 (10.3.10.192): icmp_seq=3 ttl=64 time=0.593 ms
64 bytes from dev-2 (10.3.10.192): icmp_seq=4 ttl=64 time=0.466 ms
64 bytes from dev-2 (10.3.10.192): icmp_seq=5 ttl=64 time=1.20 ms
64 bytes from dev-2 (10.3.10.192): icmp_seq=6 ttl=64 time=0.611 ms
64 bytes from dev-2 (10.3.10.192): icmp_seq=7 ttl=64 time=0.530 ms
64 bytes from dev-2 (10.3.10.192): icmp_seq=8 ttl=64 time=0.498 ms
64 bytes from dev-2 (10.3.10.192): icmp_seq=9 ttl=64 time=0.553 ms
64 bytes from dev-2 (10.3.10.192): icmp_seq=10 ttl=64 time=0.573 ms

--- dev-2 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 165ms
rtt min/avg/max/mdev = 0.466/0.621/1.200/0.202 ms
```

from host 1 to 3:
```
--- dev-3 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 143ms
rtt min/avg/max/mdev = 0.455/0.581/0.650/0.062 ms
```

**Comment by qzhuyan** [comment] 2021-04-15 08:14
note: 
1. the performance degradation beween 2.x and 4.x  is mostly caused by `mnesia:wread` calls.
2. There are many lock conflicts on lower  topic level,  we need to consider using a compact trie tree to reduce mnesia trans restart.

**Comment by gbrehmer** [comment] 2021-04-19 11:21
new performance improvement branch from @qzhuyan and @zmstone fixes our subscription problems! Thank you ❤️ 
previously we could reproduce errors with 300 wildcard subscriptions in a short timeframe on 3 node cluster (not the total number of active subscriptions is critical, only the concurrency when all devices creating subscriptions at the same time causes problems).
Now because our test setup is limited we can handle 5000 subscriptions in a short timeframe without any problems. And tests from @qzhuyan show, that even more is possible :)
I can't wait for the release ;)

**Closed** 2021-04-25 10:39 UTC
Labels: Enhancement

**Comment by gbrehmer** [comment] 2021-05-19 20:27
Good news from production: We switched to 4.3.1 on monday and no more load problems. We already testes the most of the problematic scenarios with only a short load peak as reaction. No subscription errors occurred. 🎉 🎉 🎉
