### ISSUE TITLE
Data Export doesnt work

### ISSUE THREAD

**Issue by mangostain** [emqx/emqx#4950] opened 2021-06-07 16:33 UTC
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:

When I type : emqx_ctl data export

Appear the next error... what should I do to export  data?, Thanks!
RPC to emqx@127.0.0.1 error: undef

**Comment by k32** [comment] 2021-06-08 16:34
Hello,
Which version of EMQX are you running?
How did you install it?

**Comment by mangostain** [comment] 2021-06-08 16:43
4.2.7 Broker edition
Using ubuntu 20.04 through .deb install method

**Comment by k32** [comment] 2021-06-08 17:03
Could you reproduce the problem again and collect `emqx.log` at the time when you run the export command?

**Comment by k32** [comment] 2021-06-11 14:41
It looks like export command tries to export data that is only available in the enterprise version. Strange that this bug wasn't caught in the tests. I can prepare a hotfix for this problem, if you wish.

**Comment by mangostain** [comment] 2021-06-11 14:42
Yes please, I need to backup data, thanks!

**Comment by mangostain** [comment] 2021-06-11 14:45
How to know that? What is the command? Thank you...

**Comment by k32** [comment] 2021-06-11 14:48
You can run `emqx_ctl remote_console`, and it should print something like:
```
$ emqx remote_console
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V11.1.7  (abort with ^G)
```

**Comment by mangostain** [comment] 2021-06-11 14:50
Here it is:

`Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

Eshell V10.7  (abort with ^G)`

**Comment by k32** [comment] 2021-06-11 15:01
Sorry, upon closer inspection of the code it appears that the code should handle the situation when the schema registry plugin is not enabled. Could you login into EMQ X shell and run
```erlang
ets:info(emqx_schema).
```
This command should return `undefined` on the open-source version of the broker.
Also `emqx_ctl plugins list`.

**Comment by k32** [comment] 2021-06-11 15:16
As a hack/temporary workaround you can create a file named `emqx_schema_registry.erl` with the following contents:

```erlang
-module(emqx_schema_registry).

-export([get_all_schemas/0]).

get_all_schemas() ->
  [].
```

Save it to some directory, and then run `c("/<full_directory>/emqx_schema_registry").` in EMQ X shell. And then retry exporting data. After that you need to run `code:delete(emqx_schema_registry)`.

**Comment by k32** [comment] 2021-06-14 13:30
Closing, since the root cause is found and the workaround has been presented. Feel free to comment.

**Closed** 2021-06-14 13:30 UTC
Labels: Support
