### ISSUE TITLE
MQTTs configuration seems a bit off.

### ISSUE THREAD

**Issue by LennartOlsen** [emqx/emqx#4129] opened 2021-02-01 10:58 UTC
First off, thanks for a great product.

After messing around with the SSL certificates from Lets Encrypt in setting up MQTTs for the last few days i finally figured out what i did wrong.

So basically i was trying to follow [the otherwise excellent guide](https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6), it states that you have to feed the client with a certificate aswell, which was far from ideal in our situation.

For some reason the guide states that you must feed the `fullcert.pem` file to `listener.ssl.external.certfile` and of course the private key to `listener.ssl.external.keyfile`, what the guide nor the documentation does not state is that infact `listener.ssl.external.certfile` is only read as **one** certificate and therefore is not returning the correct certificate chain to the client causing the issue with having to feed certificates to clients.

I found in the configuration that i could also feed a `listener.ssl.external.cacertfile`, which does however read more than one certificate, therefore we could put the certificates that were ultimately missing in `listener.ssl.external.certfile`.

The solution we came up with are as follows:
* Point `listener.ssl.external.certfile` to `fullchain.pem` or `cert.pem` (as they only read the first certificate this will yield the same result)
* Point `listener.ssl.external.cacertfile` to the combined contents of DST_Root_CA_X3.pem and chain.pem making the order

Specifically the order of the files
* Server CA goes into `listener.ssl.external.certfile`
* Intermediate CA and then root ca goes into `listener.ssl.external.cacertfile`
  * _Pro tip_ use `cat /etc/ssl/certs/ca-cert-DST_Root_CA_X3.pem /etc/letsencrypt/live/$domain/chain.pem > /cacertfile.pem` to get the correct cacertfile into `/cacertfile.pem`

The issue is also highlighted to some extend in https://github.com/emqx/emqx/issues/890

**What would you like to be added/modified**:
The docs and possibly [this guide](https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6) need to be updated to include the fact that `listener.ssl.external.certfile` only reads the first certificate in the file and the user needs to put the root ca and intermediate into `listener.ssl.external.cacertfile`.

**Why is this needed**:
In accordance to my lengthy precursor i see other people having this issue and at the very least this information should be easily accessible, i dont feel like the Lets Encrypt usecase that i have is specific to our setup nor is the requirement to not have to send certificates to clients.

Furthermore its important to promote a safe and secure internet this also applies to MQTT.

**Comment by zmstone** [comment] 2021-02-01 11:27
@LennartOlsen thank you for the detailed report.
I fully agree that our document has room for improvement.

I would like to ask your help to clarify, or maybe even verify somethings in your setup.

The `certfile` option (common for TLS client/server in Eralng) is mapped to the SSL option used in Erlang, which is documented as:
> Path to a file containing the user certificate on PEM format or possible several certificates where the first one is the users certificate and the rest of the certificates constitutes the certificate chain. For more details see cert(),
So I believe, if there are intermediate CA (not trusted by client), they should be chained, and it should be sent in the TLS handshake.

Based on my understanding of Erlang documentation and experience: `cacertfile` option is used to validate peer certs, the peer should send a chain of certs (can be a full chain with root cert included, although not required).
Meaning, `cacertfile` can be only a root certificate if the peer (client in your case) sends the intermediate CA certificates.

**Comment by LennartOlsen** [comment] 2021-02-01 12:06
@zmstone so the way we figured out that someting was amiss in the `listener.ssl.external.certfile` was by using wireshark to intercept the handshake request and there we found that only one of the certificates found in the `certfile` was being transmitted. Its fairly easy to prove that only one certificate is sent from the `certfile`.

The `cacertfile` might be used for validating peer certs but we saw that it was transmitted and the only way to obtain the full certificate chain.

**Comment by zmstone** [comment] 2021-02-01 12:12
@LennartOlsen thank you. I’ll run some tests to confirm.

**Comment by tigercl** [comment] 2021-02-05 09:58
@LennartOlsen Hello, after our confirmation, `certfile` should only be used to specify server or client certificate. The CA certificate in `cacertfile`, if it can form a continuous certificate chain with the certificate specified by `certfile`, then they will be sent to the peer during the handshake phase. 

If the root CA and intermediate CA trusted by the peer can form a complete certificate chain with these certificates, the authentication is passed. 

As for whether the peer needs to specify a CA that it trusts, it depends on the client's implementation. Take `openssl s_client` as an example, it will consider all CA certificates in the directories managed by the superuser to be trusted. When your CA certificates exist in these directories, you do not need to specify the `cacertfile` field. The remaining CA certificate in `cercertfile` that has not been sent to the peer will be used to verify the integrity of the peer's certificate chain.

**Comment by LennartOlsen** [comment] 2021-02-05 11:07
@tigercl i am not quite sure i understand.

The deal is :
`certfile` only sends the first certificate in the file that its given, and one certificate will never be enough to warrant a chain of trust between the client and the server (unless the client already has the remaining certificates)
`cacertfile` sends all the certificates in the file that its given.

As i understand the `cacertfile` is used for validating the peer certificate, unfortunately my knowledge here is limited. But through my testing i found that the certficicates specified in `cacertfile` was being transmitted during the handshake thus providing a full chain of trust.

I dont know how different clients interpet the chain of trust, but as far as i understand the root CA is "optional", many clients may have that already - But the intermediate and server CA must come from the server somehow, either as a prerequisite or at handshake time.

So if i am misusing the `cacertfile` is simply because of limits to the `certfile` capabilities.

In reference to https://github.com/emqx/emqx/issues/4129#issuecomment-770786507 it seems that the `certfile` is only picking up the first certificate of the pem file, although the [documentation](https://erlang.org/doc/man/ssl.html#type-cert_pem) might state otherwise.

**Comment by zmstone** [comment] 2021-02-05 11:07
Thank you @tigercl for verifying this.
I find the OTP document is quite unclear about where to put the intermediate CA.
Now that your tests confirms @LennartOlsen's suggestions,
@tigercl could you help to follow up on this and make sure we have the guide in updated.
(and maybe clarify it in emqx-docs) too.

**Comment by zmstone** [comment] 2021-02-05 11:14
Hi @LennartOlsen
I believe @tigercl tests confirmed your suggestions.

Sorry I was adding noise earlier, because I failed to understand OTP document,
and my memory from experience did not serve me well.

The key point, I believe, is where should we put the intermediate CA certificate for Erlang's SSL library.
1. Only in certfile (wrong)
2. Only in cacertfile (OK)
3. In both certfile and cacertfile (also OK).

And I am sure you are right about the ordering of the certificates too --- nontheless worth double checking @tigercl

**Comment by zmstone** [comment] 2021-02-05 11:22
by emqx-docs, I mean this:

https://github.com/emqx/emqx-docs/blob/develop/en_US/configuration/configuration.md

We should be rather verbose about whats and hows for ssl options.

**Comment by zmstone** [comment] 2021-02-28 09:50
https://github.com/emqx/emqx-docs/pull/659

**Comment by zmstone** [comment] 2021-02-28 10:42
I have also updated the medium article:
https://emqx.medium.com/using-lets-encrypt-certificates-in-emq-b11e0e57efa6
With the `cacertfile` config added.

I also added a "Mutual certificate authentication" section with a big NOTE to clarify that intermediate certs for server should be added to `ca.pem`

**Comment by zmstone** [comment] 2021-02-28 10:43
@LennartOlsen Thank you for your suggestions and patient.
Closing this issue now.

**Closed by zmstone** 2021-02-28 10:43 UTC
Labels: Feature
