### ISSUE TITLE
ACL user

### ISSUE THREAD

**Issue by archerian** [emqx/emqx#2555] opened 2019-05-21 01:26 UTC
#### Environment

- OS: Windows 10
- Erlang/OTP: 21
- EMQ: 3.1.1

#### Description

In

{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

how is the user 'dashboard' authenticated?

**Comment by HJianBo** [comment] 2019-05-21 02:08
As the ACL rule `{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.` described, it allows the named 'dashboard' user to subscribe a list of topic filter, that is '$SYS/#' here.

The mechanism of EMQ X access control, you can see our [User Guide](
https://developer.emqx.io/docs/broker/v3/en/guide.html#access-control-list) document

**Comment by archerian** [comment] 2019-05-21 11:59
Thanks for the reply, I meant how is the user authenticated before ACL is applied? Is is possible to use emqc_auth_username to authenticate the user and then apply ACL after?

**Comment by HJianBo** [comment] 2019-05-21 12:54
> Is is possible to use emqc_auth_username to authenticate the user and then apply ACL after

Yes. The Authentication chain and the ACL chain is an independent mechanism.

**Comment by archerian** [comment] 2019-05-21 15:16
Thanks again for your reply. I am not sure if they are working. I can use emqx_auth_username to get allow only authenticated users, but then the ACL does not seem to enforce the topic filters assigned to the already authenticated user.

**Comment by HJianBo** [comment] 2019-05-22 10:55
Do you reload the ACL rules by `emqx_ctl acl reload` after changing etc/acl.conf?

**Comment by archerian** [comment] 2019-05-22 13:15
Yes, I reloaded the rules and in another instance restarted the EMQX server.

**Comment by HJianBo** [comment] 2019-05-22 15:21
I have no idea. Can you provide more details to help me reproduce/understand it? i.e: started plugins, ACL rules content, Client's username/password etc.

**Comment by archerian** [comment] 2019-05-22 15:56
I downloaded 3.1.1 and unzipped it, ran it from console to see if it runs fine, it does.
Checked to see if emqx_auth_username is enabled. 
Use emqx_ctl to create users user1 password1. 
I updated emqx.conf to allow_anonymous = false and acl_nomatch = deny
Started the broker again, I can connect as user1 password1

Then I modified acl.conf to be like this ->

{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.

{allow, {user, "user1"}, subscribe, ["T1"]}.

{deny, all}.

And reloaded acl using emqx_ctl acl reload. Even now, the user user1 can subscribe to any topic, not just T1. Connection fails if I provide the wrong user/password, so authentication is working, but authorization does not seem to be as it allows user1 to subscribe to any topic.

**Comment by HJianBo** [comment] 2019-05-23 01:49
The ACL rules are matching by the presented order of acl.conf. 

So maybe the `{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.` has matched first, because your client is running on the same machine with EMQ X broker.

**Comment by archerian** [comment] 2019-05-23 14:40
thanks for the reply, no I am running mosquitto_sub as the client from a different machine.

**Comment by archerian** [comment] 2019-06-04 14:10
Hello HJianBo, can you please offer any assistance on this?

**Comment by tradingtrace** [comment] 2019-06-04 17:00
Hi @archerian,

Could you please provide the `mosquitto_sub` log with the `-d` parameter?

I just tried the below steps, and everything looks fine.
1. Run `bin/emqx_ctl plugins load emqx_auth_username`
2. Run `bin/emqx_ctl users add user1 aaa`
3. Run `bin/emqx_ctl users add user2 aaa`
4. Modify the etc/acl.config
```erlang
%% acl.config
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{allow, {user, "user2"}, pubsub, ["$SYS/#", "#"]}.  %% added

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.

{allow, {user, "user1"}, subscribe, ["T1"]}.  %% added

{deny, all}. 
```
5. Connect with a wrong password
```shell
$ mosquitto_sub -d -h x.x.x.x -u user1 -P bbb -t "T1"
Client mosq/U7yWHAgxutVXEkN2tw sending CONNECT
Client mosq/U7yWHAgxutVXEkN2tw received CONNACK (4)
Connection Refused: bad user name or password.
Client mosq/U7yWHAgxutVXEkN2tw sending DISCONNECT
```
6. Subscribe the topic `T2` (received `Unspecified error` `128`)
```shell
$ mosquitto_sub -d -h x.x.x.x -u user1 -P aaa -t "T2"
Client mosq/EB8GojRENyLmbNUT09 sending CONNECT
Client mosq/EB8GojRENyLmbNUT09 received CONNACK (0)
Client mosq/EB8GojRENyLmbNUT09 sending SUBSCRIBE (Mid: 1, Topic: T2, QoS: 0, Options: 0x00)
Client mosq/EB8GojRENyLmbNUT09 received SUBACK
Subscribed (mid: 1): 128
```
7. Subscribe the allowed topic `T1` (succeed)
```shell
mosquitto_sub -d -h x.x.x.x -u user1 -P aaa -t "T1"
Client mosq/hqXjAHo48kH91b57Rx sending CONNECT
Client mosq/hqXjAHo48kH91b57Rx received CONNACK (0)
Client mosq/hqXjAHo48kH91b57Rx sending SUBSCRIBE (Mid: 1, Topic: T1, QoS: 0, Options: 0x00)
Client mosq/hqXjAHo48kH91b57Rx received SUBACK
Subscribed (mid: 1): 0
```
8. Publish a message from user2 on topic `T1`
```shell
$ mosquitto_pub -d -h x.x.x.x -u user2 -P aaa -t "T1" -m "This is a message from user2"
Client mosq/ECiIYalf04foTSKh27 sending CONNECT
Client mosq/ECiIYalf04foTSKh27 received CONNACK (0)
Client mosq/ECiIYalf04foTSKh27 sending PUBLISH (d0, q0, r0, m1, 'T1', ... (28 bytes))
Client mosq/ECiIYalf04foTSKh27 sending DISCONNECT
```
9. user1 received the message
```shell
Client mosq/8CV9HBO43Zb7eNRbbv received PUBLISH (d0, q0, r0, m0, 'T1', ... (28 bytes))
This is a message from user2
```

**Comment by HJianBo** [comment] 2019-07-01 08:44
Hi, @archerian Has the problem been solved?

**Comment by HJianBo** [comment] 2020-03-30 05:53
Close it due to outdated. Thanks to everybody contributions :)

**Closed by HJianBo** 2020-03-30 05:53 UTC
Labels: Support
