### ISSUE TITLE
Ekka(AutoCluster): discovered nodes outside cluster

### ISSUE THREAD

**Issue by fred2807** [emqx/emqx#8418] opened 2022-07-05 02:29 UTC
### What happened?

<html>
<body>

2022-07-05T02:17:11.323758+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-1.emqx-v5-headless.emqx-cs.svc.cluster.local']
--
Tue, Jul 5 2022 10:17:11 am | 2022-07-05T02:17:11.330710+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
Tue, Jul 5 2022 10:17:25 am | 2022-07-05T02:17:25.770698+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-1.emqx-v5-headless.emqx-cs.svc.cluster.local']
Tue, Jul 5 2022 10:17:25 am | 2022-07-05T02:17:25.777478+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
Tue, Jul 5 2022 10:17:40 am | 2022-07-05T02:17:40.770709+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-1.emqx-v5-headless.emqx-cs.svc.cluster.local']
Tue, Jul 5 2022 10:17:40 am | 2022-07-05T02:17:40.778760+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
Tue, Jul 5 2022 10:17:55 am | 2022-07-05T02:17:55.384659+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-1.emqx-v5-headless.emqx-cs.svc.cluster.local']
Tue, Jul 5 2022 10:17:55 am | 2022-07-05T02:17:55.391325+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
Tue, Jul 5 2022 10:18:07 am | 2022-07-05T02:18:07.416720+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-1.emqx-v5-headless.emqx-cs.svc.cluster.local']
Tue, Jul 5 2022 10:18:07 am | 2022-07-05T02:18:07.423320+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
Tue, Jul 5 2022 10:18:19 am | 2022-07-05T02:18:19.715742+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-1.emqx-v5-headless.emqx-cs.svc.cluster.local']
Tue, Jul 5 2022 10:18:19 am | 2022-07-05T02:18:19.722515+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms

2022-07-05T02:17:20.862737+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-07-05T02:17:36.533712+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-0.emqx-v5-headless.emqx-cs.svc.cluster.local']
2022-07-05T02:17:36.542141+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-07-05T02:17:50.838734+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-0.emqx-v5-headless.emqx-cs.svc.cluster.local']
2022-07-05T02:17:50.846973+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-07-05T02:18:06.309647+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-0.emqx-v5-headless.emqx-cs.svc.cluster.local']
2022-07-05T02:18:06.318033+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-07-05T02:18:21.898659+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-0.emqx-v5-headless.emqx-cs.svc.cluster.local']
2022-07-05T02:18:21.906586+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-07-05T02:18:35.743640+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-0.emqx-v5-headless.emqx-cs.svc.cluster.local']
2022-07-05T02:18:35.753584+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-07-05T02:18:50.637661+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-0.emqx-v5-headless.emqx-cs.svc.cluster.local']
2022-07-05T02:18:50.646551+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-07-05T02:19:05.956712+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx-v5@emqx-v5-0.emqx-v5-headless.emqx-cs.svc.cluster.local']
2022-07-05T02:19:05.965667+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms

![image](https://user-images.githubusercontent.com/108706865/177236720-0d22b2e2-619f-436c-b8ab-6235ccd45f1a.png)

![image](https://user-images.githubusercontent.com/108706865/177237105-75bd9349-54a6-4d28-b592-7b11f5601e73.png)

![image](https://user-images.githubusercontent.com/108706865/177237358-1b375281-1ac4-45ec-be98-0d5788e82f96.png)

![image](https://user-images.githubusercontent.com/108706865/177237463-8a798ac3-799e-4257-9a8e-93890b5982a9.png)

如上:
2台机器，一台百度云服务器、一台华为云服务器
rancher 2.6.6  k8s:1.23.7   pod started success , but  cluster cluster failed , and v4.4.4 successed

</body>
</html>

> 

### What did you expect to happen?

cluster successed 

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker

emqx: v5.0.2 

![image](https://user-images.githubusercontent.com/108706865/177236509-4502cb18-6722-4c55-beb3-f5ba1a4c38c1.png)

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by lafirest** [comment] 2022-07-05 02:39
@fred2807, 4.x can't cluster with 5.x

**Comment by fred2807** [comment] 2022-07-05 02:49
> 
I kown ,it is two emqx cluster  but  two same k8s nodes   v4.4.4 is succeed  v5.0.2 failed

![image](https://user-images.githubusercontent.com/108706865/177239674-361c318b-0761-4ea7-80a9-877548e09f4b.png)

![image](https://user-images.githubusercontent.com/108706865/177239738-f3cc7c56-3489-44db-8eef-331763ceff73.png)

**Comment by zmstone** [comment] 2022-07-05 05:47
The v5 suffix will make erlang distribution to use port number 4375.
Could you check if the containers can communicate with each other over this port?

**Comment by fred2807** [comment] 2022-07-05 06:04
> communicate
I try just now not success,  the pic :
before add port :
![image](https://user-images.githubusercontent.com/108706865/177259558-3944ac66-6752-48c2-af73-1f8aa75d0a92.png)


after add port 

![image](https://user-images.githubusercontent.com/108706865/177259776-41f3c040-3217-4db7-b3a9-4994153e9954.png)


![image](https://user-images.githubusercontent.com/108706865/177259697-55964818-53c1-4cd1-8893-fc91ca6a17bc.png)


I use the same two node in tencent ,can success !  if must be same  Cloud producer(是否一定要是相同的云产商的服务器)，now a node is baidu ,other node is huawei, cluster failed

**Comment by zmstone** [comment] 2022-07-05 06:13
It’s likely a network issue.
I’d imagine if you have two k8s workers from the same provider, they run in a private network?
And when you have them from different providers, they need to connect each other over the internet?

Btw: Another port needed for nodes to connect each other after joining the cluster is: 5369

**Comment by fred2807** [comment] 2022-07-05 06:17
> The node name v5 suffix will make erlang distribution to use port number 4375. Could you check if the containers can communicate with each other over this port?

@zmstone  thank you !

the two same  cloud producer in tencent ,can success:

![image](https://user-images.githubusercontent.com/108706865/177261319-4df02005-f2e0-4f12-b193-2efeccab816f.png)

the log is ok :
![image](https://user-images.githubusercontent.com/108706865/177261598-3ab42892-0ea9-40b0-aec8-8b362a140ea3.png)

**Comment by fred2807** [comment] 2022-07-05 06:29
> It’s likely a network issue. I’d imagine if you have two k8s workers from the same provider, they run in a private network? And when you have them from different providers, they need to connect each other over the internet?
> 
> Btw: Another port needed for nodes to connect each other after joining the cluster is: 5369



yes ,I have four nodes ,two tecent nodes , one baidu, other one huawei ;  
two tencent nodes emqx cluster is ok !  other two emqx cluter  failed

**Comment by zmstone** [comment] 2022-07-05 06:41
Since it’s running in k8s, I supposed it should not be an issue, but: the FQDN has to be resolvable from all the nodes in the cluster.
One way to exclude DNS resolution issue is to use IP address.
If the port is mapped to docker host, you can use the host’s ip for node name.
E.g. `EMQX_NODE_NAME=emqx-v5@123.45.67.89`

**Comment by zmstone** [comment] 2022-07-05 06:43
Oh if you use ip, then it’s not k8s auto clustering, it’s just a way to troubleshoot

**Comment by fred2807** [comment] 2022-07-05 06:55
> Since it’s running in k8s, I supposed it should not be an issue, but: the FQDN has to be resolvable from all the nodes in the cluster. One way to exclude DNS resolution issue is to use IP address. If the port is mapped to docker host, you can use the host’s ip for node name. E.g. `EMQX_NODE_NAME=emqx-v5@123.45.67.89`

Thank you very much ,cost you time; i am sorry !
I will try continue; I cost time for days;
Strangely, the two tencent nodes is perfect success  with k8s discovery and hostname   not ip !   
I Provide rancher account , you can in help me see?  when you are free, thank you again!

**Comment by zmstone** [comment] 2022-07-05 07:05
I’m afraid I don’t have the perfect k8s skills to help you.

**Comment by fred2807** [comment] 2022-07-05 07:11
> I’m afraid I don’t have the perfect k8s skills to help you.

@zmstone  Are you chinese?  +weixin each other ,I provider rancher Account,you can see when you free ? I have study k8s not long also; just need to see emqx problem ,I feel cogfig is ok ,the env variable is ok，but not know why because two tecent nodes is normal  呵呵,谢谢了哈！

**Comment by zmstone** [comment] 2022-07-06 19:08
@fred2807 我的微信账号和 github 一样的。

**Comment by fred2807** [comment] 2022-07-07 02:08
> @fred2807 我的微信账号和 github 一样的。
好的，加了

**Comment by zmstone** [comment] 2022-07-18 19:59
Hi again.
It seems that the discovery succeeded, but failed to join.
If you turn on debug level logging, there should be more logs so we know more details on discovery or connect failures.

Since 4.4 is basically running the same code, another try is maybe to get rid of the `v5` suffix so it will use the same ports like 4.4 (I know you have tried to open ports, but just in case).

**Comment by zmstone** [comment] 2022-08-09 11:28
Not sure how actionable this is.
Closing this issue for now. Please feel free to reopen or create a new one if there is new findings.

**Closed by zmstone** 2022-08-09 11:28 UTC

**Comment by natalia-nasonova** [comment] 2022-09-29 13:33
Hello,

I have the same issue. I have cluster of 3 nodes and all of them have version 5.0.8 (same happens when _all_ nodes have version 5.0.0). I run them as containers in docker swarm. I don't use version in the name, and network is fine because manual node join works perfect. The issue is that I have to do that manually. The third node keeps logging "discovery did not succeed" and "discovered nodes outside cluster" and never connects to the cluster unless is joined manually.

Nodes emqx@mqttbroker1.abc.tech and emqx@mqttbroker2.abc.tech are in cluster and emqx@mqttbroker3.abc.tech cannot discover it.
```
root@mqtt-test-1:~# docker exec -it af emqx_ctl cluster status
Cluster status: #{running_nodes =>
                      ['emqx@mqttbroker1.abc.tech',
                       'emqx@mqttbroker2.abc.tech'],
                  stopped_nodes => ['emqx@mqttbroker3.abc.tech']}
```

```
root@mqtt-test-2:~# docker exec -it 2eb emqx_ctl cluster status
Cluster status: #{running_nodes => ['emqx@mqttbroker3.abc.tech'],
                  stopped_nodes => []}
```
Steps to reproduce:
1. Create cluster of three nodes with discovery strategy=static
2. Kill one of nodes and start it, until it stops reappearing after failure on dashboard (in my case the issue arose when i killed the node soon after its start)

Log of node that is not in cluster
```
dashboard.default_password = EMQX_DASHBOARD__DEFAULT_PASSWORD = ******
dashboard.default_username = EMQX_DASHBOARD__DEFAULT_USERNAME = ******
rpc.port_discovery = EMQX_RPC__PORT_DISCOVERY = manual
log.file_handlers.default.enable = EMQX_LOG__FILE_HANDLERS__DEFAULT__ENABLE = false
log.console_handler.enable = EMQX_LOG__CONSOLE_HANDLER__ENABLE = true
cluster.static.seeds = EMQX_CLUSTER__STATIC__SEEDS = [<<"emqx@mqttbroker1.abc.tech">>,<<"emqx@mqttbroker2.abc.tech">>,<<"emqx@mqttbroker3.abc.tech">>]
cluster.discovery_strategy = EMQX_CLUSTER__DISCOVERY_STRATEGY = static
node.name = EMQX_NODE__NAME = emqx@mqttbroker3.abc.tech
Listener ssl:default on :8883 started.
Listener tcp:default on :1883 started.
Listener ws:default on :8083 started.
Listener wss:default on :8084 started.
Listener http:dashboard on :18083 started.
EMQX 5.0.8 is running now!
{"backend":"built_in_database","enable":true,"id":"password_based:built_in_database","mechanism":"password_based","password_hash_algorithm":{"name":"sha256","salt
_position":"suffix"},"user_id_type":"username"}{"is_superuser":false,"user_id":"test"}2022-09-29T09:52:00.235573+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@mqttbroker1.abc.tech','emqx@mqttbroker2.abc.tech']
2022-09-29T09:52:00.235907+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-09-29T09:52:20.100579+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@mqttbroker1.abc.tech','emqx@mqttbroker2.abc.tech']
2022-09-29T09:52:20.100838+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-09-29T09:52:39.571652+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@mqttbroker1.abc.tech','emqx@mqttbroker2.abc.tech']
2022-09-29T09:52:39.571834+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-09-29T09:53:00.111524+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@mqttbroker1.abc.tech','emqx@mqttbroker2.abc.tech']
2022-09-29T09:53:00.111747+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-09-29T09:53:20.447557+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@mqttbroker1.abc.tech','emqx@mqttbroker2.abc.tech']
2022-09-29T09:53:20.447835+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
2022-09-29T09:53:40.793666+00:00 [warning] Ekka(AutoCluster): discovered nodes outside cluster: ['emqx@mqttbroker1.abc.tech','emqx@mqttbroker2.abc.tech']
```
Log of node1 that is in cluster
```
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | dashboard.default_password = EMQX_DASHBOARD__DEFAULT_PASSWORD = ******
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | dashboard.default_username = EMQX_DASHBOARD__DEFAULT_USERNAME = ******
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | rpc.port_discovery = EMQX_RPC__PORT_DISCOVERY = manual
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | log.file_handlers.default.enable = EMQX_LOG__FILE_HANDLERS__DEFAULT__ENABLE = false
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | log.console_handler.enable = EMQX_LOG__CONSOLE_HANDLER__ENABLE = true
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | cluster.static.seeds = EMQX_CLUSTER__STATIC__SEEDS = [<<"emqx@mqttbroker1.abc.tech">>,<<"emqx@mqttbroker2.abc.tech">>,<<"emqx@mqttbroker3.abc.tech">>]
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | cluster.discovery_strategy = EMQX_CLUSTER__DISCOVERY_STRATEGY = static
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | node.name = EMQX_NODE__NAME = emqx@mqttbroker1.abc.tech
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | Listener ssl:default on :8883 started.
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | Listener tcp:default on :1883 started.
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | Listener ws:default on :8083 started.
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | Listener wss:default on :8084 started.
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | Listener http:dashboard on :18083 started.
mqtt_mqtt.1.lowr35eiuk68@mqtt-test-1    | 2022-09-29T09:46:17.654318+00:00 [error] message=channel_closed driver=tcp socket="#Port<0.28>" action=stopping
```
Log of node2 that is in cluster
```
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | dashboard.default_password = EMQX_DASHBOARD__DEFAULT_PASSWORD = ******
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | dashboard.default_username = EMQX_DASHBOARD__DEFAULT_USERNAME = ******
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | rpc.port_discovery = EMQX_RPC__PORT_DISCOVERY = manual
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | log.file_handlers.default.enable = EMQX_LOG__FILE_HANDLERS__DEFAULT__ENABLE = false
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | log.console_handler.enable = EMQX_LOG__CONSOLE_HANDLER__ENABLE = true
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | cluster.static.seeds = EMQX_CLUSTER__STATIC__SEEDS = [<<"emqx@mqttbroker1.abc.tech">>,<<"emqx@mqttbroker2.abc.tech">>,<<"emqx@mqttbroker3.abc.tech">>]
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | cluster.discovery_strategy = EMQX_CLUSTER__DISCOVERY_STRATEGY = static
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | node.name = EMQX_NODE__NAME = emqx@mqttbroker2.abc.tech
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | Listener ssl:default on :8883 started.
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | Listener tcp:default on :1883 started.
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | Listener ws:default on :8083 started.
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | Listener wss:default on :8084 started.
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | Listener http:dashboard on :18083 started.
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | EMQX 5.0.8 is running now!
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | 2022-09-28T19:03:29.476091+00:00 [warning] Ekka(AutoCluster): discovery did not succeed; retrying in 5000 ms
mqtt_mqtt.2.ctndfbaid7eg@mqtt-test-3    | {"backend":"built_in_database","enable":true,"id":"password_based:built_in_database","mechanism":"password_based","password_hash_algorithm":{"name":"sha256","salt_position":"suffix"},"user_id_type":"username"}{"is_superuser":false,"user_id":"test"}2022-09-29T09:36:09.467106+00:00 [error] message=channel_closed driver=tcp socket="#Port<0.31>" action=stopping
```
