### ISSUE TITLE
Faild to install some plugins

### ISSUE THREAD

**Issue by aiden-leong** [emqx/emqx#1946] opened 2018-11-03 15:27 UTC
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: R21/10.0.5
- EMQ: 3.0  .deb

#### Description

Faild to install some plugins.
E.g. emqx_auth_mysql

Method1  via Web GUI
Error: `Request failed with status code 500`

Method2 via CLI
```
emqx_ctl plugins load emqx_auth_mysql
Usage: emqx_ctl
--------------------------------------------------------------------------------
admins add <Username> <Password> <Tags>         # Add dashboard user
admins passwd <Username> <Password>             # Reset dashboard user password
admins del <Username>                           # Delete dashboard user
```
syntax `emqx_ctl plugins` does not exist

Following: http://emqtt.com/docs/v3/guide.html#mysql

**Comment by andy1247008998** [comment] 2018-11-03 18:28
1. fixed by input correct credentials in `emqx_auth_mysql.conf`.
2. Web GUI should provide much more friendly error info rather than `500` error.
3. Database plugin should be loaded even if it can not connect to the database. Let's say if we lost connection to a remote database for only 1 minute, caused by database service reboot or Internet shaking, database plugin may crash for hours until someone manually restart emqx.
4. When I click `config` in Web GUI, I get `Network Error` and `No Default Configuration`, even when this plugin is loaded.

**Comment by Gilbert-Wong** [comment] 2018-11-05 01:36
Thanks for your advice, we'll improve it.

**Comment by fuji4** [comment] 2018-12-03 14:09
I have the same problem when trying to install `emqx_auth_pgsql`

**Comment by zmstone** [comment] 2021-08-09 20:35
I believe this bug has been fixed in later versions.

**Closed by zmstone** 2021-08-09 20:35 UTC
Labels: Enhancement, Discussion
