### ISSUE TITLE
EMQX Bridging in Cluster causes duplicate publishes to destination

### ISSUE THREAD

**Issue by haimiko** [emqx/emqx#6897] opened 2022-01-28 21:19 UTC
### Subject of the issue
Describe your issue here.

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

- EMQ X version (e.g. `emqx_ctl status`): 4.3.10
- Hardware configuration (e.g. `lscpu`): vmware esx
- OS (e.g. `cat /etc/os-release`):  Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 4.15.0-136-generic
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### Steps to reproduce
- Copied the attached emqx_bridge_mqtt.conf to /etc/emqx/plugins on each of my nodes in my cluster.
[emqx_bridge_mqtt.conf.txt](https://github.com/emqx/emqx/files/7961755/emqx_bridge_mqtt.conf.txt)
- restarted emqx on each of the nodes
- Logged on to the dashboard and started "emqx_bridge_mqtt" plugin on each of the nodes.
- Subscribed to topic described by bridge.mqtt.bg.forwardsm, on the forward broker address described by configuration bridge.mqtt.bg.address
- Published a message to the above topic to the local broker with the bridging configuration..

### Expected behaviour
Only one message gets published to the target destination broker.

### Actual behaviour
I receive duplicate messages, one for every node  in the cluster unless I stop the bridging plugin on all but one node.   If the bridging is stopped on all but one node (via the dashboard) then only 1 message is received as expected.

#### Log files
I tried running the node_dump script but I received the following errors. Hence no logs.

./node_dump
Running node dump in /
./node_dump: 9: .: Can't open //releases/emqx_vars

I did however include emqx log snippets, at the time of the testing, from each of the nodes.

[emqx.log.3.txt](https://github.com/emqx/emqx/files/7961884/emqx.log.3.txt)
[emqx.log.2.txt](https://github.com/emqx/emqx/files/7961885/emqx.log.2.txt)
[emqx.log.1.txt](https://github.com/emqx/emqx/files/7961886/emqx.log.1.txt)

**Comment by haimiko** [comment] 2022-02-12 17:30
Great news.  What's the ETA on that fix release?

**Comment by zmstone** [comment] 2022-02-12 19:03
it’s hard to say at this moment. (4.3.12 went out today)
But should be in less than 4 weeks.

**Comment by haimiko** [comment] 2022-02-12 20:59
Thank you.

**Comment by gsychev** [comment] 2022-02-15 12:25
Hi, @haimiko, could you please help where and how you were running the `node_dump` tool?
What emqx distribution did you use? Was is docker?

**Comment by haimiko** [comment] 2022-02-15 15:33
@gsychev , I'm running : 4.3.10 Ubuntu 20 debian package.  Not docker.  I tried running the tool and got this error:
./node_dump
Running node dump in /
./node_dump: 9: .: Can't open //releases/emqx_vars

**Comment by gsychev** [comment] 2022-02-16 12:09
@haimiko , Hi again. I've tried to reproduce this issue inside `docker` and I couldn't

```Dockerfile
FROM ubuntu:20.04

RUN apt update && apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

RUN curl -fsSL https://repos.emqx.io/gpg.pub | apt-key add -

RUN add-apt-repository \
    "deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/ubuntu/ \
    ./$(lsb_release -cs) \
    stable"

RUN apt update && apt install -y emqx
```

Just copy-pasted from official installation instructions

And in shell
```bash
root@73ed60781322:/# emqx start
root@73ed60781322:/# mkdir /usr/lib/emqx/log
root@73ed60781322:/# ./usr/lib/emqx/bin/node_dump
Running node dump in /usr/lib/emqx
./usr/lib/emqx/bin/node_dump: 1: eval: netstat: not found
Created a node dump log/node_dump_20220216_120807.tar.gz

WARNING: this script tries to obfuscate secrets, but make sure to
inspect log/conf.dump file manually before uploading the node dump
to a public location.
```

**Comment by haimiko** [comment] 2022-02-16 15:46
> @haimiko , Hi again. I've tried to reproduce this issue inside `docker` and I wasn't able to reproduce this
> 
> ```dockerfile
> FROM ubuntu:20.04
> 
> RUN apt update && apt install -y \
>     apt-transport-https \
>     ca-certificates \
>     curl \
>     gnupg-agent \
>     software-properties-common
> 
> RUN curl -fsSL https://repos.emqx.io/gpg.pub | apt-key add -
> 
> RUN add-apt-repository \
>     "deb [arch=amd64] https://repos.emqx.io/emqx-ce/deb/ubuntu/ \
>     ./$(lsb_release -cs) \
>     stable"
> 
> RUN apt update && apt install -y emqx
> ```
> 
> Just copy-pasted from official installation instructions
> 
> And in shell
> 
> ```shell
> root@73ed60781322:/# emqx start
> root@73ed60781322:/# mkdir /usr/lib/emqx/log
> root@73ed60781322:/# ./usr/lib/emqx/bin/node_dump
> Running node dump in /usr/lib/emqx
> ./usr/lib/emqx/bin/node_dump: 1: eval: netstat: not found
> Created a node dump log/node_dump_20220216_120807.tar.gz
> 
> WARNING: this script tries to obfuscate secrets, but make sure to
> inspect log/conf.dump file manually before uploading the node dump
> to a public location.
> ```
> 
> Perhaps there's something I'm missing. Could you help me out with this?

Got eh node_dump working.  Here is the file. 
[node_dump_20220216_073743.tar.gz](https://github.com/emqx/emqx/files/8081262/node_dump_20220216_073743.tar.gz)

**Comment by zmstone** [comment] 2022-02-16 17:10
Hi @haimiko
thank you for following up with the node_dump investigation.
the original issue however is quite clear, and there is no need for a node dump for further investigation.
what @gsychev is investigating now is why node_dump did not work for you when you reported the issue.
It would be great if @haimiko can help to reproduce the node_dump failure, and create a new issue to follow up (just to keep this thread clean).

**Comment by terry-xiaoyu** [comment] 2022-02-17 02:00
> @gsychev , I'm running : 4.3.10 Ubuntu 20 debian package. Not docker. I tried running the tool and got this error:
> ./node_dump
> Running node dump in /
> ./node_dump: 9: .: Can't open //releases/emqx_vars

Did you just download the [node_dump script](https://github.com/emqx/emqx/blob/master/bin/node_dump) from github to your machine and run? The tool cannot be used like that.

The tool should already be installed after you installing the emqx, so just do:

```
which node_dump
```

If you find it, then

```
node_dump
```

**Comment by haimiko** [comment] 2022-02-17 03:16
> > @gsychev , I'm running : 4.3.10 Ubuntu 20 debian package. Not docker. I tried running the tool and got this error:
> > ./node_dump
> > Running node dump in /
> > ./node_dump: 9: .: Can't open //releases/emqx_vars
> 
> Did you just download the [node_dump script](https://github.com/emqx/emqx/blob/master/bin/node_dump) from github to your machine and run? The tool cannot be used like that.
> 
> The tool should already be installed after you installing the emqx, so just do:
> 
> ```
> which node_dump
> ```
> 
> If you find it, then
> 
> ```
> node_dump
> ```

@terry-xiaoyu , I made the same mistake.  Documentation was not clear.  The node_dump script is already located in /usr/lib/emqx/bin.  Just create /usr/lib/emqx/log directory first before running.

**Comment by haimiko** [comment] 2022-03-07 16:06
@zmstone    I'm also seeing 15-90 sec bridging/forwarding delays from the original publish.  Could this be related?

**Comment by zmstone** [comment] 2022-03-07 20:11
@haimiko I'm not entirely sure, if you have more than one out-going bridge configured in one cluster, you'll see duplicated messages, but not necessary mean they will be delayed.
imo, these are two different issues.

**Comment by matthewGEA** [comment] 2022-04-04 03:59
> Hi @haimiko This is a design defect, the 'forward' bridge is essentially a subscriber internally which subscribes to messages from other nodes too.
> 
> we'll fix it in a backward compatible way. maybe will add a new config entry like `local_only` and default it to `false`.

Is the idea that after this feature is implemented, and `local_only=true` that the bridge plugin can be enabled on each node since each will only forward the messages it has received from directly-connected clients and it will not forward the messages it has received through the clustering mechanism?

**Comment by zmstone** [comment] 2022-04-04 05:55
the ongoing design is actually more flexible. it will be based on a `local` strategy shared subscription. Which will prioritize local messages, but in case no local subscriber is found, it will pick a random from the group.

**Comment by philippdzm** [comment] 2022-04-13 10:44
I created a similar setup as the original post with `emqx-4.4.2-otp24.1.5-3-ubuntu20.04-amd64.deb`.
It's a cluster with two EMQX brokers on two different VMs in a shared network. They are configured as a static cluster and this works perfectly fine. Except the bridges: The bridges only seem to work per node. They produce double messages with a delay of ~15 seconds. If the bridge is configured on only one node the bridging depends on this node which eliminates the idea of the cluster.

I hope my information helps this issue. Any news on this yet?

**Comment by zmstone** [comment] 2022-04-14 05:38
The shared subscription enhancement has been merged and will be released in 4.3.14 and 4.4.3.
You can start using shared subscription for bridges.

@gsychev please help to provide an example config here after the document repo is updated, then we can have this issue closed.

@philippdzm the 15-second delay seems to be a different issue, but likely not a bug, could please create another issue if you consider it a bug, or a new discussion if that’s more like a question.

**Comment by philippdzm** [comment] 2022-04-14 08:48
@zmstone I'll wait for 4.4.3 then and give feedback again.

**Comment by matthewGEA** [comment] 2022-04-19 14:14
It is still not clear to me how this feature will be used.  I hope an example configuration will clarify.

For example. consider a local cluster of two nodes and a remote broker.  How can one configure each of the nodes in the local cluster to have the bridge enabled on both nodes and have each to subscribe to same topic without creating duplicate messages in the cluster?  In this configuration, the goal is to have a bridge that still functions moving data from the remote broker to the local broker, even after a node in the cluster goes down.

Similarly, how can one configure the bridge on each node of a local cluster to forward the same topic without creating duplicate messages in the remote broker?  For example, if the configuration of node1 is:
EMQX_BRIDGE__MQTT__AWS__FORWARDS=topic1/#
EMQX_BRIDGE__MQTT__AWS__FORWARD_MOUNTPOINT=
  (mountpoint is left blank to forward to the same topic on the remote broker)

node2 is:
EMQX_BRIDGE__MQTT__AWS__FORWARDS=topic1/#
EMQX_BRIDGE__MQTT__AWS__FORWARD_MOUNTPOINT=
  (mountpoint is left blank to forward to the same topic on the remote broker)

**Comment by gsychev** [comment] 2022-04-19 15:37
@matthewGEA, for bridging between EMQX instances you might want to use RPC bridge as described [here](https://www.emqx.io/docs/en/v4.3/advanced/bridge.html#rpc-bridging-example)

**Comment by matthewGEA** [comment] 2022-04-19 15:58
@gsychev Thanks for the suggestion.  Given that I want to also subscribe to data from the remote broker, that's why I avoided an RPC bridge, per this statement on the link you referenced:

`RPC bridging can only forward local messages to remote bridge nodes, and cannot synchronize messages from remote bridge nodes to local nodes`

**Comment by zmstone** [comment] 2022-04-23 12:22
> In my example, I'm assuming emqx is both the local nodes and the remote broker.
> 
> So, the remote broker will support shared subscriptions and each node in the local cluster will have the following configuration:
> 
> ```
> broker.local_bridge.shared_subscription_strategy = local
> 
> bridge.mqtt.my_bridge.forwards = $share/local_bridge/topic1/#
> bridge.mqtt.my_bridge.forward_mountpoint=
> bridge.mqtt.my_bridge.subscription.1.topic = $share/local_bridge/topic1/#
> bridge.mqtt.my_bridge.subscription.1.qos = 1
> ```
> 
> Without publishing to a shared topic, I also would need to use this option on the remote broker to prevent loops from occurring: `mqtt.ignore_loop_deliver = true zone.external.ignore_loop_deliver = true zone.internal.ignore_loop_deliver = true` is that still needed with the configuration above?

Hi.

Ignore_loop_deliver is essentially translated to the `no local` subscription option which only ignores messages when one client is subscribing to the topic published by itself.

When starting multiple bridges in a cluster, there are multiple publishing and subscribing clients, so there is going to be looped deliveries if the messages are not isolated by a namespace (mount point).

When both ends are emqx, it’s recommended to use publishing bridges towards each other using different namespaces.

If all topics have to be mirrored, maybe it’s time to consider a larger cluster instead.

**Comment by zmstone** [comment] 2022-04-23 12:24
Please note that the rpc bridge is deprecated.

@gsychev FYI.

**Comment by zmstone** [comment] 2022-04-23 12:29
Hi all.
I’m closing this issue as the described issue has been resolved by the local strategy.
For more questions, please free free to start a new discussion.

**Closed by zmstone** 2022-04-23 12:29 UTC
Labels: #triage/accepted
