### ISSUE TITLE
How to persist subscriptions after broker restart

### ISSUE THREAD

**Issue by 87sanchavan** [emqx/emqx#448] opened 2016-02-06 19:38 UTC
Hi 

I am running emqttd with default options. However when I restart broker , it looses all existing subscriptions. I was looking into emqttd.config file and made one change to see if that work ..

{pubsub, [
            %% Default should be scheduler numbers
            {pool_size, 8},

```
        %% Subscription: disc | ram | false
       %% {subscription, ram},
        {subscription, disc},
```

---

I commented ram and added disc option as I thought subscriptions will be stored on disc however it didnt work.

Thanks
Sanjay

**Comment by erylee** [comment] 2016-02-08 01:37
@87sanchavan, please load the 'subscription' module:

```
    %% Modules
    {modules, [
        ......
        %% Subscribe topics automatically when client connected
        {subscription, [
            %% Subscription from stored table
            stored,

            %% $u will be replaced with username
            {"$Q/username/$u", 1},

            %% $c will be replaced with clientid
            {"$Q/client/$c", 1}
        ]}
        ......
```

**Comment by 87sanchavan** [comment] 2016-02-08 13:26
Here is what I have done as you mentioned. However whenever I restart the broker and reconnects both clients and when Client A send message on a topic to which Client B is subscribed , client B wont get any message. Client B has to re subscribe to the same topic to get messages.

I have set clean session = false at clients side.

Can you please tell me if restarting broker will loose all subscriptions. If it doesn't , then why broker doesn't send messages automatically when clients get connected.


 %% Modules
    {modules, [
        %% Client presence management module.
        %% Publish messages when client connected or disconnected
        {presence, [{qos, 0}]},

        %% Subscribe topics automatically when client connected
         {subscription, [
        %%    %% Subscription from stored table
           stored,
        %%
        %%   %% $u will be replaced with username
            {"$Q/username/$u", 1},
        %%
        %%   %% $c will be replaced with clientid
           {"$Q/client/$c", 1}
         ]}

        %% Rewrite rules
        %% {rewrite, [{file, "etc/rewrite.config"}]}
    ]},

**Comment by erylee** [comment] 2016-02-08 14:18
```
  %% Subscription: disc | ram | false
       %% {subscription, ram},
        {subscription, disc},
```

The broker will persist the subscriptions to disc, but will not persist offline messages.

**Comment by 87sanchavan** [comment] 2016-02-08 21:06
Thank you a ton for replying quickly.

**Our problem : **

1.We have multiple clients( connected through mobile app) which will  be subscribing  to topics according to their requirement. This is one time activity and will be carried out when clients are signed up for first time.
2. Most of times clients are  disconnected to the broker however whenever they want to get information from server , they will open the app and automatically gets connected to broker and then we want broker to send them all available information to the clients. This means information will be published for these clients when they were offline.
3. I have tested above scenario with emqttd and it is working fine so I am good with emqttd for above problem.

But the main problem is when emqttd server gets restarted , no clients will get any message even though they are already subscribed. 

 One solution could be to make all clients to resubscribe to their topics when they connect , however this will not work since they wont receive the messages which were published when they were offline.

Can you please advise us on how we can solve  this problem.

Thanks
Sanjay

**Comment by janshahid** [comment] 2016-04-12 06:55
Hi,

The above given solution did not work for me.I am also looking solution for the same problem.
I am using the latest build and I udpated the emqttd.config file with the above given solution but the the issue still there.
Please help me in this issue

**Comment by numbertank** [comment] 2016-06-18 07:22
Hi,

The above given solution did not work for me.I am also looking solution for the same problem.
I am using the latest build and I udpated the emqttd.config file with the above given solution but the the issue still there.
Please help me in this issue

**Comment by andrewchambers** [comment] 2016-06-30 03:26
It seems to me most mqtt brokers do not handle dirty sessions properly, The server should really persist all subscriptions to dirty sessions and retain messages that have not been delivered even across restarts.

**Comment by apapacy** [comment] 2017-06-17 23:54
Same problem. Is you plane resolve it?

**Comment by jalbersdorfer** [comment] 2017-07-13 12:53
Same behaviour still in 2.2.0. After broker restart, all Subscriptions (and Messages) are gone.
emq-retainer Plugin is configured to disk. From the `# emqttd_ctl mnesia` I can confirm the messages (QoS 1) get logged to disk on receiving, but restarting the broker clears the subscriptions, even when requested with `no clear = true`

**Comment by pmasrani** [comment] 2017-12-14 15:05
@emqplus : We are facing the exact same problem mentioned by 87sanchavan in https://github.com/emqtt/emqttd/issues/448#issuecomment-181568355. Since you have marked this issue with the Enterprise label, is this functionality available in Enterprise version or is it targeted for a futuristic Enterprise version? Any plans to add this functionality to the open source version as well?

**Comment by chriz-kiran** [comment] 2018-01-30 08:08
Hi, 

I am very new to erlang and emqtt. Am trying to store subscriptions list to disc, I have followed the below procedure.

1. I have added mqtt.pubsub.subscription = disc in emq.conf file
2. I have added the below lines in /emqttd/priv/config file
{mapping,"mqtt.pubsub.subscription", "emqttd.subscription", [
  {default, ram},
  {datatype, {enum, [disc, ram, false]}}
]}.

where can i find 'subscription' module and I can you suggest me some tutorial or resources to gain better knowledge about emq.

Thank you

**Comment by a3aanwisse** [comment] 2018-03-19 13:44
We are also facing the same problem. Any time schedule on this one?

**Comment by baer-devl** [comment] 2018-03-19 14:44
One solution would be to write a mod which listens to _on_client_subscribe_ and _on_client_unsubscribe_ and every time those will be invoked you can store the actual subscriptions into a database. The only thing left to do is to load all subscriptions and create sessions for each client on _load_(auto load of mod on broker start) and subscribe to all stored topics again.
Of course, messages that were in the queue would be still lost, but i am sure you can find a way to handle this as well (maybe a _controlled shutdown_ of the broker or something).

**Comment by Oduig** [comment] 2018-03-27 14:27
+1

**Closed** 2018-12-25 04:50 UTC
Labels: Discussion, Enterprise, question
