### ISSUE TITLE
Delay between RECV and RECV PUBLISH

### ISSUE THREAD

**Issue by arizz96** [emqx/emqx#3094] opened 2019-12-10 10:28 UTC
#### Environment

- OS: docker - emqx/emqx:v4.0-rc.1
- Erlang/OTP: R22/10.5.2
- EMQ: 4.0-rc.1

#### Description

I recently updated EMQ version from v2.3.11 and I'm having problems with delayed message sending. I tried different versions (v3.1.2, v3.2.1) but each one seems to be affected.
I've a client that publish messages to various topic (usually large messages but limited to 1024kb) and periodically (every 5sec) it sends a ping message to another topic. This client was configured with 5sec of ACK timeout and it never raised timeout errors with v2.3.11 and I had to change it to 10sec for the problem that I'm describing.
As you can see in attached examples, sometimes there are some seconds of delay between RECV and RECV PUBLISH; it usually happens after ~30 large messages in the other topic.

You can find 3 different cases attached, with log from our client (backend) and log from client EMQ trace, here there is one of them for a quicklook (EMQ log only).

```
2019-12-09 21:01:26.358 [debug] <<"MjkwNzA2ODI5NDI2NzUyNTQzMzE3MTA3NjA5NjU1MDUwMjE">>@94.126.9.82:57201 [MQTT] RECV <<50,54,0,9,47,97,112,105,47,112,105,110,103,0,158,123,34,116,105,
              109,101,115,116,97,109,112,34,58,34,50,48,49,57,45,49,50,45,48,
              57,84,50,50,58,48,49,58,50,54,43,48,49,58,48,48,34,125>>
2019-12-09 21:01:31.359 [debug] <<"MjkwNzA2ODI5NDI2NzUyNTQzMzE3MTA3NjA5NjU1MDUwMjE">>@94.126.9.82:57201 [MQTT] RECV PUBLISH(Q1, R0, D0, Topic=/api/ping, PacketId=158, Payload=<<"{\"timestamp\":\"2019-12-09T22:01:26+01:00\"}">>)
2019-12-09 21:01:31.796 [info] <<"MjkwNzA2ODI5NDI2NzUyNTQzMzE3MTA3NjA5NjU1MDUwMjE">>@94.126.9.82:57201 PUBLISH to /api/ping: <<"{\"timestamp\":\"2019-12-09T22:01:26+01:00\"}">>
2019-12-09 21:01:31.796 [debug] <<"MjkwNzA2ODI5NDI2NzUyNTQzMzE3MTA3NjA5NjU1MDUwMjE">>@94.126.9.82:57201 [MQTT] SEND PUBACK(Q0, R0, D0, PacketId=158)
2019-12-09 21:01:31.797 [debug] <<"MjkwNzA2ODI5NDI2NzUyNTQzMzE3MTA3NjA5NjU1MDUwMjE">>@94.126.9.82:57201 [MQTT] RECV <<192,0>>
2019-12-09 21:01:31.798 [debug] <<"MjkwNzA2ODI5NDI2NzUyNTQzMzE3MTA3NjA5NjU1MDUwMjE">>@94.126.9.82:57201 [MQTT] SEND PINGRESP(Q0, R0, D0)
2019-12-09 21:01:31.798 [error] <<"MjkwNzA2ODI5NDI2NzUyNTQzMzE3MTA3NjA5NjU1MDUwMjE">>@94.126.9.82:57201 [Channel] Unexpected info: {#Ref<0.1853498059.2159280129.256275>,ok}
```

[case1_backend.txt](https://github.com/emqx/emqx/files/3944145/case1_backend.txt)
[case1_emq.txt](https://github.com/emqx/emqx/files/3944146/case1_emq.txt)
[case2_backend.txt](https://github.com/emqx/emqx/files/3944147/case2_backend.txt)
[case2_emq.txt](https://github.com/emqx/emqx/files/3944148/case2_emq.txt)
[case3_backend.txt](https://github.com/emqx/emqx/files/3944149/case3_backend.txt)
[case3_emq.txt](https://github.com/emqx/emqx/files/3944150/case3_emq.txt)

**Comment by arizz96** [comment] 2019-12-10 10:37
I reproduced it with QoS 0 too, you can find the logs in attached files below. At the end, after client raised `Unable to ping server: execution expired`, it closed the session and opened a new one.

[case4_backend.txt](https://github.com/emqx/emqx/files/3944360/case4_backend.txt)
[case4_emq.txt](https://github.com/emqx/emqx/files/3944361/case4_emq.txt)

**Comment by tigercl** [comment] 2019-12-12 09:20
Thanks for your feedback, we will deal with it as soon as possible.

**Comment by tigercl** [comment] 2019-12-12 09:30
By the way, do you use any emqx plugins?

**Comment by Leen15** [comment] 2019-12-12 09:32
Hi @tigercl , this is the list of loaded plugins via env var:
`emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_auth_username,emqx_auth_http`

**Comment by terry-xiaoyu** [comment] 2019-12-12 10:08
Did you get the logs using emqx_ctl trace ? That will only capture the log messages printed by the client you are tracing. Please have check the emqx.log.N, too see if there are some warning/error log messages here.

**Comment by tigercl** [comment] 2019-12-12 11:14
@Leen15 How many clients did the server connect to when this problem occurred? I didn't repeat the problem in my local environment.

**Comment by terry-xiaoyu** [comment] 2019-12-12 11:24
@arizz96  

1. I cannot see the `"large message"` you mentioned in the tracing file you post. 
2. Are you using shared subscription when consuming the 'large messages'?
3. could post your emqx.conf here?

**Comment by Leen15** [comment] 2019-12-12 14:06
Hi @tigercl and @terry-xiaoyu 
We did a new test for be sure that the issue is replicable.
The server is inside a K8S, it exposes 3 ports (mqtt, ws, wss).
It uses the image `emqx/emqx:v4.0-rc.1` with a list of envs ([envs.txt](https://github.com/emqx/emqx/files/3956040/envs.txt)).
Attached you can find also the full conf generated inside the container ([app.2019.12.12.12.58.20.conf.txt](https://github.com/emqx/emqx/files/3956041/app.2019.12.12.12.58.20.conf.txt)).

During the test there are only 2 clients connected, the backend that make the publish, and mqtt-explorer for check the result.

Here you can find the full log of the test:
[client.log](https://github.com/emqx/emqx/files/3956026/client.log) for logs of our backend client, with the payload we used.
[emq.log](https://github.com/emqx/emqx/files/3956027/emq.log) for logs of the emqx server container.
[trace.log](https://github.com/emqx/emqx/files/3956029/trace.log) for logs of the client trace with `emqx_ctl trace` command.

Thanks

**Comment by tigercl** [comment] 2019-12-13 03:48
@Leen15 Are you using shared subscription when consuming the 'large messages'?

**Comment by Leen15** [comment] 2019-12-13 05:56
@tigercl no we dont use them

**Comment by tigercl** [comment] 2019-12-13 07:57
@Leen15 Could you tell me the hardware configuration of your machine?

**Comment by Leen15** [comment] 2019-12-13 08:00
usually our nodes have a configuration like:
Xeon E3-1275 v5
64 GB ECC
2 NVMe 1TB

**Comment by tigercl** [comment] 2019-12-17 01:30
@Leen15 It seems to have something to do with log level. In our tests, this problem occurred only when the log level was debug and there were large messages in the k8s environment. For now, it is recommended that you use a higher level of logging, like info. We will solve this problem as soon as possible.

**Comment by arizz96** [comment] 2019-12-17 09:13
@tigercl it seems working using `info` as log level, we tested on 4.0-rc2 this morning. We're looking forward your fix, thank you 👍

**Comment by turtleDeng** [comment] 2019-12-25 10:14
Thank you for your participation, we will close this issue.

**Closed by turtleDeng** 2019-12-25 10:14 UTC

**Comment by satyamtpatel** [comment] 2020-10-14 01:52
We are facing similar issues when we are sending large message. Sometimes it is working and sometimes it is not receiving RECV message and then client is getting disconnected. Is above issue resolved? Can you please help us?
