### ISSUE TITLE
EMQX 5.0.4 Community Edition - Memory Leak (on Windows)

### ISSUE THREAD

**Issue by Martin09** [emqx/emqx#8729] opened 2022-08-15 10:08 UTC
#### Environment

- OS: Windows 10 Pro [19044.1826], 16GB RAM, i7-10700
- Erlang/OTP: Erts 12.2.1
- EMQ: v5.0.4 Community

#### Description

Left my server running for a week, and came back to all physical + virtual memory (~29 GB) being consumed by scvhost. After restarting the EMQX service the memory consumption dropped to ~6 GB. Not sure if related to bugs in ERTS when running on Windows (ex: spaces in path etc.). Some of these seem to be fixed in later versions [[ref](https://www.erlang.org/doc/apps/erts/notes.html)].

May also be related to another recent memory leak issue: [https://github.com/emqx/emqx/issues/8695](https://github.com/emqx/emqx/issues/8695) 

Attaching log file here in case it helps: [emqx_memory_leak.zip](https://github.com/emqx/emqx/files/9336523/emqx_memory_leak.zip)

**Comment by lafirest** [comment] 2022-08-16 02:41
@qzhuyan 
Hi, William, I think this issue may need your investigation and help

**Comment by qzhuyan** [comment] 2022-08-17 16:08
@Martin09 is it reproducible? 

When you leave the node there, is there any traffic running? what is the pattern of traffic? number of sub/pubs and rates?

**Comment by Martin09** [comment] 2022-08-17 19:15
Yeah looks to be. RAM is increasing gradually, now at ~11GB committed, started at ~6GB when I restarted the node two days ago. Nothing else is running on this machine, so I am fairly certain the increase is caused by EMQX. I will try to restart the service tomorrow and see if the RAM drops again like last time.

Here are some of the metrics that you asked for, hope it helps a bit!
![image](https://user-images.githubusercontent.com/1452036/185222904-52a4036d-b2fc-42b5-8215-c934ebcee00f.png)

**Comment by HJianBo** [comment] 2022-08-19 01:40
Can you use debugging tool to get the current erlang vm memory footprint? i.e:
```
## 1. Use `remote_console` to attach into emqx console 
./bin/emqx remote_console

## 2. Open the observer to get the vm&processs runngings stats
observer_cli:start().

## 3. Type `m` and <Enter>to sort process by used mem
m

## 4. Type `q` and <CTRL>+c to exit emqx console
```

**Comment by Martin09** [comment] 2022-08-19 05:50
Here you go:
![image](https://user-images.githubusercontent.com/1452036/185551535-0b89a566-bcfe-4c72-9b6b-5cae4aabdd0e.png)

**Comment by qzhuyan** [comment] 2022-08-19 18:32
is the screenshot taken when you have ~11GB committed?
Looks like this emqx node is ideling with less than 40 connections.

**Comment by Martin09** [comment] 2022-08-22 09:14
Yes, this was around when I had ~11 GB memory use. Here's another set of screenshots from this morning:
<img width="489" alt="Screenshot 2022-08-22 092706" src="https://user-images.githubusercontent.com/1452036/185882251-c1fce8c6-c0be-4fcb-8227-015e88e7fd1f.png">
<img width="869" alt="Screenshot 2022-08-22 094400" src="https://user-images.githubusercontent.com/1452036/185882263-8e9a4d55-d875-47f6-928b-338d3c65b615.png">
<img width="973" alt="Screenshot 2022-08-22 094026" src="https://user-images.githubusercontent.com/1452036/185882264-e8222de8-dd7b-4a97-9859-5d4d14ef0551.png">
Same behaviour in that when I restarted the EMQX process, memory use dropped to the normal ~5 GB baseline. Unfortunately I forgot to take a screenshot of this drop.

It might also be relevant to mention that I am running EMQX in a service created using [NSSM](https://nssm.cc/) (v2.24). Path is "..bin\emqx.cmd" and startup directory is "...bin" with argument "start". I recently made sure to remove all spaces in the path, but this did not make a difference.

**Comment by qzhuyan** [comment] 2022-08-23 10:24
do you have screenshot of processes in windows task manager?  Maybe it is other processes are leaking the memory.
from the observer cli screenshot, it doesn't look like a leakage in EMQX.

**Comment by Martin09** [comment] 2022-08-23 19:09
Task manager is the first thing I checked, all looks fine. My user account is using ~300 MB of memory. What is consuming all the extra RAM is Erlang processes:
![image](https://user-images.githubusercontent.com/1452036/186240940-7e1b3ee0-cd12-4de1-96a7-3a7fda60e295.png)
Currently sitting at around 9 GB committed, I estimate ~4 GB of that is Erlang processes. I don't have any other software installed running Erlang, so I can't think of anything other than EMQX that could be causing this. Also, when I restart the EMQX server memory use drops instantly. These two things together are a very strong indication to me.

Also worth noting that I have been running an older version of EMQX 4.x.x (can't remember exactly which one) for more than a year without any issues. I only saw this problem appear after upgrading to v5. If there isn't any obvious cause/solution I will try downgrading to see if this helps.

**Comment by qzhuyan** [comment] 2022-08-24 13:15
I see. 

Could you do the following?


## 1. Use `remote_console` to attach into emqx console 
./bin/emqx remote_console

## 2. Get memory allocator snapshot and send us the OUTPUT_FILE.
```

recon_alloc:snapshot(), recon_alloc:snapshot_save("PATH/TO/OUTPUT_FILE").

```

## 3. Type `q` and <CTRL>+c to exit emqx console

**Comment by Martin09** [comment] 2022-08-24 14:31
Yep sure, here you go: [20220824_memory_snapshot.txt](https://github.com/emqx/emqx/files/9416943/20220824_memory_snapshot.txt)
 
 Interestingly it only seems to show ~21 MB total memory use which is also more or less what the observer reported. This at least makes sense but it somehow doesn't see all the other Erlang processes that I see in the Resource Monitor.

**Comment by qzhuyan** [comment] 2022-08-24 19:41
How many erlang processes you have in the os? How many cpu cores you have?

**Comment by Martin09** [comment] 2022-08-26 09:53
I count something like ~75 erlang processes in the process monitor, though some are grayed out (not quite sure what this means). This is running on an i7-10700 so 16 logical cores. Here's a list of the suspicious processes:
[Processes_20220826.txt](https://github.com/emqx/emqx/files/9432089/Processes_20220826.txt)

For reference, I had 20.1 GB/16 GB committed memory at the time.

I also see a lot of "cmd.exe" processes in there too, is that expected? I wonder if it somehow has to do with how I am calling EMQX as a service with NSSM. I could try running it manually from the command line and see if I still have the memory leak. What do you think?

Here's what restarting the EMQX service manually looks like:
![RestartingEMQXService](https://user-images.githubusercontent.com/1452036/186878328-6f04853a-c2e8-4347-ac29-96e97863d7f7.png)

**Comment by qzhuyan** [comment] 2022-08-29 10:05
@Martin09 there are too many `escripts` processes. 

I agree worth to try run emqx without `NSSM` (I don't have any exp. about NSSM)

**Comment by Martin09** [comment] 2022-08-29 11:42
Yes, indeed it was a problem with how I was running the EMQX server, sorry for the false alarm. In case it helps someone else: I didn't realize that the "emqx start" command launched the process in the background and gave back control of the command prompt. I think NSSM was launching the server and, when it got back control, it assumed the server had crashed so it re-launched it... eventually building up all those erlang processes. 

Now I simply ran a single instance manually from the terminal and memory use remains at the baseline level even after 2 days. Thanks a lot @qzhuyan for your support in helping debug this, we can close this one as everything is now running as expected and the issue was not with EMQX.

**Closed** 2022-08-29 11:43 UTC
Labels: windows, #triage/wait
