### ISSUE TITLE
EMQx Docker does not start Dashboard when using tmpfs for the Data directory and omitting EMQX_LOADED_PLUGINS environmental variable

### ISSUE THREAD

**Issue by matthewGEA** [emqx/emqx#7455] opened 2022-03-29 17:24 UTC
### Subject of the issue
EMQx Docker does not start Dashboard when using tmpfs for the Data directory and omitting EMQX_LOADED_PLUGINS environmental variable

### Your environment
emqx/emqx:4.4.1 docker image

### Steps to reproduce
Load EMQx using the following docker compose file within Portainer Stacks:

```
version: '3'
services:
  mqtt:
    container_name: emqx
    image: emqx/emqx:4.4.1
    network_mode: "host"
    restart: always
#    environment:
#      - EMQX_LOADED_PLUGINS=emqx_recon,emqx_management,emqx_dashboard,emqx_bridge_mqtt
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_etc:/opt/emqx/etc
      - emqx_lib:/opt/emqx/lib
      - emqx_log:/opt/emqx/log
volumes:
  emqx_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  emqx_etc:
  emqx_lib:
  emqx_log:
```

LOG OUTPUT:
*normal volume for data directory
*omit EMQX_LOADED_PLUGINS
NOTE: Dashboard loads
```
today at 1:22:22 PMlistener.ssl.external.acceptors = "32"
today at 1:22:22 PMlistener.ssl.external.max_connections = "102400"
today at 1:22:22 PMlistener.tcp.external.acceptors = "64"
today at 1:22:22 PMlistener.tcp.external.max_connections = "1024000"
today at 1:22:22 PMlistener.ws.external.acceptors = "16"
today at 1:22:22 PMlistener.ws.external.max_connections = "102400"
today at 1:22:22 PMlistener.wss.external.acceptors = "16"
today at 1:22:22 PMlistener.wss.external.max_connections = "102400"
today at 1:22:22 PMlog.to = "console"
today at 1:22:22 PMnode.max_ets_tables = "2097152"
today at 1:22:22 PMnode.max_ports = "1048576"
today at 1:22:22 PMnode.name = "ap201tst-001pc2@127.0.1.1"
today at 1:22:22 PMnode.process_limit = "2097152"
today at 1:22:22 PMrpc.port_discovery = "manual"
today at 1:22:27 PMStarting emqx on node ap201tst-001pc2@127.0.1.1
today at 1:22:27 PM2022-03-29T17:22:27.518751+00:00 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70.0%
today at 1:22:27 PMStart mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
today at 1:22:27 PMStart mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
today at 1:22:27 PMStart mqtt:ws:external listener on 0.0.0.0:8083 successfully.
today at 1:22:27 PMStart mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
today at 1:22:27 PMStart mqtt:wss:external listener on 0.0.0.0:8084 successfully.
today at 1:22:27 PMStart http:management listener on 8081 successfully.
today at 1:22:27 PMStart http:dashboard listener on 18083 successfully.
today at 1:22:27 PMEMQ X Broker 4.4.1 is running now!
```

LOG OUTPUT:
*TMPFS volume for data directory
*omit EMQX_LOADED_PLUGINS
NOTE: Dashboard does not load
```
today at 1:16:50 PMlistener.ssl.external.acceptors = "32"
today at 1:16:50 PMlistener.ssl.external.max_connections = "102400"
today at 1:16:50 PMlistener.tcp.external.acceptors = "64"
today at 1:16:50 PMlistener.tcp.external.max_connections = "1024000"
today at 1:16:50 PMlistener.ws.external.acceptors = "16"
today at 1:16:50 PMlistener.ws.external.max_connections = "102400"
today at 1:16:50 PMlistener.wss.external.acceptors = "16"
today at 1:16:50 PMlistener.wss.external.max_connections = "102400"
today at 1:16:50 PMlog.to = "console"
today at 1:16:50 PMnode.max_ets_tables = "2097152"
today at 1:16:50 PMnode.max_ports = "1048576"
today at 1:16:50 PMnode.name = "ap201tst-001pc2@127.0.1.1"
today at 1:16:50 PMnode.process_limit = "2097152"
today at 1:16:50 PMrpc.port_discovery = "manual"
today at 1:16:55 PMStarting emqx on node ap201tst-001pc2@127.0.1.1
today at 1:16:55 PM2022-03-29T17:16:55.102200+00:00 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70.0%
today at 1:16:55 PMStart mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
today at 1:16:55 PMStart mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
today at 1:16:55 PMStart mqtt:ws:external listener on 0.0.0.0:8083 successfully.
today at 1:16:55 PMStart mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
today at 1:16:55 PMStart mqtt:wss:external listener on 0.0.0.0:8084 successfully.
today at 1:16:55 PM2022-03-29T17:16:55.124175+00:00 [alert] [Modules] Failed to read: "data/loaded_modules", error: enoent
today at 1:16:55 PMEMQ X Broker 4.4.1 is running now!
```

LOG OUTPUT
*TMPFS volume for data directory
*include EMQX_LOADED_PLUGINS
NOTE: Dashboard Loads
```
today at 1:12:29 PMEMQX_LOADED_PLUGINS=emqx_recon emqx_management emqx_dashboard emqx_bridge_mqtt
today at 1:12:29 PMgrep: /opt/emqx/data/loaded_plugins: No such file or directory
today at 1:12:29 PMgrep: /opt/emqx/data/loaded_plugins: No such file or directory
today at 1:12:29 PMsed: /opt/emqx/data/loaded_plugins: No such file or directory
today at 1:12:39 PMlistener.ssl.external.acceptors = "32"
today at 1:12:39 PMlistener.ssl.external.max_connections = "102400"
today at 1:12:39 PMlistener.tcp.external.acceptors = "64"
today at 1:12:39 PMlistener.tcp.external.max_connections = "1024000"
today at 1:12:39 PMlistener.ws.external.acceptors = "16"
today at 1:12:39 PMlistener.ws.external.max_connections = "102400"
today at 1:12:39 PMlistener.wss.external.acceptors = "16"
today at 1:12:39 PMlistener.wss.external.max_connections = "102400"
today at 1:12:39 PMlog.to = "console"
today at 1:12:39 PMnode.max_ets_tables = "2097152"
today at 1:12:39 PMnode.max_ports = "1048576"
today at 1:12:39 PMnode.name = "ap201tst-001pc2@127.0.1.1"
today at 1:12:39 PMnode.process_limit = "2097152"
today at 1:12:39 PMrpc.port_discovery = "manual"
today at 1:12:43 PMStarting emqx on node ap201tst-001pc2@127.0.1.1
today at 1:12:43 PM2022-03-29T17:12:43.960945+00:00 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70.0%
today at 1:12:43 PMStart mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
today at 1:12:43 PMStart mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
today at 1:12:43 PMStart mqtt:ws:external listener on 0.0.0.0:8083 successfully.
today at 1:12:43 PMStart mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
today at 1:12:43 PMStart mqtt:wss:external listener on 0.0.0.0:8084 successfully.
today at 1:12:44 PMStart http:management listener on 8081 successfully.
today at 1:12:44 PMStart http:dashboard listener on 18083 successfully.
today at 1:12:44 PM2022-03-29T17:12:44.232784+00:00 [alert] [Modules] Failed to read: "data/loaded_modules", error: enoent
today at 1:12:44 PMEMQ X Broker 4.4.1 is running now!
```

**Comment by thalesmg** [comment] 2022-03-29 19:52
Hi @matthewGEA !

Thanks for the detailed info.

The issue you are observing arises because EMQX expects some files in the data directory, one of which is the `loaded_modules` file.  This file comes along with EMQX, as you can inspect inside the container (without mounting the `emqx_data` volume):

```sh
bash-5.1$ ls data/
configs         loaded_modules  loaded_plugins  mnesia          patches         scripts
bash-5.1$ cat data/loaded_modules 
{emqx_mod_acl_internal, true}.
{emqx_mod_presence, true}.
```

Since mounting the volume essentially hides those preexisting files, I believe there are 2 simple alternative solutions:

1. Add those files with the desired contents (or the default ones) in your volume before starting EMQX.
2. Set the `modules.loaded_file` config in `etc/emqx.conf` to a path containing the file with the expected contents.

Let me know if that solves the issue for you.  :slightly_smiling_face:

**Comment by matthewGEA** [comment] 2022-03-29 20:23
@thalesmg When using a regular volume (non-tmpfs), the internal data volume IS copied to the specified volume on boot.  See below:
```
volumes:
  emqx_data:
#    driver_opts:
#      type: tmpfs
#      device: tmpfs
  emqx_etc:
  emqx_lib:
  emqx_log:
```
![image](https://user-images.githubusercontent.com/46966648/160699783-6c78e961-0ae5-4740-b2e2-44d13d983a1f.png)

When using a tmpfs volume, however, some files are missing:

```
volumes:
  emqx_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  emqx_etc:
  emqx_lib:
  emqx_log:
```
![image](https://user-images.githubusercontent.com/46966648/160700344-1bcdd9bf-5f55-43da-a57f-ad5db3d63801.png)

My main goal is to not persist changes made to the data directory across restarts of the docker container; I want it to start fresh every time.

**Comment by thalesmg** [comment] 2022-03-30 17:22
I have reproduced locally your scenario.

The files are not copied when you specify the volumes.  The files/directories you are seeing are being created during EMQX startup.

You can verify that by changing the entrypoint to something else, e.g.:

```yaml
    entrypoint:
      - "tail"
      - "-f"
      - "/dev/null"
```

Then, if you enter the container from another shell (e.g. `docker exec -it emqx bash`), you can verify that the `data` dir is empty both with and without using tmpfs.

```
bash-5.1$ ls -la data
total 8
drwxrwxrwt    2 root     root            40 Mar 30 17:03 .
drwxrwxr-x    1 emqx     emqx          4096 Feb 22 19:01 ..
```

The problem of not loading the dashboard plugin is that the `loaded_plugins` file that is generated in the absence of a preexisting file is empty.

> My main goal is to not persist changes made to the data directory across restarts of the docker container; I want it to start fresh every time.

If you don't want to persist any data between restarts, you can simply _not_ create the a volume pointing to `/opt/emqx/data`.  This way, the preexisting files will be present, and the default value of `data/loaded_plugins` is to enable the dashboard. 

If for some reason you still want to mount `/opt/emqx/data` as a volume, the solutions for the dashboard problem are either:

- Add those files with the desired contents (or the default ones) in your volume before starting EMQX.
- Set both the `EMQX_LOADED_PLUGINS` and `EMQX_LOADED_MODULES` env vars to match those contents.

E.g:

```yaml
    environment:
     - EMQX_LOADED_MODULES=emqx_mod_acl_internal,emqx_mod_presence
     - EMQX_LOADED_PLUGINS=emqx_recon,emqx_management,emqx_dashboard,emqx_bridge_mqtt
```

**Comment by matthewGEA** [comment] 2022-03-31 04:06
I am still missing something fundamental, though.  Hopefully you can help me.

Let's forgo docker-compose at the moment.

If I run the following, where no volumes are specified:
```
sudo docker run -d \
--name=emqx4.4.1-standalone \
--network=host \
--restart=always \
emqx/emqx:4.4.1
```

a non-persistent volume will be created for the required directories (/opt/emqx/data is one of them).  Every time I stop and start this container (for example, when power-cycling the PC), the same non-persistent volume will be used by this container, therefore data will be persisted across restarts of the container.

 In this configuration, how would one start fresh with a new volume every time? This is where the idea of a tmpfs volume seems appealing, it is destroyed with the stopping of the container.

So the question that remains open for me (which could be due to my lack of understanding regarding Docker): why is the result of the /opt/emqx/data directory different when specifying a normal volume vs a tmpfs volume. It's my understanding that the docker container shouldn't treat the two differently.

For example, given two created volumes:
```
sudo docker volume create --driver local \
data_persistent
```
and
```
sudo docker volume create --driver local \
--opt type=tmpfs \
--opt device=tmpfs \
data_tmpfs
```

When running:
```
sudo docker run -d \
--name=emqx4.4.1-standalone \
--network=host \
--restart=always \
-v data_persistent:/opt/emqx/data \
emqx/emqx:4.4.1
```
then connecting via /bin/bash, to list the files from /opt/emqx/data, the following is shown:
![image](https://user-images.githubusercontent.com/46966648/160973622-6e4e5ae5-834c-4f69-b38a-74d6338b18b3.png)

whereas stopping the previous container and running:
```
sudo docker run -d \
--name=emqx4.4.1-tmpfs \
--network=host \
--restart=always \
-v data_tmpfs:/opt/emqx/data \
emqx/emqx:4.4.1
```
then connecting via /bin/bash, to list the files from /opt/emqx/data, the following is shown:
![image](https://user-images.githubusercontent.com/46966648/160973826-3bfee995-60ac-43b8-9607-7c6c51c10f34.png)

As an aside, the following command:
```
sudo docker run -d \
--name=emqx4.4.1-tmpfs \
--network=host \
--restart=always \
--tmpfs /opt/emqx/data \
emqx/emqx:4.4.1
```
produces the following errors in the log:
`2022-03-31T04:04:44.428107+00:00 [error] Error creating /opt/emqx/data/configs: permission denied`

**Comment by zmstone** [comment] 2022-03-31 04:18
Inside the container, it’s the `emqx` user not `root` runs the `emqx` program.

**Comment by zmstone** [comment] 2022-03-31 04:30
hmm, according to https://docs.docker.com/storage/tmpfs/ tmpfs is by default “world writable”

will try to experiment it later

**Comment by matthewGEA** [comment] 2022-03-31 04:49
So just discovered that the default permissions for a tmpfs MOUNT (not volume) is for root within the container, which is why "permission denied" was seen above.  Inspecting the emqx container for the emqx user shows the uid = 1000, so changing the command to this:

```
sudo docker run -d \
--name=emqx4.4.1-tmpfs \
--network=host \
--restart=always \
--tmpfs /opt/emqx/data:uid=1000 \
emqx/emqx:4.4.1
```

allows the container to load as if a tmpfs VOLUME was created, but still get this error:
`2022-03-31T04:43:42.317031+00:00 [alert] [Modules] Failed to read: "data/loaded_modules", error: enoent`

So that is the issue that should be investigated: what process cannot write to a tmpfs MOUNT (with emqx permissions) or a tmpfs VOLUME

**Comment by zmstone** [comment] 2022-03-31 05:28
the problem is there is no code handling a missing `loaded_modules` file.
count it as a bug, we'll try to fix it in the next release

before the fix, here is a workaround:

```
docker run -d --tmpfs /opt/emqx/data:uid=1000 -v $(pwd)/loaded_modules:/opt/emqx/data/loaded_modules emqx/emqx:4.4.1
```

**Comment by zmstone** [comment] 2022-03-31 05:39
A side note (only applicable for 4.x):
If you want to use retainer, please make sure  to set `retainer.storage_type = ram` when using `tmpfs`
Otherwise it will cost twice or even more RAM than having the files on disk.

The `disc` option actually means a copy on disk,
i.e. all data has a copy in RAM, but also copied on disk (including non-compacted WAL).

**Comment by matthewGEA** [comment] 2022-03-31 12:45
> the problem is there is no code handling a missing `loaded_modules` file. count it as a bug, we'll try to fix it in the next release
> 
> before the fix, here is a workaround:
> 
> ```
> docker run -d --tmpfs /opt/emqx/data:uid=1000 -v $(pwd)/loaded_modules:/opt/emqx/data/loaded_modules emqx/emqx:4.4.1
> ```

Why can the emqx docker load the "loaded_modules" file when using a normal volume, but cannot when using a tmpfs volume?

**Comment by matthewGEA** [comment] 2022-03-31 13:34
Don't know if this will have any affect:
https://github.com/moby/moby/issues/39466

**Comment by matthewGEA** [comment] 2022-03-31 15:01
To summarize the issue, why does `Configuration 3` and `Configuration 5` fail?

## Configuration 1: No volume specified
✔️ `loaded_modules` is present
### Command
```
sudo docker run -d \
--name=emqx4.4.1-standalone \
--network=host \
--restart=always \
emqx/emqx:4.4.1
```
### Permissions
```
bash-5.1$ ls -ld /opt/emqx/data/
drwxrwxr-x    6 emqx     emqx          4096 Mar 31 14:38 /opt/emqx/data/
```

## Configuration 2: Normal volume specified
✔️ `loaded_modules` is present
### Command
```
sudo docker volume create --driver local \
data_persistent

sudo docker run -d \
--name=emqx4.4.1-standalone \
--network=host \
--restart=always \
-v data_persistent:/opt/emqx/data \
emqx/emqx:4.4.1
```
### Permissions
```
bash-5.1$ ls -ld /opt/emqx/data/
drwxrwxr-x    6 emqx     emqx          4096 Mar 31 14:46 /opt/emqx/data/
```

## Configuration 3: Tmpfs volume specified
❌ `loaded_modules` is missing
NOTE: Configuration should work given "others" has write permissions to the directory
### Command
```
sudo docker volume create --driver local \
--opt type=tmpfs \
--opt device=tmpfs \
data_tmpfs

sudo docker run -d \
--name=emqx4.4.1-tmpfs \
--network=host \
--restart=always \
-v data_tmpfs:/opt/emqx/data \
emqx/emqx:4.4.1
```
### Permissions
```
bash-5.1$ ls -ld /opt/emqx/data/
drwxrwxrwt    4 root     root           100 Mar 31 14:48 /opt/emqx/data/
```

## Configuration 4:  Tmpfs mount specified
❌ ALL files are missing and container is a reboot-loop
NOTE: Configuration is expected to fail, given "others" does not have write permissions to the directory

### Command
```
sudo docker run -d \
--name=emqx4.4.1-tmpfs \
--network=host \
--restart=always \
--tmpfs /opt/emqx/data \
emqx/emqx:4.4.1
```
### Permissions
```
bash-5.1$ ls -ld /opt/emqx/data/
drwxrwxr-x    2 root     root            40 Mar 31 14:50 /opt/emqx/data/
```

## Configuration 5: Tmpfs mount specified with UID as emqx (id 1000)
❌  `loaded_modules` is missing
NOTE: Configuration should work, given the owner of the directory is emqx and the owner has write permissions
### Command
```
sudo docker run -d \
--name=emqx4.4.1-tmpfs \
--network=host \
--restart=always \
--tmpfs /opt/emqx/data:uid=1000 \
emqx/emqx:4.4.1
```
results in these permissions:
```
bash-5.1$ ls -ld /opt/emqx/data/
drwxrwxr-x    3 emqx     root            60 Mar 31 14:51 /opt/emqx/data/
```

**Comment by zmstone** [comment] 2022-03-31 22:14
Hi @matthewGEA

Your Configuration 2 worked because the `loaded_modules` file is there before EMQX starts.

this is how I tested it.
(I did not start `emqx`, but started `bash` to inspect the dir.)
```
$ docker volume create --driver local data_persistent
data_persistent
$ docker run --rm -it --name=emqx4.4.1-standalone  --network=host -v data_persistent:/opt/emqx/data emqx/emqx:4.4.1 bash
bash-5.1$ ls -l /opt/emqx/data/
total 24
drwxrwxr-x    2 emqx     emqx          4096 Feb 22 19:01 configs
-rw-rw-r--    1 emqx     emqx            58 Feb 22 18:56 loaded_modules
-rw-rw-r--    1 emqx     emqx           192 Feb 22 18:56 loaded_plugins
drwxrwxr-x    2 emqx     emqx          4096 Feb 22 19:01 mnesia
drwxrwxr-x    2 emqx     emqx          4096 Feb 22 19:01 patches
drwxrwxr-x    2 emqx     emqx          4096 Feb 22 19:01 scripts
```

**Comment by zmstone** [comment] 2022-03-31 22:17
to sum up:
* `loaded_modules` is pre-created in `/opt/emqx/data` (which is a docker volume)
* docker entry point does not create the file if it's not there (will be fixed)
* emqx fail to initialise some of the features if the file doesn't exist (will be fixed)

workaround before the fix:
Make a copy of the file from the docker image, and mount it to start the container.

**Closed** 2022-04-06 21:28 UTC
Labels: #triage/accepted
