### ISSUE TITLE
Failed to start Emqx : syntax error

### ISSUE THREAD

**Issue by chrysa95** [emqx/emqx#2173] opened 2019-01-23 08:31 UTC
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

Hello, 

I am trying to run emqx broker  but could not succeed,

- I install emqx broker like this : unzip emqx-ubuntu16.04-v3.0.0.zip

- I tried running it with cd emqx && ./bin/emqx console or start 

But i have the following mistake 

/home/user/emqx/erts-10.2/bin/run_erl: 1: /home/user/emqx/erts-10.2/bin/run_erl: Syntax error: end of file unexpected (expecting ")")

How can i solve it ??

Thanks !

**Comment by Gilbert-Wong** [comment] 2019-01-23 09:32
We have tried with `emqx-ubuntu16.04-v3.0.0.zip` on ubuntu 16.04, we can not reproduce this situation, could you please tell me more details?

**Comment by Gilbert-Wong** [comment] 2019-01-23 09:34
Maybe you could try to upgrade your `bash` to solve this problem.

**Comment by chrysa95** [comment] 2019-01-23 12:06
@Gilbert-Wong 
I did what you suggested but did not work, the same mistake remains.

- Ubuntu version 16.04.5

- Ι have download the zip file emqx-ubuntu16.04-v3.0.0 from this source: htps://www.emqx.io/downloads/emq/broker

Then,  in command line i install broker like this : unzip emqx-ubuntu16.04-v3.0.0.zip
Also , i have intsall the erlang

**Comment by Gilbert-Wong** [comment] 2019-01-30 03:32
I tried to unzip emqx on ubuntu 16.04, there is no such problem you referred in this issue. I suppose some thing wrong in your environment. Sorry, I can not help you solve this problem.

**Comment by zhanghongtong** [comment] 2019-03-20 01:47
This issue has not been updated for a long time. I am going to close this issue. Please feel free to re-open if you still have the same trouble.

**Closed by zhanghongtong** 2019-03-20 01:47 UTC
Labels: Support

**Comment by zyftank** [comment] 2022-05-06 02:03
This seems to be a problem caused by Ubuntu enabling bash,You can disable bash to solve this problem.
But,The downloaded version is a 64 bit version. It still can't run on a 32-bit machine.
