### ISSUE TITLE
Time error receiving message for tools  websocket 

### ISSUE THREAD

**Issue by servucn** [emqx/emqx#2226] opened 2019-02-15 05:22 UTC
#### Environment

* OS : window 2008 x64
* Erlang/OTP:
* EMQ:  3.0

#### Description

接收消息的时间显示错误，凌晨0点的时间显示为12点的，没有使用24小时，也没有加AM、PM.

**Comment by Gilbert-Wong** [comment] 2019-02-15 05:24
Please open issue with English and provide more details.

**Comment by linjunjj** [comment] 2019-02-15 06:00
@servucn   sorry, I can't reproduce your issues, please provide more details.

**Comment by servucn** [comment] 2019-02-15 08:39
> details
![image](https://user-images.githubusercontent.com/6037332/52844733-3b0ebb80-3140-11e9-8ecd-549dd4f834d4.png)

**Comment by wivwiv** [comment] 2019-02-16 01:58
@servucn We will use 24-hour formatting in next version.

**Comment by Gilbert-Wong** [comment] 2019-03-05 03:10
Has been fixed in 3.1-beta.1.

**Closed by Gilbert-Wong** 2019-03-05 03:10 UTC
Labels: Support
