### ISSUE TITLE
 Resource web_hook is down 

### ISSUE THREAD

**Issue by chanlk** [emqx/emqx#4904] opened 2021-06-01 03:52 UTC
### Describe the bug

There are "Resource web_hook(resource:247932) is down " in the alram tab of the emqx dashboard . 
All msg can't transfer to the web server which i config on the web_hook. 

## What I try
I add a web_hook and it's config same with the old,  and i relpace the rule's action handler to the new web_hook;
After that , it seems solved, but i don't konw why and it happend many times, it bothers me;

## Screenshots
![image](https://user-images.githubusercontent.com/31768716/120264678-dc4dbb80-c2d0-11eb-80b9-b1d9171573d9.png)

## System information
OS: [Ubuntu 16.04 on AWS EC2]

**Comment by terry-xiaoyu** [comment] 2021-06-02 02:06
This is probably caused by the connection down between the http server and emqx. Please check the emqx logs for error messages.

**Comment by chanlk** [comment] 2021-06-02 05:53
> This is probably caused by the connection down between the http server and emqx. Please check the emqx logs for error messages.

Thanks xiaoyu. 
Yes, I check the emqx log,  there are a lot of HTTP 503 error, I think it's my http server's error. But i have other clients connect to the web server,  there are fine . 
I don't know why after i repalce a new web_hook , the error will gone, the new web_hook exactly the same as  old one;

**Comment by qzhuyan** [comment] 2021-07-06 09:28
@chanlk I think the issue is resolved, thus I close this ticket. 
feel free to reopen it when you need more help.

**Closed by qzhuyan** 2021-07-06 09:28 UTC
Labels: Support
