### ISSUE TITLE
eqmx 日志报错

### ISSUE THREAD

**Issue by liangqianwuer** [emqx/emqx#6757] opened 2022-01-14 09:07 UTC
运行emqx 日志报错了
 
2022-01-11 14:28:53.568 [error] 203.168.4.213:23654 [MQTT] 
Parse failed for function_clause
[{emqx_frame,parse_packet,[{mqtt_packet_header,15,true,3,true},<<48,0,4,77,81,84,84,4,194,0,60,0,12,50,48,50>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,166}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,144}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,522}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,515}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,293}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<255,16,48,0,4,77,81,84,84,4,194,0,60,0,12,50,48,50,50,48,49,48,51,48,49,48,51,0,8,118,97,49,55,50,55,115,105,0,12,121,116,122,106,54,118,117,57,98,54,51,49>>

### Your environment

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

Otherwise please provide below info:
- EMQ X version (4.0):
- If cluster (e.g. 3 X 4Core16GB):
- Hardware configuration (e.g. `lscpu`):
- OS (winds):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### LOG File
以下是截取的一部分日志信息
2022-01-11 14:28:53.568 [error] 203.168.4.213:23654 [MQTT] 
Parse failed for function_clause
[{emqx_frame,parse_packet,[{mqtt_packet_header,15,true,3,true},<<48,0,4,77,81,84,84,4,194,0,60,0,12,50,48,50>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,166}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,144}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,522}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,515}]},{emqx_connection,process_msg,3,[{file,"emqx_connection.erl"},{line,293}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<255,16,48,0,4,77,81,84,84,4,194,0,60,0,12,50,48,50,50,48,49,48,51,48,49,48,51,0,8,118,97,49,55,50,55,115,105,0,12,121,116,122,106,54,118,117,57,98,54,51,49>>

**Comment by HJianBo** [comment] 2022-01-17 03:05
This seems to be a failure to parse the MQTT protocol. Can you reproduce it consistently? Or provide a tcpdump of the network packet capture file.

**Comment by insane-dreamer** [comment] 2022-06-29 16:31
We're getting the same error intermittently: 

A couple of examples: 
```
[MQTT] Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet_header,0,false,0,false},<<254,83,77,66,64,0,0,0,0,0,0,0,0,...>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,204}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<0,110,254,83,77,66,64,0,0,0,0,0,0,0,0,0,0,0,0,...>>
```

```
[MQTT] , Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet_header,4,false,3,true},<<"T / HTTP/1.1\r\nHost: www\r\nAccept: */*\r\nUser-Agent: Mo"...>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,204}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<"GET / HTTP/1.1\r\nHost: www\r\nAccept: */*\r\nUser-Agent: Mozilla/5.0 (Windows NT "...>>
```

**Comment by zmstone** [comment] 2024-02-12 09:32
In older version EMQX, sending HTTP request to MQTT listener causes `function_clause` exceptions.
There had been quite many improvements released in EMQX v5.
This is want logged in `v5.5.0`

```
2024-02-12T10:30:02.980367+01:00 [info] mfa: emqx_connection:parse_incoming/2(817), peername: 127.0.0.1:52452, reason: #{hint => malformed_packet,header_type => 4}, at_state: <<"clean">>, input_bytes: <<"GET / HTTP/1.1\r\nHost: localhost:1883\r\nUser-Agent: curl/7.68.0\r\nAccept: */*\r\n\r\n">>, parsed_packets: []
2024-02-12T10:30:02.980998+01:00 [info] msg: terminate, mfa: emqx_connection:terminate/2(676), peername: 127.0.0.1:52452, reason: {shutdown,#{shutdown_count => frame_error,hint => malformed_packet,header_type => 4}}
2024-02-12T10:30:02.981244+01:00 [notice] supervisor: {esockd_connection_sup,<0.2290.0>}, errorContext: frame_error, reason: #{hint => malformed_packet,header_type => 4}, offender: [{pid,<0.2290.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,listener => {tcp,default},zone => default,limiter => undefined}]}}]
```

and you can observe the total number of such errors in listener stats.

```
$ emqx ctl listeners
tcp:default
  listen_on       : 0.0.0.0:1883
  acceptors       : 16
  proxy_protocol  : false
  running         : true
  current_conn    : 0
  max_conns       : infinity
  shutdown_count  : [{frame_error,3}]
```

**Closed by zmstone** 2024-02-12 09:32 UTC
Labels: Support, #triage/accepted
