### ISSUE TITLE
AuthN/AuthZ - Built-in database not enabling from config file

### ISSUE THREAD

**Issue by rgaufman** [emqx/emqx#9913] opened 2023-02-04 10:32 UTC
### What happened?

I added this to my emqx.conf file:

```
authentication {enable:true,backend:"built_in_database",mechanism="password_based",user_id_type="username"}
```

Followed by:

```
/etc/init.d/emqx restart
```

### What did you expect to happen?

I expected the web dashboard to show this authentication method is enabled, but instead none are enabled:
![Screenshot 2023-02-04 at 10 29 41](https://user-images.githubusercontent.com/33842342/216762045-351b38fb-fc91-41de-9b11-5072aa6f74b0.jpg)

### How can we reproduce it (as minimally and precisely as possible)?

1) dpkg -i emqx-5.0.16-ubuntu18.04-amd64.deb
2) add this to emqx.cof and restart:
```
authentication {enable:true,backend:"built_in_database",mechanism="password_based",user_id_type="username"}
```
3) Open web dashboard and observe these are authentication mechanisms enabled

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.16
datetime  : 2023-02-04T10:30:36.959434762+00:00
uptime    : 16 minutes, 5 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux staging2.xanview.org 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

[node_dump_20230204_103202.tar.gz](https://github.com/emqx/emqx/files/10608405/node_dump_20230204_103202.tar.gz)

**Comment by tigercl** [comment] 2023-02-06 03:05
Hi, @rgaufman. The log does not reveal the cause of the error related to this, can you use `emqx console` to start, and then provide the output content of the console?

**Comment by zmstone** [comment] 2023-02-06 13:31
I noticed this in the log:

> 2023-02-04T09:50:36.084550+00:00 [alert] msg: failed_to_start_plugin, mfa: emqx_plugins:ensure_started/1, line: 266, reason: #{error => "bad_info_file",path => "plugins/emqx_auth_mnesia/release.json",return => {enoent,"/usr/lib/emqx/plugins/emqx_auth_mnesia/release.json"}}

It seems that you were trying to enable `emqx_auth_mnesia` as a EMQX v5 plugin?
There might be some misunderstanding, mnesia auth is now a default feature in v5, no longer needed for a plugin-enable and per-plugin configuration.

To enable mnesia auth in v5, all you need is to add the config (as you posted above):
`authentication {enable:true,backend:"built_in_database",mechanism="password_based",user_id_type="username"}`

**Comment by zmstone** [comment] 2023-02-06 13:34
To eanble AuthZ in v5, all you need is to ensure ` {type = "built_in_database"},` is added to the `sources`.
Below is a full example with both `mnesia` and `file` sources enabled.
```
authorization {
  cache {enable = true}
  deny_action = "ignore"
  no_match = "allow"
  sources = [
    {type = "built_in_database"},
    {
      enable = true
      path = "etc/acl.conf"
      type = "file"
    }
  ]
}
```

**Comment by zmstone** [comment] 2023-02-06 13:43
I have reported another issue to follow up the node boot failure:
https://github.com/emqx/emqx/issues/9920

**Comment by zmstone** [comment] 2023-02-07 07:39
Hi @rgaufman 
This does not seem to be a bug to me.
The logging error has been fixed in https://github.com/emqx/emqx/pull/9923
Closing this issue.
Please feel free to reopen or create a new one if there is something else.

**Closed by zmstone** 2023-02-07 07:39 UTC
Labels: BUG
