### ISSUE TITLE
SSL/TLS issues

### ISSUE THREAD

**Issue by gdillen** [emqx/emqx#2116] opened 2018-12-28 21:00 UTC
#### Environment

- OS: Ubuntu 18.04
- Erlang/OTP: 
- EMQ: 3.0

#### Description
Trying to use SSL/TLS for https (dashboard), MQTTS, WSS using LetsEncrypt. My LetsEncrypt certificates work perfect with Mosquitto.

I Adapted the following files:
emqx.conf

MQTT SSL/TLS
listener.ssl.external.keyfile = /etc/letsencrypt/live/abc-xyz.abc.be/privkey.pem
listener.ssl.external.certfile = /etc/letsencrypt/live/abc-xyz.abc.be/cert.pem
listener.ssl.external.cacertfile = /etc/letsencrypt/live/abc-xyz.abc.be/fullchain.pem

WSS
Same as for MQTT SSL/TLS

emqx_dashboard.conf

HTTPS dashboard
dashboard.listener.https.keyfile = /etc/letsencrypt/live/abc-xyz.abc.be/privkey.pem
dashboard.listener.https.certfile = /etc/letsencrypt/live/abc-xyz.abc.be/fullchain.pem

*A description of the issue*
Cannot connect using TLS to above mentioned services.

Can anyone help me. Many thanks.

**Comment by gdillen** [comment] 2019-01-09 18:50
Hi,

Is there any progress regarding a solution for this problem?

Thanks.

**Comment by gdillen** [comment] 2019-01-14 15:11
Hi,

My initial issue dates from almost 20days ago. Until now I didn't get any feedback on the progress, ...
We can't wait with our further development. So please give some feedback/solution or we have to look for another solution.
Thanks.

**Comment by zhengyupan** [comment] 2019-01-25 04:41
Hi @gdillen , please refer to this document for TLS/SSL.: https://medium.com/@emqtt/using-lets-encrypt-certificates-in-emq-b11e0e57efa6
This document was written for emqx 2.x, but still works for current version.

**Comment by gdillen** [comment] 2019-01-25 09:04
Hi @zhengyupan Thanks, I followed the instructions ypu mentioned but it doesn't work. When I add this dashboard.listener.https.access.1 = allow all line the broker doesn't startup! When I don't add this line I only can login with http (port: 18083).
My certificates are OK.

**Comment by guydillen** [comment] 2019-02-06 09:23
Any progress?

Thanks.

**Comment by guydillen** [comment] 2019-02-24 15:07
Followed exact the same instructions as in the document, but don’t succeed to access the dashboard with https port 18084!

**Comment by Gilbert-Wong** [comment] 2019-02-24 15:08
Sorry for late response, could you please provide your emqx log file ?

**Comment by guydillen** [comment] 2019-02-24 15:18
I suppose te file under /var/log/emqx?

[emqx.log.1.txt](https://github.com/emqx/emqx/files/2898031/emqx.log.1.txt)
[erlang.log.1.txt](https://github.com/emqx/emqx/files/2898033/erlang.log.1.txt)
[run_erl.log](https://github.com/emqx/emqx/files/2898034/run_erl.log)

**Comment by guydillen** [comment] 2019-02-25 08:14
did you had the chance looking at the logfiles?

**Comment by guydillen** [comment] 2019-02-26 14:28
my initial post dates from december 28th 2018, can someone please have a look at it. Thanks.

**Comment by guydillen** [comment] 2019-03-01 07:16
This problem completely blocks our work since december 2018! If you don't have the intention to provide, on short-term, a solution we will switch to a competitive product (VerneMQ).

**Comment by phanimahesh** [comment] 2019-03-03 19:32
The log files do not contain anything relevant to this issue.

_What diagnostic steps have you undertaken?_

Here are a few checks you can run:
1. Can you confirm that the broker is listening on port 18084? `ss -tln` should show it. emqx logs you provided indicate that the listener started.
2. Can you connect to the port using netcat or other similar tool? `nc -v <ip> 18084` should show `Connection to <ip> 443 port [tcp/https] succeeded!` or something similar.
3. Can openssl understand the certificate chain and verify it? Run `openssl s_client -connect <ip>:18084 -servername prod-gwy0.abcxyz.abc` and look at the last few lines. It should show `Verify return code: 0 (ok)`.

If all of these are successful and the issue still exists, then it might be a bug in emqx. If one of these steps fail, the mode of failure indicates what is wrong.

Alternately, you can always plop a haproxy in front of emqx. Offloading SSL termination is always a good idea, and in fact the recommended mode of using SSL with emqx. I do not understand how this can _completely_ block your work.

As such, the issue does not contain sufficient information to reproduce your situation, and without experiencing it, it can not be debugged. What is the minimum configuration change from defaults with which this issue can be reproduced?

**Comment by guydillen** [comment] 2019-03-03 19:57
The results for the checks you mentioned. I suppose all tests are successful.

1. port 18084 listening:

$ ss -tln
LISTEN 0 128 0.0.0.0:18084 0.0.0.0:* 

Broker is listening on port 18084

2. netcat connect to port

$ nc -v xxx.xxx.xxx.xxx 18084
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif en0
	src 10.0.0.43 port 57960
	dst xxx.xxx.xxx.xxx port 18084
	rank info not available
	TCP aux info available

Connection to xxx.xxx.xxx.xxx port 18084 [tcp/*] succeeded!

3. openssl

$ openssl s_client -connect xxx.xxx.xxx.xxx:18084
CONNECTED(00000003)
4584957548:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.240.1/libressl-2.6/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1551642299
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---

Modifications I made to the default out-of-the-box config:

- allow_anonymous = true
- enable auth_username (and added a user)
- in emq_dashboard_conf

## Value: IP:Port | Port
##
## Examples: 18084, 127.0.0.1:18084, ::1:18084
dashboard.listener.https = 18084

## The acceptor pool for external Dashboard HTTPS listener.
##
## Value: Number
dashboard.listener.https.acceptors = 2

## Maximum number of concurrent Dashboard HTTPS connections.
##
## Value: Number
dashboard.listener.https.max_clients = 512

## Path to the file containing the user's private PEM-encoded key.
##
## Value: File
dashboard.listener.https.keyfile = /etc/letsencrypt/live/abc.xyz/privkey.pem

## Path to a file containing the user certificate.
##
## Value: File
dashboard.listener.https.certfile = /etc/letsencrypt/live/abc.xyz/fullchain.pem

**Comment by phanimahesh** [comment] 2019-03-04 09:08
> `4584957548:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.240.1/libressl-2.6/ssl/ssl_pkt.c:585:`

> `SSL handshake has read 0 bytes and written 0 bytes`

The certificate is not being sent. For some wierd implementation reason openssl returns code 0, but the ssl handshake did not happen.

Can you confirm that the file location is correct, and verify its permissions, so that it can be read by emqx? Set log level to debug and start the broker, and see if there is any useful information there.

**Comment by guydillen** [comment] 2019-03-04 09:36
File location is correct and permissions are rwx for ugo (didn't change these)
See log with loglevel debug.
Thanks.

[log.txt](https://github.com/emqx/emqx/files/2925697/log.txt)

**Comment by phanimahesh** [comment] 2019-03-04 10:02
That log file stops midway, before even the startup is complete. Please repeat it and include the full log. The log file may be rotated, check all files in the log directory to see if any .1, .2 etc files are created.

**Comment by guydillen** [comment] 2019-03-04 10:13
[emqx.log.1.txt](https://github.com/emqx/emqx/files/2925867/emqx.log.1.txt)
[erlang.log.1.txt](https://github.com/emqx/emqx/files/2925868/erlang.log.1.txt)
[run_erl.log.txt](https://github.com/emqx/emqx/files/2925869/run_erl.log.txt)

**Comment by phanimahesh** [comment] 2019-03-04 13:28
These are truncated too. Is there a `emqx.log.2.txt`?

**Comment by guydillen** [comment] 2019-03-04 15:44
Nope that's all there is:

drwxr-xr-x  2 emqx emqx     4096 Mar  4 10:34 .
drwxrwxr-x 14 root syslog   4096 Mar  4 11:19 ..
-rw-rw-r--  1 emqx emqx   330220 Mar  4 11:09 emqx.log.1
-rw-rw-r--  1 emqx emqx       18 Mar  4 11:09 emqx.log.idx
-rw-rw-r--  1 emqx emqx       13 Mar  4 11:09 emqx.log.siz
-rw-rw-r--  1 emqx emqx    54551 Mar  4 16:39 erlang.log.1
-rw-rw-r--  1 emqx emqx      258 Mar  4 11:09 run_erl.log

**Comment by phanimahesh** [comment] 2019-03-05 03:47
That is unusual. Can you try clearing the logs folder and restarting emqx?

**Comment by guydillen** [comment] 2019-03-05 09:21
-> stopped emqx
-> deleted all logfiles in /var/log/emqx
-> restarted emqx

[emqx.log.1.txt](https://github.com/emqx/emqx/files/2930136/emqx.log.1.txt)
[erlang.log.1.txt](https://github.com/emqx/emqx/files/2930137/erlang.log.1.txt)
[run_erl.log.txt](https://github.com/emqx/emqx/files/2930138/run_erl.log.txt)

drwxrwxr-x 2 vmadmin vmadmin   4096 Mar  5 10:14 .
drwxr-xr-x 5 vmadmin vmadmin   4096 Mar  4 18:58 ..
-rw-r--r-- 1 vmadmin vmadmin 163986 Mar  5 10:14 emqx.log.1
-rw-r--r-- 1 vmadmin vmadmin     18 Mar  5 10:14 emqx.log.idx
-rw-r--r-- 1 vmadmin vmadmin     13 Mar  5 10:14 emqx.log.siz
-rw-r--r-- 1 vmadmin vmadmin   1825 Mar  5 10:14 erlang.log.1
-rw-r--r-- 1 vmadmin vmadmin    258 Mar  5 10:14 run_erl.log

**Comment by phanimahesh** [comment] 2019-03-05 11:34
Uncomment `dashboard.listener.https.ciphers` and try again. Also post the output of `openssl s_client -connect <ip> 18084`.

**Comment by guydillen** [comment] 2019-03-05 12:38
```
CONNECTED(00000003)
write:errno=54
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1551789461
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by phanimahesh** [comment] 2019-03-05 14:27
I am out of ideas. The one obscure issue I found with cipher mismatch is solved by uncommenting the ciphers.

Please check your certificates again. If they're absolutely fine (let' say if the same certs work with nginx/apache/haproxy/whatever), then I have no idea what might be wrong.

I have tried replicating the issue in multiple environments, but I can access the dashboard over https. At this point I think the issue can't be resolved without an experienced sysadm looking at your setup.

**Comment by guydillen** [comment] 2019-03-05 16:13
I understand, anyway many thanks for the effort helping trying to solve the problem.

**Closed** 2019-03-06 03:18 UTC
Labels: Support
