### ISSUE TITLE
BIND address for dashboard and management plugin

### ISSUE THREAD

**Issue by sooslaca** [emqx/emqx#5229] opened 2021-07-14 09:17 UTC
**What would you like to be added/modified**:
Can we configure bind address like for listeners in dashboard and management plugin configuration?
Documentation does not define that and I can't see it from the code
```
## HTTP Listener
dashboard.listener.http = 18083
dashboard.listener.http.acceptors = 2
dashboard.listener.http.max_clients = 512
```

Can value for listener like `127.0.0.1:18083` be accepted? I tested right now it's not accepted:
```
emqx            | 2021-07-14T09:00:22.375115+00:00 [error] Minirest(Handler): Start http:management listener on {"127.0.0.1",8081} unsuccessfully: {{shutdown,{failed_to_start_child,ranch_acceptors_sup,badarg}},{child,undefined,{ranch_listener_sup,'http:management'},{ranch_listener_sup,start_link,['http:management',ranch_tcp,#{connection_type => supervisor,max_connections => 512,num_acceptors => 2,socket_opts => [{port,{"127.0.0.1",8081}},{nodelay,true},{send_timeout_close,true},{send_timeout,15000},{backlog,...}]},cowboy_clear,#{connection_type => supervisor,env => #{dispatch => [{'_',[],...}]}}]},permanent,infinity,supervisor,[ranch_listener_sup]}}
...
emqx            | 2021-07-14T09:00:22.404811+00:00 [alert] [Plugins] Plugin emqx_dashboard load failed with {function_clause,[{emqx_plugins,apply_configs,[{error,transform_datatypes,{errorlist,[{error,{transform_type,"dashboard.listener.http"}},{error,{conversion,{[...],...}}}]}}],[{file,"emqx_plugins.erl"},{line,277}]},{emqx_plugins,load_plugin,2,[{file,"emqx_plugins.erl"},{line,300}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_app,start,2,[{file,"emqx_app.erl"},{line,45}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}

```

**Why is this needed**:
Secure mgmt/dashboard with nginx or other reverse proxy

**Comment by k32** [comment] 2021-07-14 12:19
Hello,

This is a duplicate of https://github.com/emqx/emqx/issues/2928

**Closed by k32** 2021-07-14 12:19 UTC
Labels: Feature
