### ISSUE TITLE
EMQX Centos8 Problem

### ISSUE THREAD

**Issue by rootqa** [emqx/emqx#7994] opened 2022-05-19 11:27 UTC
### What happened?

we have installed latest version of EMQX and getting an error in default libs on Centos8 (OS Level)

### What did you expect to happen?

EMQX software should be run and start.

### How can we reproduce it (as minimally and precisely as possible)?

1. install CentOS 8
2. Download latest EMQX
3. Unzip and run (./emqx start)

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

sysdescr  : EMQ X Broker
version   : 4.4.3
uptime    : 15 seconds
datetime  : 2022-05-19 15:26:34

</details>

### Log files

<details>
There seem to be missing dynamic libs from the OS.
</details>

**Comment by ieQu1** [comment] 2022-05-23 07:47
Duplicate of #7995

**Closed by ieQu1** 2022-05-23 07:47 UTC
Labels: BUG
