### ISSUE TITLE
Node 'emqx1@127.0.0.1' not responding to pings.

### ISSUE THREAD

**Issue by lanling233** [emqx/emqx#4356] opened 2021-03-17 09:21 UTC
能正常启动与访问，但运行 emqx stop 命令报错
求原因和解决方法

**Comment by tigercl** [comment] 2021-03-18 01:16
@lanling233 If possible, you'd better provide some emqx logs so that we can better analyze the problem.

**Comment by zmstone** [comment] 2021-03-18 14:11
@lanling233 你跑的哪个版本，在什么操作系统上？

**Comment by k32** [comment] 2021-09-25 08:52
Closing due to lack of updates. Please feel free to submit a new issue if you manage to reproduce it on the current version of the broker.

**Closed by k32** 2021-09-25 08:52 UTC
Labels: Support
