### ISSUE TITLE
beam.smp consuming 100% CPU

### ISSUE THREAD

**Issue by rahulwinzo** [emqx/emqx#2081] opened 2018-12-19 14:26 UTC
#### Environment

- OS: Ubuntu 18.04.1 LTS
- Erlang/OTP: Erlang/OTP 21
- EMQ: 3.0

#### Description

I've been facing issue with EMQ wherein I'm seeing very high CPU usage on our machines. We're running a cluster of two machines each with 4 cores and 16 GB memory with EMQX 3.0 installed. There isn't much that I can infer from the logs.
Attached are the images.

<img width="589" alt="screenshot 2018-12-19 at 7 47 25 pm" src="https://user-images.githubusercontent.com/37581350/50225859-aac62b80-03c7-11e9-95ea-e4151fb00435.png">

<img width="1232" alt="screenshot 2018-12-19 at 7 48 21 pm" src="https://user-images.githubusercontent.com/37581350/50226022-245e1980-03c8-11e9-94ca-0c4f43c9aaab.png">

**Comment by rahulwinzo** [comment] 2018-12-21 05:56
Could you please help with the issue? We've been getting these CPU spikes a lot lately.

**Comment by terry-xiaoyu** [comment] 2018-12-21 08:30
@rahulwinzo Hi, could you describe your pub/sub scenarios? i.e. How many publishers, subscribers do you have, what are the topics the subscribers and the publishers are using, and also the publish speed.

**Comment by rahulwinzo** [comment] 2018-12-21 08:42
Hi @terry-xiaoyu, we're using the cluster for our chat application. The application has around 10k online users at any point of time. So, I guess that's the number of publishers and subscribers that we're looking at. Since it's like any other chat application where one user can chat with another user, there are around 70k topics on our cluster right now (as visible on EMQ dashboard). For the publish speed part, I'm not sure what exactly are you looking for? Publish speed per topic or overall the publish speed.

**Comment by terry-xiaoyu** [comment] 2018-12-21 08:52
@rahulwinzo 

1. Do you have any topics that has many subscribers? e.g. is there a topic 'a/#' that all of your clients subscribe to it, and then a publisher send messages to all the clients via this topic.
Or do you have a backend service subscribes to a single topic that all of the clients publish to?

2. Do you keep the log level as `error`?

3. Are your clients connected to EMQ via TLS or via a proxy?

**Comment by rahulwinzo** [comment] 2018-12-21 09:07
@terry-xiaoyu 
1. Yes, we do have a common topic to which all clients subscribe. It's our common group chat topic.
2. Yes, we keep the log level as error which I guess is default log level.
3. Clients are connected to EMQ via TCP. We don't have TLS in place yet.

**Comment by terry-xiaoyu** [comment] 2018-12-21 10:06
@rahulwinzo Then it might be the common topic, I think the CPU is so high because messages from everyone are sent to all others frequently. If one send a message to the common topic, the broker will forward it to 10K clients, which causes the high CPU usage.

**Comment by rahulwinzo** [comment] 2018-12-21 10:55
Hi @terry-xiaoyu, the group chat feature wasn't present in the app until a couple of weeks ago. And we've been seeing CPU spikes from even before.

**Comment by terry-xiaoyu** [comment] 2018-12-22 14:17
Not sure if is the problem of cluster mode. You could attach into the Erlang shell by emqx_ctl attach, and then look for the top busy processes by recon:proc_count(message_queue_len, 20).  

Don't Ctrl-C in Erlang shell! Use Ctrl-D instead.

**Comment by terry-xiaoyu** [comment] 2018-12-22 14:19
Not sure if is the problem of cluster mode. You could attach into the Erlang shell by emqx_ctl attach, and then look for the top busy processes by recon:proc_count(message_queue_len, 20).  

Don't Ctrl-C in Erlang shell! Use Ctrl-D instead.

**Comment by rahulwinzo** [comment] 2018-12-22 15:15
emqx_ctl doesn't have any 'attach' usage. I'm not able to attach into the Erlang shell.

**Comment by terry-xiaoyu** [comment] 2018-12-24 02:57
Sorry, it is `emqx attach`

**Comment by Gilbert-Wong** [comment] 2019-02-11 04:33
@rahulwinzo , Have your problem been resolved ?

**Comment by rahulwinzo** [comment] 2019-03-28 11:58
The problem is still not resolved. We're still seeing high CPU usage on our server. Now we've switched to a single 16 core machine which is also facing similar 100% CPU utilization scenario.

**Comment by rahulwinzo** [comment] 2019-03-29 08:28
Can you give us some pointers as to where to look for the cause behind this?

**Comment by rahulwinzo** [comment] 2019-03-30 07:03
@Gilbert-Wong Can you suggest how to pinpoint the real reason behind this issue so that we can fine tune on our end?

**Comment by arihantdaga** [comment] 2019-04-30 08:46
Same issue here... 
After few days, suddenly it starts consuming High CPU. And it doesnt go normal unless i reboot the machine...

**Comment by terry-xiaoyu** [comment] 2019-04-30 08:53
> Not sure if is the problem of cluster mode. You could attach into the Erlang shell by emqx attach, and then look for the top busy processes by recon:proc_count(message_queue_len, 20).
> 
> Don't Ctrl-C in Erlang shell! Use Ctrl-D instead.

@arihantdaga  Have you tried this?

**Comment by arihantdaga** [comment] 2019-04-30 19:56
@terry-xiaoyu  On 2.3.7 i tried `emqttd attach` but it gave me this error - 
No running Erlang on pipe `//opt/emqttd/data/myusername_erl_pipes/emq1@10.139.152.154/erlang.pipe.4: No such device or address`
But i checked in the directory there exists files - erlang.pipe4.r and erlang.pipe.4.w
I used `./bin/emqttd start` to start the broker.

**Comment by arihantdaga** [comment] 2019-05-01 13:28
@terry-xiaoyu I also tried on a new emqx cluster i set up yesterday with emqx 3.1.0 with 2 nodes and in one of the node i started seeing high cpu usage at 66%, while in other one its close to 5-10%. 
I did try with `emqx attach ` I could attach into process but the response of recon:proc_count(message_queue_len, 20) is empty. 
```
(emqk@10.139.164.138)1> recon:proc_count(message_queue_len, 20)
(emqk@10.139.164.138)1> recon:proc_count()                     
(emqk@10.139.164.138)1> 
```

**Comment by arihantdaga** [comment] 2019-05-01 18:10
In my case it is definitely due to mongodb. I reproduced it. Even if one member of the mongodb replica set is down, CPU will spike in the emqx machine. 
Steps to reproduce. 
1. Have a mongodb replica server with 3 replicas. 
2. Turn off on of the secondary replica, which doesnt affect overall cluster, there is still one primary and one secondary. 
3. check with `top` on the machine with emqx installed. You'll see beam.smp on top consuming high CPU.

**Comment by cube3power** [comment] 2019-05-13 12:45
cpu too heavy.
![image](https://user-images.githubusercontent.com/5474892/57622325-eaccbb80-75bf-11e9-9650-76d6c5f73941.png)

**Comment by alex-bermishev** [comment] 2019-07-04 08:59
i experience same problems when running emqx/emqx:v3.1.2 docker image in cluster
**beam.smp** & **erl_child_setup** consume lot's of cpu periodically

**Comment by GerogeLeon** [comment] 2019-07-04 09:44
the same to me

![image](https://user-images.githubusercontent.com/25131163/60656806-bf10d800-9e82-11e9-9e65-df201628cded.png)

**Comment by GerogeLeon** [comment] 2019-07-04 11:36
i tried re-install emq, and solved it. 
i suppose, the inconsistent node status caused it, but why these node can successfully join a cluster

**Comment by moluzhui** [comment] 2019-10-17 00:48
i experience same problems when running emqx/emqx:v3.2.3 docker image in single server, The results of `docker stats` show that the container's CPU usage can vary from a few hundredths of a percent to more than a hundred percent when I didn't send any messages.

**Comment by elsobrino** [comment] 2020-09-29 06:32
https://stressgrid.com/blog/beam_cpu_usage/

**Comment by Scott--R** [comment] 2020-12-29 14:35
Did anyone find a solution to this? We are experiencing the same issue. beam.smp is consuming 100% of the CPU and stays there.

**Comment by uloga** [comment] 2021-01-07 14:39
I started learning Elixir today, by creating a simple hello world project and running it on Mac 16GB i5 the cpu went to 100% and got stuck there. Such a bad start IMHO. Any other language out there is not behaving like this. It froze my whole OS. :( 

Good luck with the project.

**Comment by zmstone** [comment] 2021-08-09 21:48
we don't have the right tools in version 3 for troubleshooting, some primitive debug utilities can be used, but it requires attaching to the Erlang console to evaluate Erlang expressions etc. which might work but will take a lot of time if communicating over github issue discussion.

In 4.3, we have added a tool called `observer_cli` to the release which can easily help to inspect the busy processes in a `htop` alike view. The interactive menu is also quite easy for users to explore even without any Erlang experience.

execute `emqx remote_console` to attach to the Erlang console
then evaluate `observer_cli:start().` to start the realtime, interactive monitoring view like this example:

![image](https://user-images.githubusercontent.com/164324/128778558-5f13ee75-613c-44f0-a83d-18dde8abe6ce.png)

the busy processes will be listed at the top.
remember the busy processes, then press `q` to quit back to Erlang console.
then evaluate `process_info(<0.1497.0>).` to inspect the process, and share the output with us.

**Closed by zmstone** 2021-08-09 21:48 UTC
Labels: Benchmark

**Comment by zmstone** [comment] 2021-08-09 21:50
This issue is closed due to lack of info for old versions.
For future reference, if this happens in version 4.3 or later, please refer to the above reply and create a new issue to report.
