### ISSUE TITLE
Active Connection Not Reaching 1 Million

### ISSUE THREAD

**Issue by shrestha-clipapp** [emqx/emqx#1550] opened 2018-04-02 09:21 UTC
#### Environment

- OS: Ubuntu
- Erlang/OTP: R20/9.0
- EMQ: 2.3.5

#### Description

I am using EMQTT as a notification cum chat for my clients. I am right now at the testing stage for notification section, where I am trying to get a load test on as many connection as possible and if notification reach all clients or not. But my emqtt broker starts failing at 350k connections. There is drop in topic count first after which there is a big drop in clients connected to the broker. The maximum clients I have reached 380k connections.

I am using M5.4x Large AWS system which is 16 vCPUs, 64 GB RAM instance.

My client is a java based one and I am using standard paho implementation to create the client where I am using 1 system to create 2000 unique clients per system.

*A description of the issue*

As I am using my clients for both chat and notification I am subscribing each client with a unique topic
(which is same as username) to allow one user to chat with another user and one common topic which will allow us to send a notification to all users. So in total the subscriptions in general is two times the clients(so maximum 700k) subscriptions. 

At first when I increase the number from 100k to 200k clients and so on there is no issue and notifications are also being passed easily to each client. By the time it reaches close to 300k then there is a huge drop in number of topics followed by clients from 400k. 

There is a recorded error that I see in the error.log file which refers to emqttd_access_control:lookup_mods/1 line 107 
which seems to be causing this issue though I am not sure what the error is there. 

I am attaching the error.log as well as emq.conf (as text file) 
[error.log](https://github.com/emqtt/emqttd/files/1867709/error.log)
file here for reference. 

Please have a look at these and let me know where I am going wrong as I need to understand the same to finish my testing and use emqtt application in our live system. 
Any help and/or advise is deeply appreciated. 

[emq.txt](https://github.com/emqtt/emqttd/files/1867708/emq.txt)

**Comment by terry-xiaoyu** [comment] 2018-04-03 16:47
@shrestha-clipapp 
Have you tuned your system using http://emqtt.io/docs/v2/tune.html# ?
I don't know what happened without more info, could you provide a full "etc/log" dir? 

If you can reproduce that issue, try attach to the erlang shell using:
```
./bin/emqttd attach
```
and then run `etop` to see if there is a bottleneck:
```
(emq@127.0.0.1)1> spawn(fun() -> etop:start([{interval,10}, {sort, msg_q}, {lines,20}]) end). 
```
use `etop:stop().` if you want to quit.

you could also check the status of ETS tables when the some issue occur:
```
(emq@127.0.0.1)3> ets:i().
 id              name              type  size   mem      owner
 ----------------------------------------------------------------------------
 ac_tab          ac_tab            set   256    19027    application_controller
 clique_commands clique_commands   set   0      306      clique_manager
 clique_config   clique_config     set   33     2271     clique_manager
...

(emq@127.0.0.1)6> ets:info(mqtt_access_control).
[{read_concurrency,true},
 {write_concurrency,false},
 {compressed,false},
 {memory,385},
 {owner,<0.1306.0>},
 {heir,none},
 {name,mqtt_access_control},
 {size,2},
 {node,'emq@127.0.0.1'},
 {named_table,true},
 {type,set},
 {keypos,1},
 {protection,protected}]
```

**Ctrl - D** to quit the erlang shell.

**Comment by shrestha-clipapp** [comment] 2018-04-04 07:09
Hi Terry 

Thank you for your reply. The case I was running today was with 180k normal notif connections(i.e. no chat was going on internally) and 75k chat clients(chatting with each other at 1 chat message/250 secs average each). So in total I had approx 250k connections. Things were running smoothly until I introduced another client which would be publishing 1 message to all the clients (checking if notifs were to be sent across at any given time). It was then that half my clients were brought down from the broker. Now neither the process limit or the file descriptor limit had been reached (according to the web dash board and the CPU load was no where close to maximum). I was also tracking the etop function that you had told but at that moment it crashed as well saying 

**"Timeout when waiting for process info from node 'emq@127.0.0.1'; exiting
Output server crashed: timeout"**

Now I am not sure about the database because that seemed responsive with high memory consumption in some tables like mqtt_client and mqtt_subscriber which seemed to be expected with these number of clients. 

Also the client records error as "Connection lost" or "Connection Timeout" as an exception.

I am attaching all the zip files for all the logs here. Please have a look and let me know if you need anything else in order to resolve this issue. Again thanks for the reply.
[logs.zip](https://github.com/emqtt/emqttd/files/1874639/logs.zip)


Regards
Shrestha

**Comment by shrestha-clipapp** [comment] 2018-04-06 06:40
Hi Terry, Huangdan

I am attaching today's and yesterday's log where we faced a similar issue again. This time I had activated the emqttd attach functions as you requested and they are also stored in the logs. Let me know if you need anything else. From the logs what I can understand that the error seems to be at line no 107 of "src/emqttd_access_control.erl". Please let me know for what reason this could happen or any other file or resource you need to reproduce this problem at your end. 

Any ideas/tips would be helpful to increase the number of connections.

[logs05042018.zip](https://github.com/emqtt/emqttd/files/1882952/logs05042018.zip)

Thanks in advance
Shrestha

**Comment by terry-xiaoyu** [comment] 2018-04-07 10:43
@shrestha-clipapp 
From your last post:
> Things were running smoothly until I introduced another client which would be publishing 1 message to all the clients (checking if notifs were to be sent across at any given time). 

 If the connections are only dropped when you publishing the `notification` to all clients (about 250k), then I think this might be a issue in emqttd router:

Currently if a PUBLISH message (with a topic in mqtt header) comes, emqttd will fetch all of the subscribers of that topic in one search, which may need huge mount of memory if the number of subscribers is substantial. Erlang VM will try to do garbage collection in the current erlang process (the sender `emqttd_client`), but that would not be enough, so it increase the memory of that erlang process by allocating more and more memory to it. The GC and memory re-allocation are both time-consuming, which may lead to some other issues such as crashes some erlang process.

I'm not sure your problem is caused by this issue, as I cannot find the Crash Logs of 'emqttd_access_control' process, but it is probably that the Erlang VM was too busy to print any logs at that time.

I'll ask @huangdan to help reproduce this issue to verify my assumption.

**Comment by terry-xiaoyu** [comment] 2018-04-07 11:14
@shrestha-clipapp Do you have some other logs in log dir? And do you have some `crash.dump` files ?  The `crash.dump` may be also in your log dir.

**Comment by shrestha-clipapp** [comment] 2018-04-07 11:35
@terry-xiaoyu : I don't have any crash.dump files in the emqttd/log directory but only crash.log.x files which I have attached in the previous zip files. Is there any other place where it is possible to find this file? If you need any other copy of those files please let me know.

Regards
Shrestha

**Comment by terry-xiaoyu** [comment] 2018-04-07 11:44
That's OK, it means your Erlang VM have not crashed. Are you using some customized plugins or pure EMQ for your testing? What authentication method are you using?

**Comment by shrestha-clipapp** [comment] 2018-04-07 11:57
Yeah I also believe that the VM has not crashed because we still have connections but they are reduced to half or less in number .
I am using pure emqtt without any plugins and no authentication method for now as we are just load testing.

Regards
Shrestha

**Comment by huangdan** [comment] 2018-04-08 03:56
@shrestha-clipapp 
Could you describe your more detail for test scenario? for example: 
the number of Pub/Sub Connection, QoS, the number of messages, the frequency of the message, the size of Payload, the number of Topic.

./bin/emqttd_ctl listeners to check the shutdown_count, for example:
```
listener on mqtt:tcp:1883
  acceptors       : 8
  max_clients     : 1024
  current_clients : 0
  shutdown_count  : [{closed,1}]
```

**Comment by shrestha-clipapp** [comment] 2018-04-08 06:07
Hi @huangdan 

I am trying to replicate a sample scenario for our app. Our app would use MQTT for 2 two things. One would be to push notifications to some or all the clients and other would be chat option which would let all the  clients talk to each other using EMQTT.

To test these scenarios all clients have one unique topic and one common topic which they are subscribed to. Hence in total for 250k clients there will be 500k subscriptions(2 per each client) with approx 250001 topics. To test this scenario I have setup 40% clients(of 250k clients i.e. 100k clients) which are chatting to each other using MQTT and other 60% (150k clients) which are just on standby(not chatting with each other). I let The number of messages exchanged for each chatting clients is on average 1 message per 250 seconds. These chatting messages are on QoS 2 level. For push notification I am sending one message to all clients(250k clients)  at QoS level 1  in one go. The size of the message is just 4 sentences of text so it would be in bytes for now. It is when I send the QoS level 1 (push notification) when the broker seems to drop clients.

As for the the command "./bin/emqttd_ctl listeners" this is the response I am getting. This response is not after the crash but after I restarted my broker. If you want I will reproduce the scenario again and run this command.  

listener on mqtt:api:0.0.0.0:8080
  acceptors       : 4
  max_clients     : 64
  current_clients : 0
  shutdown_count  : []
listener on mqtt:wss:8084
  acceptors       : 4
  max_clients     : 64
  current_clients : 0
  shutdown_count  : []
listener on mqtt:ssl:8883
  acceptors       : 16
  max_clients     : 1024
  current_clients : 0
  shutdown_count  : []
listener on mqtt:ws:8083
  acceptors       : 4
  max_clients     : 102400
  current_clients : 0
  shutdown_count  : []
listener on mqtt:tcp:0.0.0.0:1883
  acceptors       : 128
  max_clients     : 1000000
  current_clients : 0
  shutdown_count  : []
listener on mqtt:tcp:127.0.0.1:11883
  acceptors       : 4
  max_clients     : 102400
  current_clients : 0
  shutdown_count  : []
listener on dashboard:http:18083
  acceptors       : 4
  max_clients     : 512
  current_clients : 0
  shutdown_count  : []

Please let me know if you need any other information to resolve this issue.

**Comment by terry-xiaoyu** [comment] 2018-09-10 06:11
@shrestha-clipapp EMQ X 3.0 has been released and we've refactored the router. I think this issue has been fixed with it. 

We'll add test cases for this.

**Closed** 2018-12-26 03:09 UTC
Labels: Benchmark

**Comment by boddumanohar** [comment] 2019-12-03 10:34
I did the all the necessary tuning from http://emqtt.io/docs/v2/tune.html# even after that, On an M5.4X large instance, I am seeing this error after exactly 4080 connections.
```
client(1838): connect error - {{shutdown,tcp_closed},
                               {tcp_closed,#Port<0.2331>}}
```
benchmarking using 
```
./emqtt_bench conn -h 172.31.43.149 -p 1883 -c 5000 -i 10 -u "XXXX" -P "XXXX"
```

**Comment by boddumanohar** [comment] 2019-12-03 11:11
when I check the emqx logs, I get this error: 

```
2019-12-03 10:54:14.194 [error]   crasher:
    initial call: esockd_acceptor:init/1
    pid: <0.17793.0>
    registered_name: []
    exception exit: system_limit
      in function  gen_statem:loop_event_result/9
    ancestors: [<0.1297.0>,<0.1295.0>,esockd_sup,<0.1054.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1297.0>]
    dictionary: [{rand_seed,{#{jump => #Fun<rand.16.10897371>,
                                max => 288230376151711743,
                                next => #Fun<rand.15.10897371>,
                                type => exsplus},
                              [214487589861683232|75231122608994654]}}]
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 11411
  neighbours:
```
any idea what this could mean?

**Comment by boddumanohar** [comment] 2019-12-04 03:07
cc: @emqplus @shrestha-clipapp @tigercl @zhanghongtong
