### ISSUE TITLE
Using peer_cert_as_username=cn ,how can I get the client's username

### ISSUE THREAD

**Issue by Forsure-Wang** [emqx/emqx#2307] opened 2019-03-13 12:55 UTC
#### Environment

- OS:  windows 7
- Erlang/OTP:  19 [erts-8.3] [64-bit] [smp:4:4] [async-threads:32]
- EMQ:  2.3.11

#### Description

*As we all know, using the setting peer_cert_as_username=cn, the client's username will be replaced by cert's Common Name whatever the client's username is. Now I what to get the client's username while using the setting peer_cert_as_username=cn, what should I do?*

#### My configuration in emq.conf:
mqtt.allow_anonymous = false

listener.ssl.external.keyfile = etc/certs/key.pem
listener.ssl.external.certfile = etc/certs/cert.pem
listener.ssl.external.cacertfile = etc/certs/cacert.pem

listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = true

listener.ssl.external.peer_cert_as_username = cn

#### 1.Set ipaddress=%u in file emq_auth_http.conf:
![image](https://user-images.githubusercontent.com/17527834/54335297-7f1fae00-4663-11e9-8e69-2b0624e38aa1.png)

#### The setting of mqtt.fx:
![image](https://user-images.githubusercontent.com/17527834/54337723-b3e33380-466a-11e9-89b6-9d054f6b1f42.png)

#### I set username=I_am_username, password=I_am_password, and then I got this:
![image](https://user-images.githubusercontent.com/17527834/54335422-dcb3fa80-4663-11e9-9721-88d0c45761ba.png)

#### 2.Called the api/v2/clients/{clientid} API and I got this:
![image](https://user-images.githubusercontent.com/17527834/54335706-c8243200-4664-11e9-8282-84e57e105a73.png)

#### 3.Subscribed the system topic $SYS/brokers/${node}/clients/${clientid}/connected and I got this:
![image](https://user-images.githubusercontent.com/17527834/54336067-f0606080-4665-11e9-9866-0cd3d0216d58.png)

  As you see,as long as I set "peer_cert_as_username=cn", I can never get the actual username,cause the username has been replaced by cert's Common Name(cn).

  Now I just want to get the cert's Common Name and the client's username at the same time, is there any idea or I did somethting wrong? Thanks for your kindly suggestion!

**Comment by HJianBo** [comment] 2019-03-14 09:00
You can't get both of these in the current version. In my view, you should sign a different cert for every client, if you want to enable this option.

Anyway, we'll discuss this feature! Maybe it is very important in some scenes! Thanks for your suggestion!

**Comment by Forsure-Wang** [comment] 2019-03-14 09:08
@HJianBo Thank you so much and looking forward to the solution.

**Comment by HJianBo** [comment] 2019-03-15 02:28
Hi @Forsure-Wang We have discussed this, But we don't understand why are there need to get both of this at the same time? If you want to get the username of CONNECT packet, just close the peer_cert_as_username option only.

**Comment by Forsure-Wang** [comment] 2019-03-15 16:25
@HJianBo Sorry for late reply and my explanation is as follows.
The fact:
  Different MQTT client can connect to EMQ using the same cert file.

My requirement:
  One certificate can only be used once.In other words, clients can not share it's own cert with others.

My solution:
  Every time I sign a client certificate, I assign the cert's Common Name with a unique string as it's ID.With the "emq_auth_http" plug-in and the setting "peer_cert_as_username=cn", I can get the cert's Commen Name(it's "ID") and store it in database.
  If another client try to connect EMQ via SSL, I would check it's cert file's Common Name first, if the cn is already in database, I return 4XX to the "emq_auth_http" plug-in, meaning the authentication failed.
  And when the clients connecting, I want to check their username at the same time, that's why I need the Common Name and username both.
  
 Have I explained clearly? Maybe there are better solutions to my requirement? Looking forward to your suggestions!

**Comment by HJianBo** [comment] 2019-03-15 23:43
Do you consider to bind cert to client id, and save to database? then you can verify a new arriving connection's username(equal to cert's CN now), client id in you authentication web server. 

It is a preferred solution for that. 
(Or use the password field to save others credential for verifying this action..)

**Comment by Forsure-Wang** [comment] 2019-03-16 10:13
The two suggestions sounds good, thanks a lot !

But if the username field is blank, the EMQ console would print "username undefined" error, users must put  something in the username field.

And, because the username will be replaced by cert's CN whatever the client's username is, users can put what ever  they want in the username field, how weird is it ! , **that's the problem**.

Maybe there are three ways to solve the problem

1.Allow the clients to keep the username undefined
 (Set mqtt.allow_anonymous = true could be help, but when clients connecting via TCP, they don't need to provide username and password anymore, that's not what I want.)

2.Get the cert's CN and client's username at the same time.

3.Deploy two EMQ, one for TCP only,  the other for SSL only.

**Comment by HJianBo** [comment] 2019-03-18 01:05
> But if the username field is blank, the EMQ console would print "username undefined" error. Users must put something in the username field.
The

In the newly released version yesterday, we have fixed this behavior that doesn't deny the empty username connection unless the `allow_anonymous` is false.

In my view, if you set peer_cert_as_username true, you must pass username with CN name on the 1883 connection, which can keep the username having same semantics in the backend.

**Comment by Forsure-Wang** [comment] 2019-03-18 02:54
> In the newly released version yesterday, we have fixed this behavior that doesn't deny the empty username connection unless the `allow_anonymous` is false.

In the new version, empty username connection is allowed even though the `allow_anonymous` is false, right?

> In my view, if you set peer_cert_as_username true, you must pass username with CN name on the 1883 connection, which can keep the username having same semantics in the backend.

I can't get the point, could you explain it please?

**Comment by Forsure-Wang** [comment] 2019-03-18 12:26
> Maybe there are three ways to solve the problem
> 
> **1.Allow the clients to keep the username undefined**
> (Set mqtt.allow_anonymous = true could help, but when clients connecting via TCP(port 1883), they don't need to provide username and password anymore, that's not what I want.)
> 
> **2.Get the cert's CN and client's username at the same time.**
> 
> **3.Deploy two EMQ, one for TCP only, the other for SSL only.**

The third way is a bad idea. I tried to set 'allow_anonymous=true' and load the 'emq_auth_http' plug-in, the Erlang console said *"Username 'undefined' login failed for username_or_password_undefined"* 

Sorry for my stupid mind.

**Comment by Gilbert-Wong** [comment] 2019-03-25 02:22
Sorry, in the implementation of emqx 2.3.11 authentication mechanism. If your load the auth plugin, the `allow_anonymous` would lose efficacy.

**Comment by HJianBo** [comment] 2019-03-26 01:29
Hi, @Forsure-Wang I have put the CN/DN of client cert into the authentication hooks. In other words, you can get these values on the authentication steps:

For example, you can get it on your web server (by the emqx_auth_http plugin)

`emqx_auth_http.conf`
```
##--------------------------------------------------------------------
## Authentication request.
##
## Variables:
##  - %u: username
##  - %c: clientid
##  - %a: ipaddress
##  - %P: password
##  - %cn: common name of client TLS cert
##  - %dn: subject of client TLS cert
##
auth.http.auth_req.params = clientid=%c,username=%u,password=%P,cn=%cn
```

**Comment by Gilbert-Wong** [comment] 2019-04-08 06:15
This feature has been implemented in emqx3.1-rc.1. Please check it :).

**Comment by Forsure-Wang** [comment] 2019-04-09 07:09
@Gilbert-Wong Thanks,but I tried emqx3.1-rc.1 and I got this:
![image](https://user-images.githubusercontent.com/17527834/55779917-54493e00-5ad9-11e9-8407-96457c2fd2c9.png)
have the feature merged into emqx3.1-rc.1 ?

**Comment by HJianBo** [comment] 2019-04-09 08:15
Yes, We have merged and released it. Could you enable the Two-way authentication  in the emqx.conf? 

```
listener.ssl.external.cacertfile = etc/certs/cacert.pem
listener.ssl.external.verify = verify_peer
```
And pass the `common name` in the emqx_auth_http.conf:
```
auth.http.auth_req.params = clientid=%c,username=%u,password=%P,cn=%cn
```

**Comment by Forsure-Wang** [comment] 2019-04-10 13:41
@HJianBo I'm too busy to reply today, sorry for that.
I tried on another PC and got the same result.
Here are my conf file:
emqx.conf
```
allow_anonymous = false
listener.ssl.external.keyfile = etc/certs/key.pem
listener.ssl.external.certfile = etc/certs/cert.pem
listener.ssl.external.cacertfile = etc/certs/cacert.pem
listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = true
```
emqx_auth_http.conf
```
##--------------------------------------------------------------------
## Authentication request.
##
## Variables:
##  - %u: username
##  - %c: clientid
##  - %a: ipaddress
##  - %P: password
##
## Value: URL
auth.http.auth_req = http://127.0.0.1:8991/mqtt/auth
## Value: post | get | put
auth.http.auth_req.method = post
## Value: Params
auth.http.auth_req.params = clientid=%c,username=%u,password=%P,commonname=%cn
```

**Comment by HJianBo** [comment] 2019-04-10 14:07
Have you updated to the v3.1.rc.1?

If updated, the emqx_auth_http.conf seems to be like this:
```protperties

##--------------------------------------------------------------------
## Authentication request.
##
## Variables:
##  - %u: username
##  - %c: clientid
##  - %a: ipaddress
##  - %P: password
##  - %cn: common name of client TLS cert
##  - %dn: subject of client TLS cert
##
## Value: URL
```

**Comment by HJianBo** [comment] 2019-04-14 02:01
This problem caused by the v3.1.rc.1 windows package doesn't contain the newest feature.

And, we have re-pack and release it. It is fixed now. Thanks a lot!

**Closed by HJianBo** 2019-04-14 02:01 UTC
Labels: Discussion, Feature

**Comment by Forsure-Wang** [comment] 2019-04-16 12:19
I tried and it works! Thanks!
