### ISSUE TITLE
Usernames of new clients shown as undefined after reloading emqx_mod_acl_internal

### ISSUE THREAD

**Issue by cvwa** [emqx/emqx#9848] opened 2023-01-27 08:55 UTC
### What happened?

All new clients usernames will be shown as `undefined` after executing `emqx_ctl modules reload emqx_mod_acl_internal`.

The clients usernames were monitored using `emqx_ctl clients list`.

This happens when using only acl.conf file as access control without any additional auth plugins loaded.

### What did you expect to happen?

Expected an acl.conf reload command what would not disrupt how usernames are seen in the output of `emqx_ctl clients list`, similar to what `emqx_ctl acl reload` was in the EMQx version 3.x.x

### How can we reproduce it (as minimally and precisely as possible)?

Baseline:
- Allow pubsub by adding following before the last row to acl.conf: `{allow, {ipaddr, "10.0.0.21"}, pubsub, ["#"]}.`
- Start a static EMQx cluster with all nodes having the same identical acl.conf without any additional plugins loaded
- Connect/subscribe to the broker and using some (any) username
- Message publishing and subscribing works and clients usernames can be seen in the output of `emqx_ctl clients list` as shown:
  - `Client(STg95sCO, username=mqttuser01, peername=10.0.0.27:42543, clean_start=true, keepalive=60, session_expiry_interval=0, subscriptions=0, inflight=0, awaiting_rel=0, delivered_msgs=0, enqueued_msgs=0, dropped_msgs=0, connected=true, created_at=1674755302800, connected_at=1674755302801)`

Reproduce the problem:
- Run `emqx_ctl modules reload emqx_mod_acl_internal`
- Message publishing and subscribing still works **but** usernames of **new clients** will be `undefined` in the output of `emqx_ctl clients list` as shown:
  - `Client(vuz2oVAN, username=undefined, peername=10.0.0.27:50323, clean_start=true, keepalive=60, session_expiry_interval=0, subscriptions=0, inflight=0, awaiting_rel=0, delivered_msgs=0, enqueued_msgs=0, dropped_msgs=0, connected=true, created_at=1674806655413, connected_at=1674806655414)`

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.3.22
uptime    : 14 hours, 18 minutes, 36 seconds
datetime  : 2023-01-27 08:06:23
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux 7c618c58960e 4.18.0-425.3.1.el8.x86_64 #1 SMP Tue Nov 8 14:08:25 EST 2022 x86_64 GNU/Linux
```

</details>

### Log files

<details>

```

========================================================
    /opt/emqx/bin/emqx eval 'emqx_node_dump:app_env_dump()'
========================================================
[{{env,emqx,broker_sys_heartbeat},30000},
 {{env,emqx,plugins_loaded_file},"data/loaded_plugins"},
 {{env,emqx,shared_subscription},true},
 {{env,os_mon,start_cpu_sup},true},
 {{env,emqx,rpc_mode},async},
 {{env,emqx_rule_engine,ignore_sys_message},true},
 {{env,emqx,max_packet_size},1048576},
 {{env,bcrypt,pool_size},4},
 {{env,emqx,route_lock_type},key},
 {{env,emqx,enable_session_registry},true},
 {{env,gen_rpc,tcp_client_num},1},
 {{env,emqx_management,default_application_id},"admin"},
 {{env,emqx,expand_plugins_dir},"etc/plugins/"},
 {{env,emqx,retain_available},true},
 {{env,gen_rpc,async_call_inactivity_timeout},infinity},
 {{env,gen_rpc,socket_keepalive_count},9},
 {{env,ekka,cluster_autoclean},300000},
 {{env,emqx,global_gc_interval},900},
 {{env,gen_rpc,tcp_server_port},5369},
 {{env,bcrypt,default_log_rounds},12},
 {{env,kernel,logger},
  [{handler,console,logger_std_h,
       #{config => #{type => standard_io},
         filters =>
             [{drop_progress_reports,{fun logger_filters:progress/2,stop}}],
         formatter =>
             {emqx_logger_textfmt,
                 #{chars_limit => unlimited,date_format => rfc3339,
                   single_line => true,
                   template =>
                       [time," [",level,"] ",
                        {clientid,
                            [{peername,
                                 [clientid,"@",peername," "],
                                 [clientid," "]}],
                            [{peername,[peername," "],[]}]},
                        msg,"\n"]}},
         level => warning}}]},
 {{env,emqx_telemetry,enabled},true},
 {{env,bcrypt,mechanism},nif},
 {{env,gen_rpc,client_inactivity_timeout},infinity},
 {{env,emqx,max_qos_allowed},2},
 {{env,emqx,shared_subscription_strategy},random},
 {{env,runtime_tools,ttb_autostart_module},ttb_autostart},
 {{env,gen_rpc,tcp_client_port},5369},
 {{env,emqx,client_disconnect_takeovered},false},
 {{env,emqx,broker_sys_interval},60000},
 {{env,emqx,telemetry},
  [{enabled,false},
   {url,"https://telemetry-emqx-io.bigpar.vercel.app/api/telemetry"},
   {report_interval,604800}]},
 {{env,mnesia,dir},"/opt/emqx/data/mnesia/emqx1@10.0.0.31"},
 {{env,kernel,error_logger},silent},
 {{env,gen_rpc,client_config_per_node},{internal,#{}}},
 {{env,ekka,cluster_name},lmjprodcl2022},
 {{env,emqx,max_clientid_len},65535},
 {{env,emqx,acl_file},"etc/acl.conf"},
 {{env,ekka,cluster_autoheal},true},
 {{env,gen_rpc,max_batch_size},256},
 {{env,emqx_retainer,max_retained_messages},0},
 {{env,emqx,strict_mode},false},
 {{env,emqx_retainer,stop_publish_clear_msg},false},
 {{env,gen_rpc,rpc_module_control},disabled},
 {{env,ekka,{callback,prepare}},fun emqx:shutdown/1},
 {{env,os_mon,start_os_sup},false},
 {{env,gen_rpc,ssl_client_port},5370},
 {{env,emqx,trie_compaction},true},
 {{env,os_mon,start_disksup},true},
 {{env,emqx,sysmon},
  [{long_schedule,240},
   {long_gc,0},
   {large_heap,8388608},
   {busy_port,false},
   {busy_dist_port,true}]},
 {{env,emqx,wildcard_subscription},true},
 {{env,gen_rpc,authentication_timeout},5000},
 {{env,gen_rpc,socket_buffer},1048576},
 {{env,gen_rpc,ssl_client_options},[]},
 {{env,emqx,acl_deny_action},ignore},
 {{env,gen_rpc,call_receive_timeout},15000},
 {{env,kernel,net_ticktime},120},
 {{env,emqx,acl_order},"none"},
 {{env,emqx,route_batch_clean},false},
 {{env,observer_cli,scheduler_usage},disable},
 {{env,gen_rpc,socket_sndbuf},1048576},
 {{env,ssl,protocol_version},['tlsv1.3','tlsv1.2']},
 {{env,emqx,alarm},
  [{actions,[log,publish]},{size_limit,1000},{validity_period,86400}]},
 {{env,emqx,zones},
  [{external,
       [{use_username_as_clientid,false},
        {upgrade_qos,false},
        {strict_mode,false},
        {session_expiry_interval,600},
        {retry_interval,30},
        {mqueue_store_qos0,true},
        {mqueue_priorities,none},
        {mqueue_default_priority,highest},
        {max_subscriptions,0},
        {max_mqueue_len,10000},
        {max_inflight,10000},
        {max_awaiting_rel,100},
        {keepalive_backoff,0.75},
        {ignore_loop_deliver,false},
        {idle_timeout,15000},
        {force_shutdown_policy,
            #{max_heap_size => 8388608,message_queue_len => 10000}},
        {force_gc_policy,#{bytes => 16777216,count => 16000}},
        {enable_stats,true},
        {enable_flapping_detect,false},
        {enable_ban,true},
        {enable_acl,true},
        {conn_congestion_min_alarm_sustain_duration,60000},
        {conn_congestion_alarm_enabled,false},
        {bypass_auth_plugins,false},
        {await_rel_timeout,300},
        {acl_deny_action,disconnect}]},
   {internal,
       [{use_username_as_clientid,false},
        {upgrade_qos,false},
        {strict_mode,false},
        {session_expiry_interval,7200},
        {retry_interval,30},
        {mqueue_store_qos0,true},
        {mqueue_priorities,none},
        {mqueue_default_priority,lowest},
        {max_subscriptions,0},
        {max_mqueue_len,3000},
        {max_inflight,3000},
        {max_awaiting_rel,1000},
        {keepalive_backoff,0.75},
        {ignore_loop_deliver,false},
        {idle_timeout,15000},
        {force_shutdown_policy,
            #{max_heap_size => 8388608,message_queue_len => 10000}},
        {enable_stats,true},
        {enable_flapping_detect,false},
        {enable_ban,false},
        {enable_acl,false},
        {conn_congestion_min_alarm_sustain_duration,60000},
        {conn_congestion_alarm_enabled,false},
        {bypass_auth_plugins,true},
        {await_rel_timeout,300},
        {allow_anonymous,true},
        {acl_deny_action,ignore}]}]},
 {{env,emqx,allow_anonymous},true},
 {{env,emqx_retainer,expiry_interval},0},
 {{env,emqx,modules_loaded_file},"data/loaded_modules"},
 {{env,ekka,{callback,reboot}},fun emqx:reboot/0},
 {{env,emqx,plugins_etc_dir},"etc/plugins/"},
 {{env,emqx_management,listeners},
  [{http,8081,
       [{backlog,512},
        {send_timeout,15000},
        {send_timeout_close,true},
        {nodelay,true},
        {inet6,false},
        {ipv6_v6only,false},
        {num_acceptors,2},
        {max_connections,512}]}]},
 {{env,kernel,logger_sasl_compatible},false},
 {{env,emqx,max_topic_alias},65535},
 {{env,emqx_management,max_row_limit},10000},
 {{env,emqx_dashboard,default_user_passwd},"********"},
 {{env,emqx,client_disconnect_discarded},false},
 {{env,gen_rpc,send_timeout},5000},
 {{env,os_mon,memsup_improved_system_memory_data},true},
 {{env,emqx_retainer,max_payload_size},1048576},
 {{env,kernel,logger_level},warning},
 {{env,gen_rpc,rpc_module_list},[]},
 {{env,observer_cli,plugins},[]},
 {{env,ekka,proto_dist},inet_tcp},
 {{env,emqx,flapping_detect_policy},
  #{banned_interval => 300,duration => 60000,threshold => 30}},
 {{env,gen_rpc,ssl_server_options},[]},
 {{env,gen_rpc,socket_recbuf},1048576},
 {{env,emqx_management,default_application_secret},"********"},
 {{env,emqx,backtrace_depth},16},
 {{env,emqx_dashboard,default_user_username},"admin"},
 {{env,gen_rpc,server_inactivity_timeout},infinity},
 {{env,kernel,inet_dist_listen_max},4371},
 {{env,kernel,error_logger_format_depth},100},
 {{env,emqx,acl_cache_ttl},60000},
 {{env,kernel,inet_dist_use_interface},{0,0,0,0}},
 {{env,gen_rpc,socket_ip},{0,0,0,0}},
 {{env,os_mon,start_memsup},true},
 {{env,emqx_dashboard,listeners},
  [{http,18083,
       [{num_acceptors,4},
        {max_connections,512},
        {inet6,false},
        {ipv6_v6only,false}]}]},
 {{env,gen_rpc,socket_keepalive_interval},75},
 {{env,kernel,shell_docs_ansi},auto},
 {{env,emqx_telemetry,report_interval},604800},
 {{env,emqx,listeners},
  [#{listen_on => 1983,name => "internal",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,512},
               {send_timeout,5000},
               {send_timeout_close,true},
               {recbuf,65536},
               {sndbuf,65536},
               {high_watermark,1048576},
               {nodelay,false},
               {reuseaddr,true}]},
          {acceptors,4},
          {max_connections,1024000},
          {max_conn_rate,1000},
          {active_n,1000},
          {zone,internal},
          {proxy_address_header,<<>>},
          {proxy_port_header,<<>>},
          {supported_subprotocols,[]}],
     proto => tcp},
   #{listen_on => 1883,name => "external",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,1024},
               {send_timeout,15000},
               {send_timeout_close,true},
               {high_watermark,1048576},
               {nodelay,true},
               {reuseaddr,true}]},
          {acceptors,64},
          {max_connections,1024000},
          {max_conn_rate,1000},
          {active_n,100},
          {zone,external},
          {proxy_protocol,true},
          {proxy_address_header,<<>>},
          {proxy_port_header,<<>>},
          {supported_subprotocols,[]},
          {access_rules,[{allow,all}]}],
     proto => tcp},
   #{listen_on => 8083,name => "external",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,1024},
               {send_timeout,15000},
               {send_timeout_close,true},
               {nodelay,true}]},
          {acceptors,16},
          {mqtt_path,"/"},
          {max_connections,102400},
          {max_conn_rate,1000},
          {active_n,100},
          {zone,external},
          {proxy_protocol,true},
          {proxy_address_header,<<"x-forwarded-for">>},
          {proxy_port_header,<<"x-forwarded-port">>},
          {fail_if_no_subprotocol,true},
          {supported_subprotocols,["mqtt","mqtt-v3","mqtt-v3.1.1","mqtt-v5"]},
          {mqtt_piggyback,multiple},
          {check_origin_enable,false},
          {allow_origin_absence,true},
          {check_origins,
              [<<"http://localhost:18083">>,<<"http://127.0.0.1:18083">>]},
          {access_rules,[{allow,all}]}],
     proto => ws},
   #{listen_on => 8883,name => "external",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,1024},
               {send_timeout,15000},
               {send_timeout_close,true},
               {recbuf,4096},
               {sndbuf,4096},
               {high_watermark,1048576},
               {nodelay,true},
               {reuseaddr,true}]},
          {ssl_options,
              [{ciphers,
                   ["TLS_AES_256_GCM_SHA384","TLS_AES_128_GCM_SHA256",
                    "TLS_CHACHA20_POLY1305_SHA256","TLS_AES_128_CCM_SHA256",
                    "TLS_AES_128_CCM_8_SHA256",
                    "ECDHE-ECDSA-AES256-GCM-SHA384",
                    "ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384",
                    "ECDHE-RSA-AES256-SHA384","ECDHE-ECDSA-DES-CBC3-SHA",
                    "ECDH-ECDSA-AES256-GCM-SHA384",
                    "ECDH-RSA-AES256-GCM-SHA384","ECDH-ECDSA-AES256-SHA384",
                    "ECDH-RSA-AES256-SHA384","DHE-DSS-AES256-GCM-SHA384",
                    "DHE-DSS-AES256-SHA256","AES256-GCM-SHA384",
                    "AES256-SHA256","ECDHE-ECDSA-AES128-GCM-SHA256",
                    "ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES128-SHA256",
                    "ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256",
                    "ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256",
                    "ECDH-RSA-AES128-SHA256","DHE-DSS-AES128-GCM-SHA256",
                    "DHE-DSS-AES128-SHA256","AES128-GCM-SHA256",
                    "AES128-SHA256","ECDHE-ECDSA-AES256-SHA",
                    "ECDHE-RSA-AES256-SHA","DHE-DSS-AES256-SHA",
                    "ECDH-ECDSA-AES256-SHA","ECDH-RSA-AES256-SHA",
                    "AES256-SHA","ECDHE-ECDSA-AES128-SHA",
                    "ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA",
                    "ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA",
                    "AES128-SHA"]},
               {handshake_timeout,15000},
               {depth,10},
               {keyfile,"etc/certs/key.pem"},
               {certfile,"etc/certs/cert.pem"},
               {cacertfile,"etc/certs/cacert.pem"},
               {reuse_sessions,true},
               {gc_after_handshake,false}]},
          {acceptors,32},
          {max_connections,102400},
          {max_conn_rate,500},
          {active_n,100},
          {zone,external},
          {proxy_address_header,<<>>},
          {proxy_port_header,<<>>},
          {supported_subprotocols,[]},
          {access_rules,[{allow,all}]}],
     proto => ssl},
   #{listen_on => 8084,name => "external",
     opts =>
         [{deflate_options,[]},
          {tcp_options,
              [{backlog,1024},
               {send_timeout,15000},
               {send_timeout_close,true},
               {nodelay,true}]},
          {ssl_options,
              [{ciphers,
                   ["TLS_AES_256_GCM_SHA384","TLS_AES_128_GCM_SHA256",
                    "TLS_CHACHA20_POLY1305_SHA256","TLS_AES_128_CCM_SHA256",
                    "TLS_AES_128_CCM_8_SHA256",
                    "ECDHE-ECDSA-AES256-GCM-SHA384",
                    "ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384",
                    "ECDHE-RSA-AES256-SHA384","ECDHE-ECDSA-DES-CBC3-SHA",
                    "ECDH-ECDSA-AES256-GCM-SHA384",
                    "ECDH-RSA-AES256-GCM-SHA384","ECDH-ECDSA-AES256-SHA384",
                    "ECDH-RSA-AES256-SHA384","DHE-DSS-AES256-GCM-SHA384",
                    "DHE-DSS-AES256-SHA256","AES256-GCM-SHA384",
                    "AES256-SHA256","ECDHE-ECDSA-AES128-GCM-SHA256",
                    "ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES128-SHA256",
                    "ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256",
                    "ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256",
                    "ECDH-RSA-AES128-SHA256","DHE-DSS-AES128-GCM-SHA256",
                    "DHE-DSS-AES128-SHA256","AES128-GCM-SHA256",
                    "AES128-SHA256","ECDHE-ECDSA-AES256-SHA",
                    "ECDHE-RSA-AES256-SHA","DHE-DSS-AES256-SHA",
                    "ECDH-ECDSA-AES256-SHA","ECDH-RSA-AES256-SHA",
                    "AES256-SHA","ECDHE-ECDSA-AES128-SHA",
                    "ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA",
                    "ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA",
                    "AES128-SHA"]},
               {depth,10},
               {keyfile,"etc/certs/key.pem"},
               {certfile,"etc/certs/cert.pem"},
               {reuse_sessions,true}]},
          {acceptors,16},
          {mqtt_path,"/mqtt"},
          {max_connections,102400},
          {max_conn_rate,1000},
          {active_n,100},
          {zone,external},
          {proxy_address_header,<<"x-forwarded-for">>},
          {proxy_port_header,<<"x-forwarded-port">>},
          {fail_if_no_subprotocol,true},
          {supported_subprotocols,["mqtt","mqtt-v3","mqtt-v3.1.1","mqtt-v5"]},
          {mqtt_piggyback,multiple},
          {check_origin_enable,false},
          {allow_origin_absence,true},
          {check_origins,
              [<<"https://localhost:8084">>,<<"https://127.0.0.1:8084">>]},
          {access_rules,[{allow,all}]}],
     proto => wss}]},
 {{env,jose,crypto_fallback},true},
 {{env,gen_rpc,ssl_server_port},false},
 {{env,crypto,fips_mode},false},
 {{env,emqx,vm_mon},
  [{check_interval,30},
   {process_high_watermark,80.0},
   {process_low_watermark,60.0}]},
 {{env,ekka,cluster_discovery},
  {static,[{seeds,['emqx2@10.0.0.32','emqx3@10.0.0.33']}]}},
 {{env,emqx,enable_acl_cache},true},
 {{env,emqx,modules},
  [{emqx_mod_presence,[{qos,1}]},
   {emqx_mod_subscription,[]},
   {emqx_mod_rewrite,[]},
   {emqx_mod_topic_metrics,[]},
   {emqx_mod_delayed,[]},
   {emqx_mod_acl_internal,[{acl_file,"etc/acl.conf"}]}]},
 {{env,gen_rpc,port_discovery},manual},
 {{env,gen_rpc,sbcast_receive_timeout},15000},
 {{env,emqx,shared_dispatch_ack_enabled},false},
 {{env,emqx,auth_order},"none"},
 {{env,emqx,shared_subscription_strategy_per_group},#{}},
 {{env,emqx_telemetry,url},"https://telemetry.emqx.io/api/telemetry"},
 {{env,emqx,session_locking_strategy},quorum},
 {{env,emqx,max_topic_levels},128},
 {{env,gen_rpc,socket_keepalive_idle},900},
 {{env,emqx,acl_cache_max_size},32},
 {{env,gen_rpc,default_client_driver},tcp},
 {{env,emqx,data_dir},"data"},
 {{env,kernel,inet_dist_listen_min},4371},
 {{env,emqx_retainer,storage_type},ram},
 {{env,emqx,acl_nomatch},deny},
 {{env,emqx_rule_engine,events},[]},
 {{env,gen_rpc,connect_timeout},5000},
 {{env,emqx,ignore_loop_deliver},false},
 {{env,emqx,exclusive_subscription},false},
 {{env,crypto,rand_cache_size},896},
 {{env,emqx,os_mon},
  [{cpu_check_interval,60},
   {cpu_high_watermark,80.0},
   {cpu_low_watermark,60.0},
   {mem_check_interval,60},
   {sysmem_high_watermark,70.0},
   {procmem_high_watermark,5.0}]}]

```

</details>

**Comment by tigercl** [comment] 2023-02-01 01:36
@cvwa Hi. Sorry to keep you waiting. I was not able to reproduce the problem. Can you trace the clients connected after reloading the module for more detailed logs?

[How to trace?](https://www.emqx.io/docs/en/v4.3/getting-started/log.html#control-log-output)

**Comment by zmstone** [comment] 2024-02-02 17:38
closing this issue as 4.3 is no longer supported, please upgrade to v5.

**Closed by zmstone** 2024-02-02 17:38 UTC
Labels: BUG
