### ISSUE TITLE
Update authentication options using emqx_conf:update fails due to function_clause error

### ISSUE THREAD

**Issue by MikeDombo** [emqx/emqx#11095] opened 2023-06-20 00:44 UTC
### What happened?

Trying to update the `authentication` section in a local override fails due to:

```
[error] msg: change_config_crashed, mfa: emqx_config_handler:handle_update_request/4, line: 208, exception: error, key_path: [authentication], module: emqx_conf_schema, reason: function_clause, stacktrace: [{emqx_authentication_config,do_pre_config_update,[[#{<<"backend">> => <<"http">>,<<"mechanism">> => <<"password_based">>,<<"method">> => <<"get">>,<<"url">> => <<"http://localhost/testing">>}],[#{<<"backend">> => <<"http">>,<<"mechanism">> => <<"password_based">>,<<"method">> => <<"get">>,<<"url">> => <<"http://172.17.0.1:34275/mqtt/auth?clientid=&username=&password=">>}]],[{file,"emqx_authentication_config.erl"},{line,73}]},{emqx_authentication_config,pre_config_update,3,[{file,"emqx_authentication_config.erl"},{line,65}]},{emqx_config_handler,call_pre_config_update,4,[{file,"emqx_config_handler.erl"},{line,385}]},{emqx_config_handler,do_update_config,5,[{file,"emqx_config_handler.erl"},{line,273}]},{emqx_config_handler,process_update_request,3,[{file,"emqx_config_handler.erl"},{line,243}]},{emqx_config_handler,do_handle_update_request,4,[{file,"emqx_config_handler.erl"},{line,213}]},{emqx_config_handler,handle_update_request,4,[{file,"emqx_config_handler.erl"},{line,195}]},{emqx_config_handler,handle_call,3,[{file,"emqx_config_handler.erl"},{line,124}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}], update_req: {{update,[#{<<"backend">> => <<"http">>,<<"mechanism">> => <<"password_based">>,<<"method">> => <<"get">>,<<"url">> => <<"http://localhost/testing">>}]},#{override_to => local}}
```

Looking at the code for the pre config update in authentication, it seems that it requires the update request to use specific atoms and not the generic "update" atom which is used by `emqx_conf:update`.

### What did you expect to happen?

`emqx_conf:update` should be able to update the configuration for authentication without failing.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by MikeDombo** [comment] 2023-06-20 11:37
5.0.22.

Updating `authentication` key with:
```json
{
              "mechanism": "password_based",
              "backend": "http",
              "method": "get",
              "url": "http://localhost/testing"
            }
          ]
```

**Comment by id** [comment] 2023-06-20 12:51
Observed the same behavior in v5.0.22, but the issue seems to be fixed in the latest version, couldn't reproduce this on release-51 branch.

**Comment by MikeDombo** [comment] 2023-06-20 13:02
Odd that 5.1 doesn't have the same problem. Are you able to point to the change which fixed it?

**Comment by id** [comment] 2023-06-20 14:13
Theoretically yes, but not at the moment :)

**Comment by MikeDombo** [comment] 2023-06-20 15:21
https://github.com/emqx/emqx/pull/10783
this change seems relevant, though it isn't clear why it would actually fix the problem.

**Comment by zmstone** [comment] 2023-06-22 20:08
Hi. @MikeDombo 
Config (re)loading is a new feature and it was not yet supported in v5.0.22.
The old version update requests are mostly to facilitate API requests made from the dashboard.
Prior to 5.1, you can technically mimic the dashboard behavior to call HTTP APIs in order to make changes to the authenticator chain.

**Closed by zmstone** 2023-06-22 20:08 UTC
Labels: BUG
