### ISSUE TITLE
Rule Engine fails if binary payload

### ISSUE THREAD

**Issue by alexandrim0** [emqx/emqx#3287] opened 2020-03-04 12:52 UTC
#### Environment

- OS: ubuntu 18/04
- Erlang/OTP: R22/10.5.6
- EMQ: 4.0.3 (docker)

#### Description

Rule Engine fails if binary payload. It seems, like Rule Engine do parse payload even there is no select from payload.

SQL query:
  SELECT username, clientid, topic, payload FROM "hub/1/presence/#"

Error on action: 
  2020-03-04 11:30:56.655 [error] <<"mdseV8itGOQXipzcxbdrcJPProwrvdtNuCUyBvHR2hMvyStLGGbC1pZvQ80q0LRk">>@{address:port obfuscated} Apply rule rule:69a114c3 failed: {take_action_failed,
                                  {<<"data_to_webserver_1583258493072805679">>,
                                   {invalid_string,
                                    <<191,101,109,111,100,101,108,114,114,52,
                                      115,95,107,101,116,116,108,101,95,101,
                                      120,97,109,112,108,101,102,115,101,114,
                                      105,97,108,70,132,13,142,173,167,205,
                                      107,100,101,118,105,99,101,95,114,111,
                                      111,116,120,75,114,52,115,47,50,47,100,
                                      57,49,49,47,109,100,115,101,86,56,105,
                                      116,71,79,81,88,105,112,122,99,120,98,
                                      100,114,99,74,80,80,114,111,119,114,118,
                                      100,116,78,117,67,85,121,66,118,72,82,
                                      50,104,77,118,121,83,116,76,71,71,98,67,
                                      49,112,90,118,81,56,48,113,48,76,82,107,
                                      112,102,105,114,109,119,97,114,101,95,
                                      118,101,114,115,105,111,110,99,49,46,48,
                                      255>>},

**Comment by terry-xiaoyu** [comment] 2020-03-05 01:26
@alexandrim0 Could you provide more detailed log messages just after what you post? It would contain the full stack trace info.

**Comment by terry-xiaoyu** [comment] 2020-03-05 01:42
@alexandrim0 And also what're the params you provided to the resource `WebHook ` and the action `data_to_webserver `?

**Comment by ThomasArts** [comment] 2020-03-07 10:16
Check issue #2397

**Comment by alexandrim0** [comment] 2020-03-07 15:34
@terry-xiaoyu  there is no special params to Webhook action, just url. This rule works fine with that url for ASCII string in a payload, but action fails if it is a binary string like cbor which I use.

With plugin Webhook I met the same trouble. But if I set plugin param "web.hook.encode_payload=base64" then Webhook works fine.
I did not check if Rule Engine Action will works fine with setting webhook plugin to encode payload. Should I?
Anyway, It is not clear if Rule Engine use params of some not enabled plugin.
Also I did not find param like that in config file of Rule Engine.

The full log about that message:
`2020-03-04 12:49:19.777 [debug] <<"mdseV8itGOQXipzcxbdrcJPProwrvdtNuCUyBvHR2hMvyStLGGbC1pZvQ80q0LRk">>@188.170.78.103:1375 [MQTT] RECV PUBLISH(Q1, R0, D0, Topic=hub/1/presence, PacketId=4, Payload=<<"¡emodelcr4s">>)
2020-03-04 12:49:19.780 [info] <<"mdseV8itGOQXipzcxbdrcJPProwrvdtNuCUyBvHR2hMvyStLGGbC1pZvQ80q0LRk">>@188.170.78.103:1375 PUBLISH to hub/1/presence: <<"¡emodelcr4s">>
2020-03-04 12:49:19.780 [debug] <<"mdseV8itGOQXipzcxbdrcJPProwrvdtNuCUyBvHR2hMvyStLGGbC1pZvQ80q0LRk">>@188.170.78.103:1375 [WebHook Action] post to http://172.17.0.1:1083/presence/online, headers: , body: #{clientid =>
                                                                                        <<"mdseV8itGOQXipzcxbdrcJPProwrvdtNuCUyBvHR2hMvyStLGGbC1pZvQ80q0LRk">>,
                                                                                    payload =>
                                                                                        <<"¡emodelcr4s">>,
                                                                                    topic =>
                                                                                        <<"hub/1/presence">>,
                                                                                    username =>
                                                                                        <<"d911">>}
2020-03-04 12:49:19.781 [error] <<"mdseV8itGOQXipzcxbdrcJPProwrvdtNuCUyBvHR2hMvyStLGGbC1pZvQ80q0LRk">>@188.170.78.103:1375 Apply rule rule:69a114c3 failed: {take_action_failed,
                                  {<<"data_to_webserver_1583258493072805679">>,
                                   {invalid_string,<<"¡emodelcr4s">>},
                                   [{jiffy,encode,2,
                                     [{file,
                                       "/emqx_rel/_build/emqx/lib/jiffy/src/jiffy.erl"},
                                      {line,99}]},
                                    {emqx_web_hook_actions,http_request,4,
                                     [{file,
                                       "/emqx_rel/_build/emqx/lib/emqx_web_hook/src/emqx_web_hook_actions.erl"},
                                      {line,144}]},
                                    {emqx_rule_runtime,take_action,3,
                                     [{file,
                                       "/emqx_rel/_build/emqx/lib/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                                      {line,225}]},
                                    {lists,map,2,
                                     [{file,"lists.erl"},{line,1239}]},
                                    {emqx_rule_runtime,apply_rule,2,
                                     [{file,
                                       "/emqx_rel/_build/emqx/lib/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                                      {line,99}]},
                                    {emqx_rule_runtime,apply_rules,2,
                                     [{file,
                                       "/emqx_rel/_build/emqx/lib/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                                      {line,47}]},
                                    {emqx_rule_events,on_message_publish,2,
                                     [{file,
                                       "/emqx_rel/_build/emqx/lib/emqx_rule_engine/src/emqx_rule_events.erl"},
                                      {line,97}]},
                                    {emqx_hooks,safe_execute,2,
                                     [{file,
                                       "/emqx_rel/_build/emqx/lib/emqx/src/emqx_hooks.erl"},
                                      {line,164}]}]}}. Stacktrace:
[{emqx_rule_runtime,take_action,3,
                    [{file,"/emqx_rel/_build/emqx/lib/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                     {line,231}]},
 {lists,map,2,[{file,"lists.erl"},{line,1239}]},
 {emqx_rule_runtime,apply_rule,2,
                    [{file,"/emqx_rel/_build/emqx/lib/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                     {line,99}]},
 {emqx_rule_runtime,apply_rules,2,
                    [{file,"/emqx_rel/_build/emqx/lib/emqx_rule_engine/src/emqx_rule_runtime.erl"},
                     {line,47}]},
 {emqx_rule_events,on_message_publish,2,
                   [{file,"/emqx_rel/_build/emqx/lib/emqx_rule_engine/src/emqx_rule_events.erl"},
                    {line,97}]},
 {emqx_hooks,safe_execute,2,
             [{file,"/emqx_rel/_build/emqx/lib/emqx/src/emqx_hooks.erl"},
              {line,164}]},
 {emqx_hooks,do_run_fold,3,
             [{file,"/emqx_rel/_build/emqx/lib/emqx/src/emqx_hooks.erl"},
              {line,143}]},
 {emqx_broker,publish,1,
              [{file,"/emqx_rel/_build/emqx/lib/emqx/src/emqx_broker.erl"},
               {line,202}]}]
2020-03-04 12:49:19.783 [debug] <<"mdseV8itGOQXipzcxbdrcJPProwrvdtNuCUyBvHR2hMvyStLGGbC1pZvQ80q0LRk">>@188.170.78.103:1375 [MQTT] SEND PUBACK(Q0, R0, D0, PacketId=4)`

@ThomasArts I belive this issues are not connected. Thanks.

**Comment by ThomasArts** [comment] 2020-03-08 07:51
Indeed, that seems unrelated. If you get invalid_string on that binary, then you most likely can find a "~s" somewhere in an io_lib:format where you try to format this binary. Could be in a log, could be elsewhere. Try to generate a stacktrace just before you get this error to see what modules are playing a role.

**Comment by terry-xiaoyu** [comment] 2020-03-09 06:05
@alexandrim0 @ThomasArts 

Thanks for your help, the issue is caused by emqx_json when encoding utf8 chars. The fix will be included in v4.0.5.

**Comment by HJianBo** [comment] 2020-03-17 12:22
Hi guys, We have fixed it and released it into v4.0.5. Plz try it :)

**Closed by HJianBo** 2020-03-17 12:22 UTC
Labels: BUG

**Comment by alexandrim0** [comment] 2020-03-18 11:40
Hi, @HJianBo!

Thank you!
I had tested 4.0.5 with UTF8 and it works fine. I`m not sure it did not works before.

But UTF8 is not a binary in general. I still can not be sure if any binary data in payload will be delivered and not modified by UTF8 parser (or other code is thinking it is a UTF8 string) in case of using CBOR.
The option to encode payload to BASE64 (like in web hook plugin) could be a way.
Am I right or not?

**Comment by KonstantinRitt** [comment] 2020-11-27 20:56
The issue isn't solved by any means, plz re-open.

Forcing UTF-8 to non-textual data and then decoding it from UTF-8 is undefined behaviour and produces a corrupted data in most cases.

**Comment by bitgorbovsky** [comment] 2020-11-27 22:12
Hello there.

To my mind, instead of inventing solution, how not no to touch binary content and pass it through json (please note, that json is not about binaries), for some cases using base64_encode function in SQL statements of rules is appropriate solution.

At least, it works for me :)
