### ISSUE TITLE
Nodes can't communicate  in static cluster

### ISSUE THREAD

**Issue by Rotario** [emqx/emqx#12484] opened 2024-02-06 00:53 UTC
### What happened?

I'm running a 2 core node cluster on fly.io
my cluster settings are:
```
  EMQX_CLUSTER__PROTO_DIST = "inet6_tcp"
  EMQX_CLUSTER__DISCOVERY_STRATEGY = "static"
  EMQX_CLUSTER__STATIC__SEEDS = "[emqx@xxxxx.vm.emqx.internal,emqx@xxxxxx.vm.emqx.internal]"
```
They're running fine most of the time:
![image](https://github.com/emqx/emqx/assets/29485059/abaa88ff-b5a6-4898-8702-6aa5f75b511b)

But when testing I've found that sometimes they get stuck and can't communicate and spit out the following logs:
```
2024-02-06T00:35:56Z app[6e82e56f2e3038] lhr [info]2024-02-06T00:35:56.990082+00:00 [error] event=connect_to_remote_server, peer=emqx@2874de3c1675d8.vm.emqx.internal, port=5369, reason=nxdomain                  
2024-02-06T00:35:56Z app[6e82e56f2e3038] lhr [info]2024-02-06T00:35:56.990243+00:00 [error] crasher: initial call: gen_rpc_client:init/1, pid: <0.7306.0>, registered_name: [], exit: {{badrpc,nxdomain},[{gen_serv
er,init_it,6,[{file,"gen_server.erl"},{line,835}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}, ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.2123.0>], message_queue_len: 0, messages: [], l
inks: [<0.2129.0>], dictionary: [], trap_exit: true, status: running, heap_size: 2586, stack_size: 28, reductions: 2710; neighbours:   
```

This results in the fact that if I subscribe to one node, I don't receive messages sent to the other node.
I've found a restart fixes this, but I can't deploy EMQX into production if this occurs.
What could potentially be causing this please? Is it the DNS resolution of the domain names from the cloud provider (docs here: https://fly.io/docs/networking/private-networking/)? If so I'm waiting for https://github.com/emqx/emqx/pull/12467 to get merged so I can move to AAAA discovery. This might fix the issue.

### What did you expect to happen?

I expected two nodes to communicate correctly using my cloud provider's private IP address resolution mechanisms

### How can we reproduce it (as minimally and precisely as possible)?

Use static discovery and 2 seeds

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.4.1
datetime  : 2024-02-06T00:52:37.516464153+00:00
uptime    : 14 minutes, 54 seconds

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux 2874de3c1675d8 5.15.98-fly #g2626e66887 SMP Mon Jan 29 07:34:38 UTC 2024 x86_64 GNU/Linux

```

</details>

### Log files

<details>
2024-02-06T00:35:56Z app[6e82e56f2e3038] lhr [info]2024-02-06T00:35:56.990082+00:00 [error] event=connect_to_remote_server, peer=emqx@2874de3c1675d8.vm.emqx.internal, port=5369, reason=nxdomain                  
2024-02-06T00:35:56Z app[6e82e56f2e3038] lhr [info]2024-02-06T00:35:56.990243+00:00 [error] crasher: initial call: gen_rpc_client:init/1, pid: <0.7306.0>, registered_name: [], exit: {{badrpc,nxdomain},[{gen_serv
er,init_it,6,[{file,"gen_server.erl"},{line,835}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}, ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.2123.0>], message_queue_len: 0, messages: [], l
inks: [<0.2129.0>], dictionary: [], trap_exit: true, status: running, heap_size: 2586, stack_size: 28, reductions: 2710; neighbours:   
</details>

**Comment by Rotario** [comment] 2024-02-06 07:51
Cool thanks I'll close this and investigate

**Comment by Rotario** [comment] 2024-02-06 17:01
Hi - I've still got this issue, I've installed dnsutils on the production server and when I run
nslookup xxxx
the IP is resolved correctly.
I'm still getting this issue however sometimes. I don't think EMQX supports AAAA records properly somehow

```
2024-02-06T16:56:21Z app[2874de3c1675d8] lhr [info]2024-02-06T16:56:21.032192+00:00 [error] event=connect_to_remote_server, peer=emqx@6e82e56f2e3038.vm.emqx.internal, port=5369, reason=nxdomain
2024-02-06T16:56:21Z app[2874de3c1675d8] lhr [info]2024-02-06T16:56:21.032304+00:00 [error] crasher: initial call: gen_rpc_client:init/1, pid: <0.11531.1>, registered_name: [], exit: {{badrpc,nxdomain},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,835}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}, ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.2123.0>], message_queue_len: 0, messages: [], links: [<0.2129.0>], dictionary: [], trap_exit: true, status: running, heap_size: 2586, stack_size: 28, reductions: 2712; neighbours:
```

**Comment by kjellwinblad** [comment] 2024-02-07 10:06
Hi,

Did you test with a version that includes the AAAA record fix: https://github.com/emqx/emqx/pull/12467? I Don't think that fix is included in version 5.4.1 as it just recently got merged into the master branch.

**Comment by Rotario** [comment] 2024-02-07 12:11
I'm running from a docker image. Can I just copy the 5.5 Docker file and
replace the emqx version with master?

**Comment by ieQu1** [comment] 2024-02-07 12:12
Not sure if the above PR will help:
- It only affects `DNS` discovery strategy
- It only adds a parameter to the configuration schema, and doesn't change anything in the underlying code.

**Comment by Rotario** [comment] 2024-02-07 14:58
Sure - from VM1
```
root@6e82e56f2e3038:/opt/emqx# nslookup 2874de3c1675d8.vm.emqx.internal
Server:		fdaa::3
Address:	fdaa::3#53

Name:	2874de3c1675d8.vm.emqx.internal
Address: fdaa:0:xxxx:xxxx:xxxx:4935:2
```

from VM2
```
root@2874de3c1675d8:/opt/emqx# nslookup 6e82e56f2e3038.vm.emqx.internal
Server:		fdaa::3
Address:	fdaa::3#53

Name:	6e82e56f2e3038.vm.emqx.internal
Address: fdaa:0:xxxx:xxx:xx:xxxx:e24:2
````

**Comment by ieQu1** [comment] 2024-02-07 17:22
If I understand correctly, the problem is intermittent, and the node can communicate after restart, or similar actions. I assume the IP addresses don't change. This points at the name resolution errors.

What distro are you running? Does it have a local DNS cache, like `systemd-resolved`. Also, what is the TTL for the AAAA record?

**Comment by Rotario** [comment] 2024-02-08 14:50
Hi - No I think it seems pretty consistent now.

**Comment by Rotario** [comment] 2024-02-08 23:22
I'm going to wait for the DNS discovery AAAA feature to be released and try that

**Comment by Rotario** [comment] 2024-02-09 15:37
Hi - I've got the master branch working now on the cloud provider
```
  EMQX_CLUSTER__DNS__NAME = "emqx.internal"
  EMQX_CLUSTER__DNS__RECORD_TYPE = "aaaa"
  EMQX_CLUSTER__PROTO_DIST = "inet6_tcp"
  EMQX_CLUSTER__DISCOVERY_STRATEGY = "dns"
```
And I'm still getting nxdomain issues - I think it's now interpretting this ipv6 IP as a domain name? Does it need to be bracketed?
```
2024-02-09T15:36:12Z app[6e82e56f2e3038] lhr [info]2024-02-09T15:36:12.952226+00:00 [error] event=connect_to_remote_server, peer=emqx@fdaa:0:e26a:a7b:172:b294:4935:2, port=5369, reason=nxdomain
2024-02-09T15:36:12Z app[6e82e56f2e3038] lhr [info]2024-02-09T15:36:12.952315+00:00 [error] crasher: initial call: gen_rpc_client:init/1, pid: <0.12092.0>, registered_name: [], exit: {{badrpc,nxdomain},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,961}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]}, ancestors: [gen_rpc_client_sup,gen_rpc_sup,<0.2158.0>], message_queue_len: 0, messages: [], links: [<0.2164.0>], dictionary: [], trap_exit: true, status: running, heap_size: 2586, stack_size: 28, reductions: 2615; neighbours:
```

**Comment by Rotario** [comment] 2024-02-09 16:24
I've changed the node name from emqx@ipv6_of_machine to emqx@FQDN of machine 
and now I'm getting
```
Cannot get connection id for node 'emqx@2874de3c1675d8.vm.emqx.internal'
```

**Comment by Rotario** [comment] 2024-02-12 10:44
The cluster seems to be working fine - with messages and subscribes passing thru transparently. Though the `cant get connection id` is still logging

**Comment by ieQu1** [comment] 2024-02-15 21:16
I recall that `cant get connection id` message originates inside the Erlang runtime... I'll have to take a deep dive into the Erlang code to find the precise conditions that trigger it, and what are the implications of that error.

**Comment by Rotario** [comment] 2024-02-18 18:11
It seeems related to nodes trying to connect to themselves which makes sense from the logs.
Maybe the auto DNS discovery mechanism with ipv6 makes a node try to connect to itself? Maybe some compare function that should return true to make a node not connect to itself doesn't compare IPv6 IPs properly or something? 

Searching in GH i can't find Node.connect anywhere, so cant find the place where nodes are connecting to each other.
```
2024-02-18T18:09:01Z app[6e82e56f2e3038] lhr [info]2024-02-18T18:09:01.339236+00:00 [error] ** Cannot get connection id for node 'emqx@6e82e56f2e3038.vm.emqx.internal'
2024-02-18T18:09:08Z app[2874de3c1675d8] lhr [info]2024-02-18T18:09:08.114719+00:00 [error] ** Cannot get connection id for node 'emqx@2874de3c1675d8.vm.emqx.internal'
```
https://github.com/bitwalker/libcluster/issues/70
https://github.com/mrluc/peerage/pull/17/files

**Comment by zmstone** [comment] 2024-02-19 10:18
Found this fix: https://github.com/erlang/otp/pull/1870 but merged long ago, EMQX 5.4.1 should have the fix in place.
maybe there are other call paths not covered.

**Comment by zmstone** [comment] 2024-02-19 13:13
Hi again @Rotario 
"Cannot get connection id" has happened before in ipv4 network too, but I never managed to find the cause.
If you are open to run some debug tests. I can provide a patch + steps to install the patch to help the investigation.
the patch will try to print the stacktrace when a node tries to self-connect.

**Comment by zmstone** [comment] 2024-02-19 18:46
Hi @Rotario 

Here is the beam file: https://we.tl/t-Cxck7JxkD1 (expires in 7 days)
Sha256sum of the beam file: 44551fcb70c1d58a9e2ab8430a968d65de37552e1e5d7012dcf0cf6ddbefba0a
Code diff: https://github.com/zmstone/otp/commit/41dcd061758b8a7b148b997e659b1e3cd558a202

Mount this file to replace `/opt/emqx/lib/kernel-8.5.4/ebin/net_kernel.beam`
Or commit a new docker tag with this file replaced in the container.

**Comment by Rotario** [comment] 2024-02-19 20:00
Thanks for your help!
```
2024-02-19T20:00:10Z app[6e82e56f2e3038] lhr [info]2024-02-19T20:00:10.700354+00:00 [error] ** Cannot get connection id for node 'emqx@6e82e56f2e3038.vm.emqx.internal'
2024-02-19T20:00:10Z app[6e82e56f2e3038] lhr [info]2024-02-19T20:00:10.700470+00:00 [error] error:badarg, [{erts_internal,new_connection,['emqx@6e82e56f2e3038.vm.emqx.internal'],[{error_info,#{module => erl_erts_errors}}]},{net_kernel,handle_info,2,[{file,"net_kernel.erl"},{line,1098}]},{gen_server,try_handle_info,3,[{file,"gen_server.erl"},{line,1095}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1183}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]
```

**Comment by zmstone** [comment] 2024-02-20 09:42
Thank you @Rotario.
The log narrowed it down a bit.
Now we know that it's logged when accepting a new connection from Erlang distribution listener.
We might need to trace/debug the connection initiator side, but I need to dig more in the code to find where to trace.

In the meantime, could you help to test with this patch?  [dist-debug.zip](https://github.com/emqx/emqx/files/14341790/dist-debug.zip).
It included more debug logs.


Also would like to ask:
- Does it happen if you start a single node?
- How often do you see this logged?

Example (normal) logs from the patch:
```
v5.4.1(emqx@192.168.31.216)1> 110989263 'emqx@192.168.31.216':recv_name: 'N' name="emqx2@192.168.31.216" creation=4
{"MD5 connection from ~p~n",['emqx2@192.168.31.216']}
{net_kernel,accept_pending,'emqx@192.168.31.216','emqx2@192.168.31.216',undefined,[]}
110990781 'emqx@192.168.31.216':do_mark_pending(<0.2016.0>,'emqx@192.168.31.216','emqx2@192.168.31.216',55966662589) -> ok
{dist_util,<0.3250.0>,send_status,'emqx2@192.168.31.216',ok}
110991845 'emqx@192.168.31.216':send: 'N' challenge=780365816 creation=4
110994512 'emqx@192.168.31.216':recv_reply: challenge=631707742 digest=[6,93,82,221,42,134,231,21,140,166,246,
                                        161,49,183,233,112]
110994717 'emqx@192.168.31.216':sum = <<6,93,82,221,42,134,231,21,140,166,246,161,49,183,233,112>>
110994893 'emqx@192.168.31.216':send_ack: digest=<<25,210,44,53,117,211,215,113,115,210,118,160,255,201,32,218>>
{dist_util,<0.3250.0>,accept_connection,'emqx2@192.168.31.216'}
110995605 'emqx@192.168.31.216':setnode: node='emqx2@192.168.31.216' port=#Port<0.18> flags=55966662589(normal) creation=4
```

**Comment by zmstone** [comment] 2024-02-20 09:55
Some more information for you to troubleshoot the network:
EMQX node resolves the peer's port from node name, in your case, both nodes should be listening on port `4370`.
If node `2874de3c1675d8@vm.emqx.internal.4370` tries to connect `6e82e56f2e3038.vm.emqx.internal:4370` but end up resolving `6e82e56f2e3038` to self IP, or if the connection is looped back to self due to a misconfigured TCP routing/port forwarding, this might happen.

**Comment by zmstone** [comment] 2024-02-20 10:22
For reference. This is what happens if I self-connect with a different name:

```
v5.4.1(emqx@192.168.31.216)1>  net_kernel:connect_node(node()).
true
v5.4.1(emqx@192.168.31.216)2>  net_kernel:connect_node('emqx@local.host').
20025380 'emqx@192.168.31.216':send_name: 'N' node='emqx@192.168.31.216' creation=4
20025933 'emqx@192.168.31.216':recv_name: 'N' name="emqx@192.168.31.216" creation=4
{"MD5 connection from ~p~n",['emqx@192.168.31.216']}
{net_kernel,accept_pending,'emqx@192.168.31.216','emqx@192.168.31.216',undefined,[]}
2024-02-20T10:20:05.500277+00:00 [error] ** Cannot get connection id for node 'emqx@192.168.31.216'
2024-02-20T10:20:05.500549+00:00 [error] error:badarg, [{erts_internal,new_connection,['emqx@192.168.31.216'],[{error_info,#{module => erl_erts_errors}}]},{net_kernel,handle_info,2,[{file,"net_kernel.erl"},{line,1099}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,1123}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]
20027524 'emqx@192.168.31.216':do_mark_pending(<0.2016.0>,'emqx@192.168.31.216','emqx@192.168.31.216',55966662589) -> nok_pending
{dist_util,<0.3196.0>,send_status,'emqx@192.168.31.216',nok}
{dist_util,<0.3194.0>,recv_status,'emqx@local.host',"nok"}
```

this line looks suspicious in your logs: `{dist_util,<0.3085.0>,recv_status,'emqx@fdaa:0:e26a:a7b:8f:ff70:e24:2',"nok"}`

**Comment by zmstone** [comment] 2024-02-20 10:55
@Rotario I guess `fdaa:0:e26a:a7b:8f:ff70:e24:2` is `6e82e56f2e3038`'s address?
Is `emqx@fdaa:0:e26a:a7b:8f:ff70:e24:2` by any chance configured in the static discovery node list ?
Could you share the output of this command (in the container): `emqx eval 'application:get_all_env(ekka)'`

**Comment by Rotario** [comment] 2024-02-20 10:59
Ok could it maybe just be a hangover from switching discovery mechanisms?

```
root@6e82e56f2e3038:/opt/emqx# emqx eval 'application:get_all_env(ekka)'
643702 'remsh_maint_emqx763@6e82e56f2e3038.vm.emqx.internal':send_name: 'N' node='remsh_maint_emqx763@6e82e56f2e3038.vm.emqx.internal' creation=4
{dist_util,<0.93.0>,recv_status,'emqx@6e82e56f2e3038.vm.emqx.internal',"ok"}
656404 'remsh_maint_emqx763@6e82e56f2e3038.vm.emqx.internal':recv: 'N' node="emqx@6e82e56f2e3038.vm.emqx.internal", challenge=3526690536 creation=4
657095 'remsh_maint_emqx763@6e82e56f2e3038.vm.emqx.internal':send_reply: challenge=785686415 digest=<<190,232,253,141,252,169,249,220,242,
                                         38,215,173,131,214,231,93>>
659050 'remsh_maint_emqx763@6e82e56f2e3038.vm.emqx.internal':recv_ack: digest=[19,143,161,52,113,63,105,18,229,8,223,64,237,51,219,50]
659608 'remsh_maint_emqx763@6e82e56f2e3038.vm.emqx.internal':sum = <<19,143,161,52,113,63,105,18,229,8,223,64,237,51,219,50>>
660181 'remsh_maint_emqx763@6e82e56f2e3038.vm.emqx.internal':setnode: node='emqx@6e82e56f2e3038.vm.emqx.internal' port=#Port<0.6> flags=55966662588(hidden) creation=4
[{proto_dist,inet6_tcp},
 {cluster_discovery,{dns,[{name,"emqx.internal"},{type,aaaa}]}},
 {{callback,stop},fun emqx_machine_boot:stop_apps/0},
 {cluster_name,emqxcl},
 {{callback,start},fun emqx_machine_boot:ensure_apps_started/0}]
```

**Comment by Rotario** [comment] 2024-02-20 11:01
I've noticed the nodes aren't discovering each other either. I have to run `emqx ctl cluster join <node>`. This isn't an issue right now. Can explore it later

**Comment by zmstone** [comment] 2024-02-20 11:12
Ah. ok.
Now I get it.
The node name should not use FQDN as host part if you use DNS discovery strategy.
This is because DNS resolution is a list of IP addresses, this will always make the nodes connect peers using `node@IP`.

You'll need to either use static/maul strategy for node discovery,
or use DNS, but assign static IPs to the containers.

**Comment by Rotario** [comment] 2024-02-20 11:13
Ah ok brill thank you! And set node names to the ip not to the fqdn. Brill thank you

**Comment by zmstone** [comment] 2024-02-20 11:15
@Rotario Thank you.
This debug session resolved a long time myth for us.

**Closed** 2024-02-20 11:15 UTC
Labels: #triage/wait
