### ISSUE TITLE
Clustering issue

### ISSUE THREAD

**Issue by jayjamba** [emqx/emqx#3058] opened 2019-11-26 10:48 UTC
- OS: CentOS Linux 7
- Erlang/OTP: 
- EMQ: **3.2.5**

Scenario : Our application is running on 3 different ports 8081, 8082 and 8083. We have also deployed EMQX broker on 3 different machines 192.168.0.1, 192.168.0.2, 192.168.0.3 and is clustered successfully. Our application is connecting to this broker.

Few Questions related to above scenario:
Q1) Since our application is running on 3 different ports, so Should we connect to different emqx nodes from different port i.e. 8081 port should connect to 192.168.0.1; 8082 port should connect to 192.168.0.2 and 8083 port should connect to 192.168.0.3

OR Connecting to one node from all our application nodes is advisable i.e. connecting to 192.168.0.1 from all 3 ports 8081,8082 and 8083. And then load balance on emqx cluster is managed by itself ?

Q2) Any particular configuration that we need to take care of to prevent messages from getting dropped ? Coz we have been facing problem of messages getting dropped in either of the case i.e. even if we connect to one broker from all 3 ports OR connecting to different brokers from all 3 ports.

Below are the configuration we have changed in the conf file:

zone.external.max_awaiting_rel = 0
zone.external.await_rel_timeout = 600s

Q3) Which is the reliable JAVA client to connect to any node in cluster ? 
Can you provide sample code to connect to one node and if that node fails or comes down, how will my application will still keep going by connecting to other node present in cluster ?

I tried with Eclipse Paho client and HiveMQ Client. The code is mentioned below. 

Eclipse Paho -

public MqttClient getClient(final String clientId) throws MqttException {
	final MqttClient mqttClient = new MqttClient("192.168.0.1", clientId);
	final MqttConnectOptions connectOptions = new MqttConnectOptions();
	connectOptions.setCleanSession(false);
	connectOptions.setAutomaticReconnect(true);
	connectOptions.setServerURIs(new String[] { "192.168.0.1", "192.168.0.2", "192.168.0.3" });
	mqttClient.connect(connectOptions);
	return mqttClient;
}

HiveMQ -

final Mqtt5BlockingClient client = Mqtt5Client.builder().identifier(UUID.randomUUID().toString())
	.serverHost("192.168.0.1").serverPort(1883).addDisconnectedListener(context -> {
		System.out.println(context.getCause());
		context.getReconnector().reconnect(true).delay(5, TimeUnit.SECONDS);
		System.out.println(context.getReconnector().getAttempts());
		if (context.getReconnector().getAttempts() > 3) {
			context.getReconnector().transportConfig().serverHost("192.168.0.2").applyTransportConfig();
		}
	}).buildBlocking();

**Comment by jayjamba** [comment] 2019-11-29 06:37
Hi,
Did you get a chance to look into this ?

**Comment by HJianBo** [comment] 2019-12-20 07:29
Hi, @jayjamba Sorry for the late reply.

Q1): The good practice is deploying the EMQ X cluster behind an HAProxy service. And you can make a proxy strategy to implement your architecture

Q2):  Besides, the 'message.dropped' event also caused by the following situation:

1. Nobody subscribes the Topic of PUBLISH message

2. The Message Delivery Queue fulled (The client has no time to process a large number of messages )
             
```
zone.external.max_inflight  = 32
zone.external.max_mqueue_len = 1000
 ```

3. Ignore loop delivery
```
mqtt.ignore_loop_deliver = true
```

Q3): **Paho**  maybe a good choice. Your client should add a automatic reconnecting mechanism to avoid some things wrong. And you don't need connecting to other nodes if your cluster exposes a fixed port to outside by HAProxy,

**Comment by HJianBo** [comment] 2020-01-17 04:11
Hi, @jayjamba Is the problems resolved?

**Comment by jayjamba** [comment] 2020-01-17 05:31
Well, Not exactly. I am yet to try on solution that you suggested for Question no: 2.

**Comment by HJianBo** [comment] 2020-04-27 06:31
Close it first

Please let me know if you have any questions

**Closed by HJianBo** 2020-04-27 06:31 UTC
Labels: Support
