### ISSUE TITLE
EMQX Persistence Kubernetes PVC - emqx exit abnormally.

### ISSUE THREAD

**Issue by ctellechea2001** [emqx/emqx#5254] opened 2021-07-16 15:37 UTC
#### Environment

- OS: Kubernetes
- Erlang/OTP: v4.1.1
- EMQ: v4.1.1

#### Description

I am getting the same error that was reported in this post. 
(Start emqx with stateful set. When all pods of emqx are deleted at the same time, emqx pod can't be started normally any more. However, if the pod is rolling-update, it can be started normally.)
https://github.com/emqx/emqx/issues/3993

![image](https://user-images.githubusercontent.com/45426180/125972645-5093ce45-9e73-4354-b553-178bf8be402e.png)

Could you please help us to resolve the issue. It was informed that is bug and that is resolved, but the problem persists.

HJianBo commented on Jan 29
We have tagged 4.3-alpha.1, which contains the fix. The official release will probably come in 1-2 months.

![image](https://user-images.githubusercontent.com/45426180/125972456-7872a9d6-a9f1-4789-a161-5bfed9ad7ff1.png)

Thanks for your help.

**Comment by k32** [comment] 2021-07-16 20:31
Hello,

Sorry, I have trouble reading the text on the screenshots due to my bad vision. Could you please attach the logs in the test format? Also could you collect all the contents of `var/log/emqx/` directory? If you are worried about sensitive data, can you email the logs to k32 at posteo.net email address?

**Comment by ctellechea2001** [comment] 2021-07-16 21:01
@k32 Sure.

We have two pods in cluster with PVC persistence enabled to /opt/emqx/data/mnesia . If you delete both pods at the same time, you could not start the emqx anymore.

      volumeMounts:
          - mountPath: /opt/emqx/data/mnesia
            name: emqx-data

dev-emqx-0                                   1/1     Running   0          87m
dev-emqx-1                                   1/1     Running   0          86m

NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
emqx-data-dev-emqx-0   Bound    pvc-c0d570f9-6b50-4c0f-8257-4bf69adace1e   1Gi        RWO            gp2            118m
emqx-data-dev-emqx-1   Bound    pvc-fa635250-bb26-4c31-9e5a-07462f91fa5d   1Gi        RWO            gp2            117m

Cluster status: #{running_nodes =>
                      ['dev-emqx@dev-emqx-0.dev-emqx-headless.dev.svc.cluster.local',
                       'dev-emqx@dev-emqx-1.dev-emqx-headless.dev.svc.cluster.local'],
                  stopped_nodes => []}

The only way to start the emqx again is deleting the pvc and recreated them. Something is happening and was marked as bug in #3993. 

=====
===== LOGGING STARTED Thu Jul 15 13:59:03 UTC 2021
=====
Exec: /opt/emqx/erts-10.7.1/bin/erlexec -boot /opt/emqx/releases/v4.1.1/emqx -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-10.7.1/../lib -mnesia dir "/opt/emqx/data/mnesia/dev-emqx@dev-emqx-0.dev-emqx-headless.dev.svc.cluster.local" -config /opt/emqx/data/configs/app.2021.07.15.13.59.04.config -args_file /opt/emqx/data/configs/vm.2021.07.15.13.59.04.args -vm_args /opt/emqx/data/configs/vm.2021.07.15.13.59.04.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Root: /opt/emqx
/opt/emqx
2021-07-15 13:59:13.991 [info] event=server_setup_successfully driver=tcp socket="#Port<0.8>"
Starting emqx on node dev-emqx@dev-emqx-0.dev-emqx-headless.dev.svc.cluster.local
2021-07-15 13:59:13.992 [info] event=start
['2021-07-15T13:59:21Z']:emqx start
['2021-07-15T13:59:21Z']:emqx not running, waiting for recovery in 20 seconds
['2021-07-15T13:59:26Z']:emqx not running, waiting for recovery in 15 seconds
.
.
.
['2021-07-15T14:00:26Z']: emqx exit abnormally.

**Comment by k32** [comment] 2021-07-19 08:17
Thanks for the logs, I'll try to reproduce the error.

**Comment by ctellechea2001** [comment] 2021-07-19 17:14
Thanks! I will wait for your testing. Thanks!

**Comment by ctellechea2001** [comment] 2021-07-23 14:57
Any update @k32 ?

**Comment by ctellechea2001** [comment] 2021-07-23 18:08
@k32 If you need to reproduce the error you can run the following steps:

- Install minikube (https://minikube.sigs.k8s.io/docs/start/). That is to simulate the Kubernetes Cluster in a local environment.
- Run: **helm install my-emqx emqx/emqx --set service.type=NodePort --set persistence.enabled=true**
- Run **minikube stop**: that command simulate that all pods are stopped together at the same time.
- Run: **minikube start**
- After that all the pods are going to be stopped.

Exec: /opt/emqx/erts-11.1.8/bin/erlexec -noshell -noinput +Bd -boot /opt/emqx/releases/4.3.5/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir "/opt/emqx/data/mnesia/my-emqx@my-emqx-0.my-emqx-headless.emqx.svc.cluster.local" -config /opt/emqx/data/configs/app.2021.07.23.17.51.25.config -args_file /opt/emqx/data/configs/vm.2021.07.23.17.51.25.args -vm_args /opt/emqx/data/configs/vm.2021.07.23.17.51.25.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- foreground
Root: /opt/emqx
Starting emqx on node my-emqx@my-emqx-0.my-emqx-headless.emqx.svc.cluster.local
2021-07-23T17:51:58.350855+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:52:28.351871+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:52:58.352872+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:53:28.353902+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:53:58.354912+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:54:28.355920+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]

carlos@(minikube:emqx): k get pods
NAME        READY   STATUS    RESTARTS   AGE
my-emqx-0   0/1     Running   0          6m2s
my-emqx-1   0/1     Running   1          81m
my-emqx-2   0/1     Running   1          81m
carlos@(minikube:emqx):

If you want to resolve the issue you need to delete all the PVC.

carlos@(minikube:emqx): k get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
emqx-data-my-emqx-0   Bound    pvc-53b6cecd-2e91-4e50-9dee-ff8762a46047   20Mi       RWO            standard       83m
emqx-data-my-emqx-1   Bound    pvc-46dafb8b-0ba8-43c3-a37e-17481af2576c   20Mi       RWO            standard       83m
emqx-data-my-emqx-2   Bound    pvc-3e0e0e3f-e423-4b05-a6a9-ed8ddc6a1c67   20Mi       RWO            standard       83m
carlos@(minikube:emqx):

**Comment by eosantigen** [comment] 2021-07-29 07:30
I  confirm that we have the very exact same issue in a deployment in Kubernetes (AKS 1.19.7 production , and , 1.14.9 dev cluster ) . We use: **EMQX Enterprise (with valid license) version 4.2.5**

**Comment by qzhuyan** [comment] 2021-08-04 22:19
[emqx-issue-5254.tar.gz](https://github.com/emqx/emqx/files/6934683/emqx-issue-5254.tar.gz)
@eosantigen @ctellechea2001 I have patch for you, it works in my minikube
would be good if you can verify that.

BTW, sorry for late reply @k32 is on vacation.

**Comment by ctellechea2001** [comment] 2021-08-05 16:03
@qzhuyan How are you? Thanks for you support

I followed the steps that you sent us and this was the result: (Containers start and running with 1 restart) is that correct?

carlos@(minikube:emqx):~/Documents/Hipcam/Deployments/emqx/charts/emqx-issue-5254$ k get pods
NAME          READY   STATUS    RESTARTS   AGE
my-emqx-p-0   1/1     Running   1          114m
my-emqx-p-1   1/1     Running   1          114m
my-emqx-p-2   1/1     Running   1          114m
carlos@(minikube:emqx):~/Documents/Hipcam/Deployments/emqx/charts/emqx-issue-5254$ kubectl exec my-emqx-p-0 -- emqx_ctl cluster status
Cluster status: #{running_nodes =>
                      ['my-emqx-p@my-emqx-p-0.my-emqx-p-headless.emqx.svc.cluster.local',
                       'my-emqx-p@my-emqx-p-1.my-emqx-p-headless.emqx.svc.cluster.local',
                       'my-emqx-p@my-emqx-p-2.my-emqx-p-headless.emqx.svc.cluster.local'],
                  stopped_nodes => []}
carlos@(minikube:emqx):~/Documents/Hipcam/Deployments/emqx/charts/emqx-issue-5254$

**Comment by qzhuyan** [comment] 2021-08-05 17:20
@ctellechea2001 
Glad it works. Thanks for verifying it.

You can find the diffs in this PR:
https://github.com/emqx/emqx/pull/5408

Note this PR is against to our 5.0 branch. 

The PR still need some polishing to have similar test in our CI env.

I will backport it to 4.3 branch when it passed review.

**Comment by eosantigen** [comment] 2021-08-09 12:25
Hi dear committers. 

Just a question regarding the versioning of the Enterprise Docker image and the free version, related to this patch.

We  noticed that in DockerHub, for the Enterprise edition, only up to 4.3.2 tag is available , whereas this patch here has been applied to version 4.3.5. _The question is:_  if we use the Enterprise edition (with applied license) , will this patch be available to 4.3.2 or 4.3.5, or both ?

_(We have started testing now, with both images deployed along with this patch, and will let you know how it goes)_

Thanks.

**Comment by qzhuyan** [comment] 2021-08-10 08:17
@eosantigen the patch should work for Enterprise as well.

**Comment by ctellechea2001** [comment] 2021-08-23 13:26
@qzhuyan Do you know when will the changes be in a new version 4.3.6 or something ? It is to avoid to manual process in kuberentes. Thanks!!!

**Comment by qzhuyan** [comment] 2021-08-23 14:10
We miss the release window of opensource 4.3.7 so it will be released in the next release opensource 4.3.8

**Comment by ctellechea2001** [comment] 2021-08-31 14:13
@qzhuyan how are you? Do you have an estimated time for release 4.3.8? Thanks for you support.

**Comment by eosantigen** [comment] 2021-09-02 11:18
Hi All.

_(Please Note: No one here is my colleague - we are not from the same company)_

I have finally, made the test with this patch, following the exact steps mentioned above .

# TEST CASES

1. Restart the node . The pods should be restarted as normal and be up and running again (the emqx service should start) afterwards, automatically.
2. Uninstall deployment via Helm without deleting the storage and redeploy it again with identical chart values. Emqx service should start.

- All done with the patch in the storage.
- Option: `recreatePods: False` (default)
- Tests done with the following versions:

4.3.2 - EE
4.3.3 - EE
4.3.5 - NON-EE
4.3.7 - NON-EE

## 4.3.2 - EE

### Test Case 1: FAILED

### Test Case 2: FAILED

Pods were not up and running, with logs stuck at: 

```
2021-09-02T09:53:27.921179+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_listeners_state,emqx_resource,emqx_conf_b,emqx_conf_a,mqtt_app,emqx_conf_info,emqx_rule,emqx_modules,emqx_banned,emqx_schema,mqtt_admin]
```

## 4.3.3 - EE

### Test Case 1: FAILED

Pods were not up and running, with logs stuck at for hours: 

```
Starting emqx on node emqx-ee-433-latest@emqx-ee-433-latest-2.emqx-ee-433-latest-headless.emqx.svc.cluster.local

dets: file "/opt/emqx/data/mnesia/emqx-ee-433-latest@emqx-ee-433-latest-2.emqx-ee-433-latest-headless.emqx.svc.cluster.local/emqx_collect.DAT" not properly closed, repairing ...

2021-09-02T10:02:47.382587+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_listeners_state,emqx_resource,emqx_conf_b,emqx_conf_a,mqtt_app,emqx_conf_info,emqx_rule,emqx_modules,emqx_banned,emqx_schema,mqtt_admin]

```

Tried to even delete the stuck pods: only one got recreated and was stuck there with the same warning as above.

### Test Case 2: Not done because 1 failed.

## 4.3.7

### Test Case 1: FAILED

Again, the log output of not-ready pods remained stuck for many hours at the following:

```
Starting emqx on node emqx-ee-433-latest@emqx-ee-433-latest-2.emqx-ee-433-latest-headless.emqx.svc.cluster.local

dets: file "/opt/emqx/data/mnesia/emqx-ee-433-latest@emqx-ee-433-latest-2.emqx-ee-433-latest-headless.emqx.svc.cluster.local/emqx_collect.DAT" not properly closed, repairing ...

2021-09-02T10:02:47.382587+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_listeners_state,emqx_resource,emqx_conf_b,emqx_conf_a,mqtt_app,emqx_conf_info,emqx_rule,emqx_modules,emqx_banned,emqx_schema,mqtt_admin]
```
### Test Case 2: Not done because 1 failed

## 4.3.5

### Τest Case 1: FAILED
### Test Case 2: FAILED

#### Final attempt
Tried to even delete the stuck pods: only one got recreated and was stuck there with the same warning as above.

---
Thanks - Kind Regards

**Comment by qzhuyan** [comment] 2021-09-02 11:57
@eosantigen thanks for the updates.

which helm chart file do you use? could you share it?

**Comment by eosantigen** [comment] 2021-09-02 12:32
Thanks for the reply

I have already mentioned that it has been tested with 4.3.3 EE .

The charts have been  taken out of here, out of  the box:

https://github.com/emqx/emqx/tree/v4.3.3/deploy/charts/emqx
https://github.com/emqx/emqx/tree/v4.3.7/deploy/charts/emqx

I have deployed both emqx-ee and emqx versions .

All stuck with the same logs:

```
Starting emqx on node emqx-ee-433-latest@emqx-ee-433-latest-2.emqx-ee-433-latest-headless.emqx.svc.cluster.local

dets: file "/opt/emqx/data/mnesia/emqx-ee-433-latest@emqx-ee-433-latest-2.emqx-ee-433-latest-headless.emqx.svc.cluster.local/emqx_collect.DAT" not properly closed, repairing ...

2021-09-02T10:02:47.382587+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_listeners_state,emqx_resource,emqx_conf_b,emqx_conf_a,mqtt_app,emqx_conf_info,emqx_rule,emqx_modules,emqx_banned,emqx_schema,mqtt_admin]
```

Thanks.

**Comment by qzhuyan** [comment] 2021-09-02 12:46
Apologies to make you confusion  @eosantigen 

|https://github.com/emqx/emqx/tree/v4.3.3/deploy/charts/emqx
|https://github.com/emqx/emqx/tree/v4.3.7/deploy/charts/emqx

They are all opensource versions that miss one little change in the helm chart.

As mentioned in https://github.com/emqx/emqx/issues/5254#issuecomment-893012673, the helm chart need a patch as well.

See the changes here:

https://github.com/emqx/emqx/pull/5428/files

Could you verify the stateful sets `podManagementPolicy`is set to `parallel` before your test?

**Comment by eosantigen** [comment] 2021-09-02 13:23
Yes, exactly , I verify that  `podManagementPolicy: Parallel` was _already in the chart_  - because, except for these two links  , I had also used the updated chart you had attached above in your comment in order to test 4.3.3 version.
And , indeed, the pods were launched in "parallel" , all 3 at the same time.

```

NAME                        READY   STATUS    RESTARTS   AGE   IP            NODE            
emqx-ee-0                   0/1     Running   1          84m   10.42.3.158   dev-k8s-worker-0   
emqx-ee-1                   0/1     Running   1          84m   10.42.3.156   dev-k8s-worker-0   
emqx-ee-2                   0/1     Running   1          84m   10.42.3.153   dev-k8s-worker-0  
```

The logs were:
```
Starting emqx on node emqx-ee-433-latest@emqx-ee-433-latest-2.emqx-ee-433-latest-headless.emqx.svc.cluster.local

dets: file "/opt/emqx/data/mnesia/emqx-ee-433-latest@emqx-ee-433-latest-2.emqx-ee-433-latest-headless.emqx.svc.cluster.local/emqx_collect.DAT" not properly closed, repairing ...

2021-09-02T10:02:47.382587+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_listeners_state,emqx_resource,emqx_conf_b,emqx_conf_a,mqtt_app,emqx_conf_info,emqx_rule,emqx_modules,emqx_banned,emqx_schema,mqtt_admin]
.............(same for half-hour )
```
But how much time does it need to do the repair? I waited about half-hour... then i gave up.

**Comment by qzhuyan** [comment] 2021-09-02 13:49
@eosantigen It is not the issue of reparing.

Could you confirm you are using docker image `emqx-ee:4.3.3` ?

**Comment by eosantigen** [comment] 2021-09-02 13:53
Yes, the image is emqx-ee:4.3.3

![Screenshot from 2021-09-02 16-14-16](https://user-images.githubusercontent.com/11250505/131856189-ee055a76-43e7-410a-bedd-be026931c4be.png)

**Comment by qzhuyan** [comment] 2021-09-02 14:07
Could you write down what are the steps to reproduce the issue? The two testcases slogan to me is a bit vague.
Also have you tried with a empty new PVC? I wonder if the data is huge that need more time to get synced.

**Comment by qzhuyan** [comment] 2021-09-02 14:45
| 4. Test case : Node restart
Do you mean you restart the k8s host node? So all three pods were deployed on the same k8s host?

| Did a clean install - from scratch : helm install -n emqx emqx-ee . (no existing storage at this point)
I don't see `--set persistence.enabled=true` is specified, meaning you are not using any persietent storage?

**Comment by eosantigen** [comment] 2021-09-02 14:50
exactly, all three pods are on the same host. Yes, it was restarted .

the persistentStorage has been inside values.yaml
```
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 20Mi
```

```
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
emqx-data-emqx-ee-0   Bound    pvc-51544ec2-0bf3-11ec-96e7-92570905be1e   20Mi       RWO            nfs-client     70m
emqx-data-emqx-ee-1   Bound    pvc-515c0442-0bf3-11ec-96e7-92570905be1e   20Mi       RWO            nfs-client     70m
emqx-data-emqx-ee-2   Bound    pvc-51644080-0bf3-11ec-96e7-92570905be1e   20Mi       RWO            nfs-client     70m
```

**Comment by qzhuyan** [comment] 2021-09-02 16:52
@eosantigen thanks for the info, I managed to reproduced the issue with microk8s by doing

```
# microk8s stop
then
# microk8s start
```
that should suffient simulate your step
| 4. Test case : Node restart


However it is a just a little problem in helm chart and 
I have a solution here:

https://github.com/qzhuyan/emqx/commit/cd43bb42a7266f7a7b6d293dbe44c1277423a9e4

Would you mind test this solution in your env?

**Comment by eosantigen** [comment] 2021-09-02 17:42
Thanks a lot .

Will try it tomorrow first thing in the morning and will let you know in detail.

**Comment by eosantigen** [comment] 2021-09-03 07:35
Hi  @qzhuyan

I have applied this directive you mentioned, and tested again  same way, and I confirm this has solved the issue. 

It all restarts/runs perfectly!

Thank you for the help...

Kind Regards

**Closed** 2021-09-03 07:44 UTC
Labels: BUG, Support, backlog

**Comment by ctellechea2001** [comment] 2021-09-07 16:57
@qzhuyan How are you? Can we test in the release 4.3.8? I checked that was released 2 days ago.

https://github.com/emqx/emqx/releases/tag/v4.3.8

**Comment by qzhuyan** [comment] 2021-09-07 17:13
> @qzhuyan How are you? Can we test in the release 4.3.8? I checked that was released 2 days ago.
> 
> 
> 
> https://github.com/emqx/emqx/releases/tag/v4.3.8
> 
> 

@ctellechea2001 I am very well, thank you and hope you are well too! yes all fixs are included, go ahead and test it, good luck!
