### ISSUE TITLE
/subscriptions REST接口，_match_topic 参数无效

### ISSUE THREAD

**Issue by woniudiancang** [emqx/emqx#11765] opened 2023-10-16 01:48 UTC
### What happened?

https://docs.emqx.com/zh/cloud/latest/api/subscriptions_v5.html

/subscriptions REST接口，_match_topic 参数无效

传不传这个参数，返回的结果是一样的，传了一个不存在的主题名称，接口还是返回了所有的订阅信息

### What did you expect to happen?

比如 _match_topic  传了 abc， 不应该返回  ggg 的主题的记录

### How can we reproduce it (as minimally and precisely as possible)?

_match_topic  传了 abc， 返回了所有主题的记录，该参数未进行筛选处理

### EMQX version

最新版本

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by woniudiancang** [comment] 2023-10-16 01:54
用的网站上的 serverLess 版本，接口请求，具体看 postMan 发送的记录，或者 CURL：

curl -i -X GET
-H “Authorization: XXXXXXXXXXXX”
‘https://y13ae666.ala.cn-hangzhou.emqxsl.cn:8443/api/v5/subscriptions?_match_topic=abc’

**Comment by woniudiancang** [comment] 2023-10-16 01:55
![微信截图_20231016095237](https://github.com/emqx/emqx/assets/68815831/6b18d5a7-3e8a-4b82-bab7-f4cc59738f98)

**Comment by thalesmg** [comment] 2023-10-16 19:56
Hi @woniudiancang .

I can't read Chinese, but I think I may have inferred your problem.

Attempting to use `_match_topic` as a query parameters indeed returns all subscriptions because that parameter is not valid.  Since there are effectively no filters in the query, all results are returning.  The correct parameter is `match_topic`.

Ex:

```sh
# wrong parameter
curl 'http://localhost:18083/api/v5/subscriptions?limit=20&page=1&_match_topic=zzz' #...
{
  "data": [
    {
      "clientid": "myclient",
      "nl": 0,
      "node": "emqx@127.0.0.1",
      "qos": 1,
      "rap": 0,
      "rh": 0,
      "topic": "abc"
    },
    {
      "clientid": "myclient",
      "nl": 0,
      "node": "emqx@127.0.0.1",
      "qos": 1,
      "rap": 0,
      "rh": 0,
      "topic": "zzz"
    }
  ],
  "meta": {
    "count": 2,
    "hasnext": false,
    "limit": 20,
    "page": 1
  }
}

# correct parameter
curl 'http://localhost:18083/api/v5/subscriptions?limit=20&page=1&match_topic=zzz' #...
{
  "data": [
    {
      "clientid": "myclient",
      "nl": 0,
      "node": "emqx@127.0.0.1",
      "qos": 1,
      "rap": 0,
      "rh": 0,
      "topic": "zzz"
    }
  ],
  "meta": {
    "hasnext": false,
    "limit": 20,
    "page": 1
  }
}
```

**Comment by thalesmg** [comment] 2023-10-16 19:57
I'll close this since this is not a bug.  Please feel free to open new issues if you encounter new problems.

**Closed by thalesmg** 2023-10-16 19:57 UTC
Labels: Support
