### ISSUE TITLE
new node cannot join cluster

### ISSUE THREAD

**Issue by seqwait** [emqx/emqx#5135] opened 2021-06-29 12:31 UTC
1.  version: 4.0
2. docker 19.03.8
cluster:
Cluster status: #{running_nodes =>
                      ['emqx1@172.17.110.196','emqx2@172.17.110.203',
                       'emqx3@172.17.110.204'],
                  stopped_nodes => []}

after join node4 error:

['2021-06-29T11:51:28Z']:waiting emqx
2021-06-29 11:51:28.754 [error] Mnesia('emqx4@172.17.110.215'): ** ERROR ** Mnesia on 'emqx4@172.17.110.215' could not connect to node(s) ['emqx3@172.17.110.204']

**Comment by k32** [comment] 2021-06-29 15:31
Hello.
Is this issue a duplicate of https://github.com/emqx/emqx/issues/5133 ?
Can you check network connectivity between the nodes and setup the firewall openings according to the instruction: https://docs.emqx.io/en/broker/v4.3/advanced/cluster.html#firewall-settings

**Closed** 2021-06-30 04:27 UTC
Labels: Support
