### ISSUE TITLE
etcd discovery failed

### ISSUE THREAD

**Issue by elysian-gc** [emqx/emqx#10061] opened 2023-03-03 02:39 UTC
### What happened?
```
2023-03-03T02:30:59.905157+00:00 [warning] ekka_cluster_etcd failed to connect [etcd.xxxx:2379] by <GRPC Unhealthy> {gun_stream_error,{closed,"The connection was lost."}}, mfa: eetcd_conn:exit_conn/6 line: 251
2023-03-03T02:30:59.905343+00:00 [error] Failed to connect ETCD: {"etcd.xxxx",2379} by {gun_stream_error,{closed,"The connection was lost."}} mfa: eetcd_conn:fold_connect/5 line: 205
2023-03-03T02:30:59.905760+00:00 [error] Supervisor: {local,ekka_cluster_sup}. Context: start_error. Reason: {{badmatch,{error,[{{"etcd.xxx",2379},{gun_stream_error,{closed,"The connection was lost."}}}]}},[{ekka_cluster_etcd,init,1,[{file,"ekka_cluster_etcd.erl"},{line,348}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}. Offender: id=ekka_cluster_etcd,pid=undefined.
2023-03-03T02:30:59.905573+00:00 [error] crasher: initial call: ekka_cluster_etcd:init/1, pid: <0.2002.0>, registered_name: [], error: {{badmatch,{error,[{{"etcd.xxxx",2379},{gun_stream_error,{closed,"The connection was lost."}}}]}},[{ekka_cluster_etcd,init,1,[{file,"ekka_cluster_etcd.erl"},{line,348}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [ekka_cluster_sup,ekka_sup,<0.1999.0>], message_queue_len: 0, messages: [], links: [<0.2001.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 28, reductions: 326; neighbours:
2023-03-03T02:30:59.906137+00:00 [error] Supervisor: {local,ekka_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,ekka_cluster_etcd,{{badmatch,{error,[{{"etcd.xxxx",2379},{gun_stream_error,{closed,"The connection was lost."}}}]}},[{ekka_cluster_etcd,init,1,[{file,"ekka_cluster_etcd.erl"},{line,348}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}}. Offender: id=ekka_cluster_sup,pid=undefined.
2023-03-03T02:30:59.906472+00:00 [error] crasher: initial call: application_master:init/4, pid: <0.1998.0>, registered_name: [], exit: {{{shutdown,{failed_to_start_child,ekka_cluster_sup,{shutdown,{failed_to_start_child,ekka_cluster_etcd,{{badmatch,{error,[{{"etcd.xxxxx",2379},{gun_stream_error,{closed,"The connection was lost."}}}]}},[{ekka_cluster_etcd,init,1,[{file,"ekka_cluster_etcd.erl"},{line,348}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}}}},{ekka_app,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.1997.0>], message_queue_len: 1, messages: [{'EXIT',<0.1999.0>,normal}], links: [<0.1997.0>,<0.1741.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 28, reductions: 223; neighbours:
2023-03-03T02:30:59.912846+00:00 [error] crasher: initial call: application_master:init/4, pid: <0.1985.0>, registered_name: [], exit: {{bad_return,{{emqx_machine_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{ekka,{{shutdown,{failed_to_start_child,ekka_cluster_sup,{shutdown,{failed_to_start_child,ekka_cluster_etcd,{{badmatch,{error,[{{"etcd.xxxxx",2379},{gun_stream_error,{closed,"The connection was lost."}}}]}},[{ekka_cluster_etcd,init,1,[{file,"ekka_cluster_etcd.erl"},{line,348}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}}}},{ekka_app,start,[normal,[]]}}}}},[{ekka,start,0,[{file,"ekka.erl"},{line,97}]},{emqx_machine,start,0,[{file,"emqx_machine.erl"},{line,44}]},{emqx_machine_app,start,2,[{file,"emqx_machine_app.erl"},{line,27}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.1984.0>], message_queue_len: 1, messages: [{'EXIT',<0.1986.0>,normal}], links: [<0.1984.0>,<0.1741.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 28, reductions: 180; neighbours:
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```
### What did you expect to happen?

emqx running

### How can we reproduce it (as minimally and precisely as possible)?

1. run etcd with ssl
2. configure emqx.conf
```
cluster {
  name = "emqx_v5_cluster"
  discovery_strategy = "etcd"
  etcd {
    server = "https://etcd.xxxxx:2379"
    prefix = "emqx-cluster"
    ssl {
      keyfile = "/data/etcdssl/etcd-key.pem"
      cacertfile = "/data/etcdssl/ca.pem"
      certfile = "/data/etcdssl/etcd.pem"
    }
  }
}
```
3. start emqx

### EMQX version

v5.0.19

### OS version

5.10.167-147.601.amzn2.aarch64

### Log files

<details>

</details>

**Comment by ieQu1** [comment] 2023-03-03 08:39
Hi,

Thanks the report, I can confirm the bug. ETCD server tries to establish connection in the init callback, meaning any problem there will lead to aborted startup:

https://github.com/emqx/ekka/blob/master/src/ekka_cluster_etcd.erl#L348

**Comment by elysian-gc** [comment] 2023-03-03 08:45
@ieQu1 thanks your reply , so any configure error ?  sorry I cannot understand erlang,

**Comment by ieQu1** [comment] 2023-03-03 08:56
It could be a configuration error (I cannot check this without knowing the service endpoints), but also a programming error on our side: it's not great that the node startup is aborted because ETCD is down or misconfigured. I would prefer if EMQX retries connection to ETCD instead.

**Comment by elysian-gc** [comment] 2023-03-03 09:04
when I use `etcdcl --endpoint=https://xxxxx:2379 ` or `curl https://xxxxx:2379` command , which can get result.
can you  try this problem, please, it important for me

**Comment by ieQu1** [comment] 2023-03-03 09:22
As for your immediate issue, I think you may want to modify ssl configuration like this:

```
    ssl {
      keyfile = "/data/etcdssl/etcd-key.pem"
      cacertfile = "/data/etcdssl/ca.pem"
      certfile = "/data/etcdssl/etcd.pem"
      enable = true
    }
```

**Comment by ieQu1** [comment] 2023-03-03 12:13
Great. After a discussion, we that the current "fail fast if etcd is unreachable" behavior is correct, so I'm closing the issue.

**Closed by ieQu1** 2023-03-03 12:13 UTC
Labels: BUG
