### ISSUE TITLE
Kubernetes Cluster Deployment with PVC - Readiness probe fails

### ISSUE THREAD

**Issue by Fidenz-Lasithh** [emqx/emqx#5483] opened 2021-08-13 06:39 UTC
**Environment**:
Deployed on a Kubernetes cluster on Azure via Helm chart
- EMQ X version (e.g. `emqx_ctl status`):  4.3.6
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.7
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
- Kernel (e.g. `uname -a`): Linux emqx-0 5.4.0-1055-azure 57~18.04.1-Ubuntu SMP Fri Jul 16 19:40:19 UTC 2021 x86_64 Linux
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
When cluster restarts some pods may not come online.  saying,
Readiness probe failed: Get http://10.240.0.219:8081/status: dial tcp 10.240.0.219:8081: connect: connection refused

**How to reproduce it (as minimally and precisely as possible)**:
Happens when the cluster restarts. Should delete and recreate the PVC to get all the pods back online

**Anything else we need to know?**:
Logs- 
cluster.discovery = "k8s"
cluster.k8s.address_type = "hostname"
cluster.k8s.apiserver = "https://kubernetes.default.svc:443"
cluster.k8s.app_name = "emqx"
cluster.k8s.namespace = "emqx-mqtt"
cluster.k8s.service_name = "emqx-headless"
cluster.k8s.suffix = "svc.cluster.local"
listener.ssl.external.acceptors = "32"
listener.ssl.external.max_connections = "102400"
listener.tcp.external.acceptors = "64"
listener.tcp.external.max_connections = "1024000"
listener.ws.external.acceptors = "16"
listener.ws.external.max_connections = "102400"
listener.wss.external.acceptors = "16"
listener.wss.external.max_connections = "102400"
log.to = "console"
node.max_ets_tables = "2097152"
node.max_ports = "1048576"
node.name = "emqx@emqx-0.emqx-headless.emqx-mqtt.svc.cluster.local"
node.process_limit = "2097152"
rpc.port_discovery = "manual"
Exec: /opt/emqx/erts-11.1.8/bin/erlexec -noshell -noinput +Bd -boot /opt/emqx/releases/4.3.6/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir "/opt/emqx/data/mnesia/emqx@emqx-0.emqx-headless.emqx-mqtt.svc.cluster.local" -config /opt/emqx/data/configs/app.2021.08.13.05.35.21.config -args_file /opt/emqx/data/configs/vm.2021.08.13.05.35.21.args -vm_args /opt/emqx/data/configs/vm.2021.08.13.05.35.21.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- foreground
Root: /opt/emqx
Starting emqx on node emqx@emqx-0.emqx-headless.emqx-mqtt.svc.cluster.local

***Then, the line below is printed repeatedly.***
ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]

**Comment by k32** [comment] 2021-08-13 08:59
Duplicate of https://github.com/emqx/emqx/issues/4863

**Closed by k32** 2021-08-13 08:59 UTC
Labels: Support
