### ISSUE TITLE
exception error: no case clause matching {error,closed} (v4.0.2)

### ISSUE THREAD

**Issue by arroyoh** [emqx/emqx#3436] opened 2020-05-06 16:15 UTC
**Environment**:

3 Node Kubernetes cluster

- EMQ X version: **4.0.2** (Docker image emqx/emqx:4.0.2)
- OS:
         NAME="Alpine Linux"
         ID=alpine
         VERSION_ID=3.10.4

- Kernel: Linux connection-emqx-0 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 Linux

**Description**:

```
2020-05-06 15:44:23.375 [error] <<"8628043009">>@100.102.53.192:58962   crasher:
    initial call: cowboy_clear:connection_process/4
    pid: <0.17853.8>
    registered_name: []
    exception error: no case clause matching {error,closed}
      in function  cowboy_websocket:websocket_send_close/2 (/emqx_rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl, line 640)
      in call from cowboy_websocket:websocket_close/3 (/emqx_rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl, line 623)
    ancestors: [<0.2154.0>,<0.2153.0>,ranch_sup,<0.1945.0>]
    message_queue_len: 1
    messages: [{tcp_closed,#Port<0.154073>}]
    links: [<0.2154.0>]
    dictionary: [{guid,{1588776597686678,38474451273149,4}},
                  {incoming_bytes,2369},
                  {outgoing_bytes,565},
                  {'$logger_metadata$',
                      #{clientid => <<"8628043009">>,
                        peername => "100.102.53.192:58962"}},
                  {outgoing_pubs,3},
                  {recv_pkt,5},
                  {recv_cnt,204},
                  {acl_cache_size,1},
                  {acl_keys_q,
                      {[{subscribe,
                            <<"orders/events/e115d45a-fe73-4966-94c5-c22dd4d32a56">>}],
                       []}},
                  {{subscribe,
                       <<"orders/events/e115d45a-fe73-4966-94c5-c22dd4d32a56">>},
                   {allow,1588773897550}},
                  {send_pkt,199},
                  {send_cnt,199},
                  {send_oct,565},
                  {rand_seed,
                      {#{bits => 58,jump => #Fun<rand.13.8986388>,
                         next => #Fun<rand.10.8986388>,type => exsss,
                         uniform => #Fun<rand.11.8986388>,
                         uniform_n => #Fun<rand.12.8986388>},
                       [51780116134882405|174145305067248777]}},
                  {recv_oct,2369},
                  {send_msg,3}]
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 169705
  neighbours:

2020-05-06 15:44:23.376 [error] Ranch listener 'mqtt:ws:8083' had connection process started with cowboy_clear:start_link/4 at <0.17853.8> exit with reason: {{case_clause,{error,closed}},[{cowboy_websocket,websocket_send_close,2,[{file,"/emqx_rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl"},{line,640}]},{cowboy_websocket,websocket_close,3,[{file,"/emqx_rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl"},{line,623}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
```

**Comment by arroyoh** [comment] 2020-05-06 16:35
I can see that this issue might be related
https://github.com/emqx/emqx/issues/3268

Is it fixed on version 4.0.4? I'll try it out and close this if it is fixed

**Comment by arroyoh** [comment] 2020-05-06 20:28
[UPDATE] v4.0.6 (Docker image emqx/emqx:4.0.6)

Service is no loger getting the exception log as before, so this is probably fixed.

We're still getting this line though:

```
2020-05-06 19:54:00.722 [error] Ranch listener 'mqtt:ws:8083' had connection process started with cowboy_clear:start_link/4 at <0.27766.0> exit with reason: {{case_clause,{error,closed}},[{cowboy_websocket,websocket_send_close,2,[{file,"/emqx_rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl"},{line,640}]},{cowboy_websocket,websocket_close,3,[{file,"/emqx_rel/_build/emqx/lib/cowboy/src/cowboy_websocket.erl"},{line,623}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
```

Is it related? is it something we should worry about?

In our use case we are depending on the `on_session_terminated` hook to detect **offline** events. The exception was aparently affecting the execution of the hook.

**Comment by HJianBo** [comment] 2020-05-08 07:23
There logs it seems somethings closed here. Could you give some steps to help me reproduce it?

**Comment by HJianBo** [comment] 2020-07-13 01:55
Close it due to expiration.

If you have more information, plz reopen it

**Closed by HJianBo** 2020-07-13 01:55 UTC
Labels: Support
