### ISSUE TITLE
[3.2.3/4.0] subscriptions with wildcards produces many errors on higher load

### ISSUE THREAD

**Issue by gbrehmer** [emqx/emqx#2851] opened 2019-08-28 16:05 UTC
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 21.3
- EMQ: 3.2.3 / 4.0.1 (see comments below)

#### Description

After emqx upgrade the broker generates a lot of timeouts and error messages. Devices have to reconnect a lot of times and cannot subscribe to any topic. Only a few messages in the beginning are received/sent out successful. Then timeout count increases very fast and load of the system was high (but not over limits)
OUTDATED (on our dev system all is working fine. We had tested the dev environment with your benchmark tool successfully.
UPDATE: With the hint to the underlying problem from the mentioned other bug, we can now reproduce the problem with your benchmark client (our previous benchmarks only covers publish from client and subscriptions in the backend). with 600 clients (300 publishing, 300 subscribing, 300msg/s) all is working fine. with 1200 clients ( 600 publishing, 600 subscribing, still 300 msg/s) the error rate was very high. If we reduce the topic levels (still with wildcard) we could handle 2400 clients w/o errors, with 4800 the problem comes back.

example of errors:

```
2019-08-28 17:42:30.388 [error] supervisor: 'esockd_connection_sup - <0.2582.0>'
    errorContext: connection_shutdown
    reason: {timeout,
                {gen_server,call,
                    [<0.2502.0>,
                     {subscribe,
                         <<"home/topic/+/status">>}]}}
    offender: [{pid,<0.30652.8>},
               {name,connection},
               {mfargs,{emqx_channel,start_link,
                                     [[{deflate_options,[]},
                                       {max_conn_rate,10000},
                                       {active_n,100},
                                       {zone,external}]]}}]
``` 

```
2019-08-28 17:42:30.544 [error] XXX ** Generic server <0.431.9> terminating
** Last message in was {'$gen_cast',
                           {subscribe,<0.413.9>,
                               {2,undefined,
                                [{<<"home/topic/job/+/status">>,
                                  #{nl => 0,qos => 1,rap => 0,rc => 1,
                                    rh => 0}}]}}}
** When Server state == {state,external,30000,true,
                            #Fun<emqx_session.1.105215689>,
                            <<"XXX">>,
                            <<"XXX">>,<0.413.9>,undefined,1,
                            #{},
                            {emqx_inflight,100,{0,nil}},
                            undefined,
                            {mqueue,true,1000,0,0,none,infinity,
                                {queue,[],[],0}},
                            #{},undefined,0,undefined,undefined,
                            {emqx_gc,
                                #{cnt => {1000,1000},
                                  oct => {1048576,1048576}}},
                            {1567,6945,129127},
                            {message,
                                <<0,5,145,47,60,82,75,193,18,78,9,0,1,157,0,0>>,
                                1,<<"XXX">>,
                                #{dup => false,retain => true},
                                #{username => <<"XXX">>},
                                <<"home/topic/status">>,
                                <<"offline">>,
                                {1567,6945,70045}},
                            undefined}
** Reason for termination ==
** {{timeout,{gen_server,call,
                         [<0.2502.0>,
                          {subscribe,<<"home/topic/job/+/status">>}]}},
    [{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},
     {emqx_session,do_subscribe,5,
                   [{file,"/builds/folder/emqx-rel/_build/emqx-pkg/lib/emqx/src/emqx_session.erl"},
                    {line,1135}]},
     {emqx_session,'-handle_cast/2-fun-0-',4,
                   [{file,"/builds/folder/emqx-rel/_build/emqx-pkg/lib/emqx/src/emqx_session.erl"},
                    {line,471}]},
     {emqx_session,handle_cast,2,
                   [{file,"/builds/folder/emqx-rel/_build/emqx-pkg/lib/emqx/src/emqx_session.erl"},
                    {line,468}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
``` 

config:
```
cluster.name = emqx-cluster
cluster.discovery = manual
cluster.autoheal = on
cluster.autoclean = 5m
node.name = emqx@host1
node.cookie = emqxsecretcookie
node.data_dir = data
node.async_threads = 32
node.process_limit = 2048000
node.max_ports = 1024000
node.dist_buffer_size = 32MB
node.max_ets_tables = 256000
node.fullsweep_after = 1000
node.crash_dump = /var/log/emqx/crash.dump
node.proto_dist = inet_tcp
node.dist_net_ticktime = 60
node.dist_listen_min = 6369
node.dist_listen_max = 6379
log.to = file
log.level = warning
log.dir = /var/log/emqx
log.file = emqx.log
log.rotation.size = 10MB
log.rotation.count = 10
log.error.file = error.log
allow_anonymous = false
acl_nomatch = allow
acl_file = /etc/emqx/acl.conf
enable_acl_cache = on
acl_cache_max_size = 32
acl_cache_ttl = 1m
acl_deny_action = ignore
mqtt.max_clientid_len = 65535
mqtt.max_packet_size = 1MB
mqtt.max_topic_levels = 0
mqtt.max_qos_allowed = 2
mqtt.max_topic_alias = 0
mqtt.retain_available = true
mqtt.wildcard_subscription = true
mqtt.shared_subscription = true
mqtt.ignore_loop_deliver = false
zone.external.idle_timeout = 30s
zone.external.enable_acl = on
zone.external.enable_ban = on
zone.external.enable_stats = on
zone.external.acl_deny_action = ignore
zone.external.force_gc_policy = 1000|1MB
zone.external.keepalive_backoff = 0.75
zone.external.max_subscriptions = 0
zone.external.upgrade_qos = off
zone.external.max_inflight = 100
zone.external.retry_interval = 20s
zone.external.max_awaiting_rel = 1000
zone.external.await_rel_timeout = 300s
zone.external.session_expiry_interval = 2h
zone.external.max_mqueue_len = 1000
zone.external.mqueue_priorities = none
zone.external.mqueue_default_priority = highest
zone.external.mqueue_store_qos0 = true
zone.external.enable_flapping_detect = off
zone.external.flapping_threshold = 10, 1m
zone.external.flapping_banned_expiry_interval = 1h
zone.external.use_username_as_clientid = false
zone.external.ignore_loop_deliver = false
zone.internal.allow_anonymous = true
zone.internal.enable_stats = on
zone.internal.enable_acl = off
zone.internal.acl_deny_action = ignore
zone.internal.max_subscriptions = 0
zone.internal.max_inflight = 100
zone.internal.max_awaiting_rel = 1000
zone.internal.max_mqueue_len = 1000
zone.internal.mqueue_store_qos0 = true
zone.internal.enable_flapping_detect = off
zone.internal.flapping_threshold = 10, 1m
zone.internal.flapping_banned_expiry_interval = 1h
zone.internal.use_username_as_clientid = false
zone.internal.ignore_loop_deliver = false
listener.tcp.external = 0.0.0.0:31883
listener.tcp.external.acceptors = 8
listener.tcp.external.max_connections = 1024000
listener.tcp.external.max_conn_rate = 10000
listener.tcp.external.active_n = 100
listener.tcp.external.zone = external
listener.tcp.external.access.1 = allow all
listener.tcp.external.backlog = 1024
listener.tcp.external.send_timeout = 15s
listener.tcp.external.send_timeout_close = on
listener.tcp.external.nodelay = true
listener.tcp.external.reuseaddr = true
listener.tcp.internal = 127.0.0.1:11883
listener.tcp.internal.acceptors = 4
listener.tcp.internal.max_connections = 1024000
listener.tcp.internal.max_conn_rate = 1000
listener.tcp.internal.active_n = 1000
listener.tcp.internal.zone = internal
listener.tcp.internal.backlog = 512
listener.tcp.internal.send_timeout = 5s
listener.tcp.internal.send_timeout_close = on
listener.tcp.internal.nodelay = false
listener.tcp.internal.reuseaddr = true
listener.ws.external = 31083
listener.ws.external.mqtt_path = /mqtt
listener.ws.external.acceptors = 4
listener.ws.external.max_connections = 102400
listener.ws.external.max_conn_rate = 10000
listener.ws.external.zone = external
listener.ws.external.access.1 = allow all
listener.ws.external.verify_protocol_header = on
listener.ws.external.backlog = 1024
listener.ws.external.send_timeout = 15s
listener.ws.external.send_timeout_close = on
listener.ws.external.nodelay = true
broker.enable_session_registry = on
broker.session_locking_strategy = quorum
broker.shared_subscription_strategy = random
broker.shared_dispatch_ack_enabled = false
broker.route_batch_clean = off
sysmon.long_gc = 0
sysmon.long_schedule = 240ms
sysmon.large_heap = 8MB
sysmon.busy_port = false
sysmon.busy_dist_port = true
os_mon.cpu_check_interval = 60s
os_mon.cpu_high_watermark = 80%
os_mon.cpu_low_watermark = 60%
os_mon.mem_check_interval = 60s
os_mon.sysmem_high_watermark = 70%
module.presence = on
module.presence.qos = 1
module.subscription = off
module.rewrite = off
plugins.etc_dir = /etc/emqx/plugins/
plugins.loaded_file = /var/lib/emqx/loaded_plugins
plugins.expand_plugins_dir = plugins/
broker.sys_interval = 1m
broker.sys_heartbeat = 30s
os_mon.procmem_high_watermark = 5%
vm_mon.check_interval = 30s
vm_mon.process_high_watermark = 80%
vm_mon.process_low_watermark = 60%
rpc.socket_keepalive_idle = 900s
cluster.static.seeds = emqx@host1,emqx@host2
zone.external.force_shutdown_policy = 100000|1200MB
```

host env:
2 nodes (each 4 CPUs, 8GB RAM), 5000 devices (ws or tcp, uses wildcard subscriptions for a sub-topic tree), 2 backend nodes fro message processing with 12 connections each, uses wildcard subscriptions for a "device-topic-shard" each, haproxy as loadbalancer

**Comment by gbrehmer** [comment] 2019-08-28 16:48
It seems that #2561 mentioned a similar behavior. our clients are connecting to the broker and right after that subscribe to several topics:
home/<number>/<number>/<username>/job/+/status
home/<number>/<number>/<username>/error/service

We are currently not able to change this behavior in the client (no possibility to add some sleeptime or changes of the subscriptions). Are there any other options/config settings for improvement?

**Comment by HJianBo** [comment] 2019-08-30 09:15
Afraid not. It should enhance the behaviour of wildcard topic subscription to handle it.

How many connections in the one sec? 

I suppose it is not a huge number, maybe you can try to turn down the `listener.tcp.internal.max_conn_rate = 1000` value to reduce the server pressure for executing subscribe transaction

**Comment by gbrehmer** [comment] 2019-08-30 10:13
i updated the description:
UPDATE: With the hint to the underlying problem from the mentioned other bug, we can now reproduce the problem with your benchmark client (our previous benchmarks only covers publish from client and subscriptions in the backend). with 600 clients (300 publishing, 300 subscribing, 300msg/s) all is working fine. with 1200 clients ( 600 publishing, 600 subscribing, still 300 msg/s) the error rate was very high. If we reduce the topic levels (still with wildcard) we could handle 2400 clients w/o errors, with 4800 the problem comes back.

connections / second will increase to the current peak number of simultaneously active devices if we had a connection loss / downtime before (like for the broker update). Currently the devices had no exponential backoff implemented and will retry every 20s. Because Timeouts has to be raised I think it must be 2500-4000 devices which will simultaneously try to connect.

Regarding your suggestion, you're right with the knowledge of the underlying bug, we found out that increasing the max_conn_rate from 1k to 10k was a really bad decision but the problems also occur with 1k  Yes a lower connection rate could be very helpful (e.g. 100), but currently we can not test it with your benchmark client, because reconnect feature was removed in the underlying mqtt client library. we will try to test with the old library.

**Comment by HJianBo** [comment] 2019-08-31 03:36
Thanks for your so explicit descriptions and testing !  It very useful to help me profiling it

> Is it right to say, that the problem can increase, if we install more nodes to handle more traffic/devices? Is a distributed transaction required?

Yes. The distributed transaction is required, so it is only increasing problems if we add more nodes. The core problem is how to handle the subscription for wildcard topic (there are too many insert operations in the one transaction for it)

We have plan to improve it at v4.0

**Comment by gbrehmer** [comment] 2019-09-09 21:03
we tested 4.0-alpha.2 and get similar results to 3.2.3. Benchmark-Client seems not to crash, but approx. 20% of subscriptions failed silently on first try (only visible on server side logfile). (1200 clients, 600 subscriber, 600 publisher, 300 messages published/s, 240 messages received/s)

**Comment by gbrehmer** [comment] 2019-10-10 21:01
we tested 4.0-beta.1 and get worse results than with 3.2.3 and previous 4.0.alpha versions. Benchmark-Client seems not to crash, but some or more of the subscriptions failed silently on first try (only visible on server side logfile):

Case 1: 1200 clients, 600 subscriber, 600 publisher, 300 messages published/s, 120 messages received/s (60% loss)
Case 2: 600 clients, 300 subscriber, 300 publisher, 300 messages published/s, 272 messages received/s (9% loss)
Case 3: 400 clients, 200 subscriber, 200 publisher, 200 messages published/s, 200 messages received/s (0% loss)

**Comment by gbrehmer** [comment] 2020-01-17 18:20
@HJianBo 
better news from our side. It seems that 4.0.1 in comparison to 4.0-beta.1 has some improvements inside:

Case 1: 1200 clients, 600 subscriber, 600 publisher, 300 messages published/s, 120 messages received/s (2% loss)
Case 2: 600 clients, 300 subscriber, 300 publisher, 300 messages published/s, 272 messages received/s (0% loss)
Case 3: 400 clients, 200 subscriber, 200 publisher, 200 messages published/s, 200 messages received/s (0% loss)
new Case 4: 2400 clients, 1200 subscriber, 1200 publisher, 300 messages published/s, 300 messages received/s (30% loss)

Are there any other improvements planned?

**Comment by alexandrim0** [comment] 2020-01-18 16:52
Hello!

I met the same problem with 3.2.7 whichhandled about 2700 clients.
It seems, using 4.0.1 could serve that amount of clients.

**Comment by HJianBo** [comment] 2020-01-19 02:45
Yep, @alexandrim0 @gbrehmer But the main cost is caused by the transaction of inserting the subscription `Topic Trie`.

We have a plan to improve it at v5.0.

**Comment by HJianBo** [comment] 2020-01-19 03:32
This has duplicated at https://github.com/emqx/emqx/issues/2985

@BorisPetelj give us a very details test report here: https://github.com/emqx/emqx/issues/2985#issuecomment-555489251

I'll close this discussion and focus on that. Thank anybody attention here

**Closed by HJianBo** 2020-01-19 03:32 UTC
Labels: Enhancement
