### ISSUE TITLE
4.3.3 emqx_auth_mnesia can't set user as superuser in config

### ISSUE THREAD

**Issue by GuryYu** [emqx/emqx#4966] opened 2021-06-09 11:42 UTC
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 
  4.3.3
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:

```
https://github.com/emqx/emqx-auth-mnesia/blob/master/etc/emqx_auth_mnesia.conf
## Examples:
##auth.mnesia.1.login = admin
##auth.mnesia.1.password = public
##auth.mnesia.1.is_superuser = true
```

set *auth.mnesia.1.is_superuser* or *auth.user.1.is_superuser* all fail, it not't works.

set with docker env params also fail.

eg.
```
docker run -itd \
-e TZ=Asia/Shanghai \
-e EMQX_ALLOW_ANONYMOUS=false \
-e EMQX_LOADED_PLUGINS="emqx_auth_mnesia,emqx_management,emqx_recon,emqx_retainer" \
-e EMQX_AUTH__MNESIA__PASSWORD_HASH="plain" \
-e EMQX_AUTH__USER__1__USERNAME="root" \
-e EMQX_AUTH__USER__1__PASSWORD="root" \
-e EMQX_AUTH__USER__1__IS_SUPERUSER="true" \
emqx/emqx:4.3.3
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by k32** [comment] 2021-06-09 11:57
Hello,
Superuser has been removed in 4.3, when the opensource version of the broker switched to the enterprise version of auth_mnesia plugin. Documentation wasn't updated, though. So this issue is a duplicate of https://github.com/emqx/emqx/issues/4952

**Closed by k32** 2021-06-09 11:57 UTC
Labels: Support
