### ISSUE TITLE
peer_cert_as_username TLS not working in EMQX 4.2.6

### ISSUE THREAD

**Issue by KrYpToDeN** [emqx/emqx#4033] opened 2021-01-19 05:50 UTC
Hello, setting - peer_cert_as_username is not working in EMQX 4.2.6.

I tried to connect with two way TLS ang got this in log file:
2021-01-19 05:29:20.556 [warning] <<"be3d1252-d876-4e87-856f-15fba5ee01ba1611034107155">>@10.77.1.1:62189 [Channel] Client be3d1252-d876-4e87-856f-15fba5ee01ba1611034107155 (Username: 'undefined') login failed for not_authorized.

How can you see Username is underfined.

My connection command is:
mosquitto_sub -h domain.com -p 8883 --cafile root.pem --cert client.pem --key client.key -t 'topic' -d

My settings are:
allow_anonymous = false
listener.ssl.external = 8883
listener.ssl.external.keyfile = server.key
listener.ssl.external.certfile = server.pem
listener.ssl.external.cacertfile = root.pem
listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = true
listener.ssl.external.peer_cert_as_username = cn

My OS is Debian 10.

Could you help me to solve my problem?

Thank you.

**Comment by HJianBo** [comment] 2021-01-21 02:22
Hi, @KrYpToDeN I have checked these codes. It is simply a printing error. In fact, the Username is equal to the contents of cn.

**Comment by KrYpToDeN** [comment] 2021-01-21 02:25
> Hi, @KrYpToDeN I have checked these codes. It is simply a printing error. In fact, the Username is equal to the contents of cn.

Hello @HJianBo . Thank you for testing.

Also, to solve this problem (login failed for not_authorized) i should check my ACL?

**Comment by HJianBo** [comment] 2021-01-21 02:31
Check that plug-in authentication is enabled instead of ACLs.

**Comment by KrYpToDeN** [comment] 2021-01-21 02:33
> Check that plug-in authentication is enabled instead of ACLs.

ok, and the last one question.

Tell me, please, mysql auth plugin is good working with tls auth?

**Comment by HJianBo** [comment] 2021-01-21 02:36
Yes it is.  see: https://docs.emqx.io/en/broker/latest/advanced/auth-mysql.html#salting-rules-and-hash-methods

**Comment by KrYpToDeN** [comment] 2021-01-22 03:19
> Yes it is. see: https://docs.emqx.io/en/broker/latest/advanced/auth-mysql.html#salting-rules-and-hash-methods

Hello, about yesterday discussion:

i tried to connect via TLS connection (two way), and i got error:
```
2021-01-22 03:10:09.150 [error] <<"mosq-8uSquVlIsFP0oF0bHq">>@10.77.1.1:60320 [Hooks] Failed to execute {fun emqx_auth_mysql:check/3,[#{auth_query => {"select password from mqtt_user where username = ? limit 1",["'%C'"]},hash_type => md5,pool => emqx_auth_mysql,super_query => {"select is_superuser from mqtt_user where username = ? limit 1",["'%C'"]}}]}: {badarg,[{erlang,iolist_to_binary,[undefined],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,604}]},{emqx_passwd,hash,2,[{file,"emqx_passwd.erl"},{line,59}]},{emqx_passwd,check_pass,2,[{file,"emqx_passwd.erl"},{line,41}]},{emqx_auth_mysql,check_pass,2,[{file,"emqx_auth_mysql.erl"},{line,85}]},{emqx_auth_mysql,check,3,[{file,"emqx_auth_mysql.erl"},{line,43}]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,164}]},{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,143}]}]}
2021-01-22 03:10:09.151 [warning] <<"mosq-8uSquVlIsFP0oF0bHq">>@10.77.1.1:60320 [Channel] Client mosq-8uSquVlIsFP0oF0bHq (Username: 'undefined') login failed for not_authorized
```

My MySQL config is:

```
auth.mysql.auth_query = select password from mqtt_user where username = '%C' limit 1
auth.mysql.password_hash = md5
auth.mysql.super_query = select is_superuser from mqtt_user where username = '%C' limit 1
auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c' or clientid = '$all'

auth.mysql.ssl = on
auth.mysql.ssl.cafile  = root.pem
auth.mysql.ssl.certfile = server.pem
auth.mysql.ssl.keyfile = server.key
```

If i change `%C` to `%us`, connecting via username+password => it's ok.
But via TLS i got error. I don't have password for TLS certs, what should i do in this situation?
I need to connect via TLS without password, using only root.pem -> client.pem -> client.key files.

If i allow anonymous - it's ok.

Help me, please. The intenet has information only for usersname+password connection.

**Comment by HJianBo** [comment] 2021-01-26 07:21
It looks like it's because the CN was not fetched. can you confirm that the device is connected to the emqx via two-way authentication?

**Comment by KrYpToDeN** [comment] 2021-01-27 06:16
> It looks like it's because the CN was not fetched. can you confirm that the device is connected to the emqx via two-way authentication?

Hello, @HJianBo 

I think yes, beacause all emqx config is:

```
allow_anonymous = false
listener.ssl.external = 8883
listener.ssl.external.keyfile = /etc/emqx/certs/openssl_database/chain_1/private/client/canhoc.key
listener.ssl.external.certfile = /etc/emqx/certs/openssl_database/chain_1/certs/client/canhoc.crt
listener.ssl.external.cacertfile = /etc/emqx/certs/openssl_database/chain_1/certs/ca/rootCA.crt
listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = true
listener.ssl.external.peer_cert_as_username = cn
```

Is it all right in setiings?

**Comment by HJianBo** [comment] 2021-01-28 03:54
This seems right and works well for me..

**Comment by KrYpToDeN** [comment] 2021-01-28 03:57
> This seems right and works well for me..

I think the same, all should be good, but..

Could you suggest me, how to make it work, please?

**Comment by zmstone** [comment] 2021-01-28 05:11
What exactly is the common name in the certificate? Could you please use OpenSSL command to inspect?

not sure if the chain depth affects anything, what’s the depth in your tests?

@HJianBo do we have debug logs for this?
If not, maybe  `recon` trace?

**Comment by HJianBo** [comment] 2021-01-28 05:46
No logs here. :(

If this is possible, we only have to trace the execution of some functions.

1. Execute `bin/emqx attach` to get to the emqx console
2. Enter the following commands to track each login request, `dbg:tracer(),dbg:p(all,call),dbg:tp(emqx_auth_mysql,check,x),dbg:tp(mysql,x). `
3. Use the client to try to log in; then the console will prints a lot of logs. Please post these here.

**Comment by KrYpToDeN** [comment] 2021-02-05 03:43
> * te `bin/emqx attach` to get to the emqx console
> * Enter the following commands to track each login request, `dbg:tracer(),dbg:p(all,call),dbg:tp(emqx_auth_mysql,check,x),dbg:tp(mysql,x). `
> * Use the client to try to log in; then the console will print a lot of logs. Please post these here.

Hello, @HJianBo 

Logs are below:
`(emqx@127.0.0.1)1>
(emqx@127.0.0.1)1>
(emqx@127.0.0.1)1> dbg:tracer(),dbg:p(all,call),dbg:tp(emqx_auth_mysql,check,x),                                                                                                                                                             dbg:tp(mysql,x).
{ok,[{matched,'emqx@127.0.0.1',26},{saved,x}]}
(emqx@127.0.0.1)2> (<0.2013.0>) call emqx_auth_mysql:check(#{clientid => <<"mosq                                                                                                                                                             -czpl0HcAE73ZAqQcp3">>,cn => <<"1D001000001">>,
  dn => <<"CN=1D001000001,O=CanHoc Company,L=Moscow,ST=MO,C=RU">>,
  is_bridge => false,is_superuser => false,mountpoint => undefined,
  password => undefined,
  peerhost => {10,77,1,1},
  protocol => mqtt,sockport => 8883,username => <<"1D001000001">>,
  zone => external},#{anonymous => false,auth_result => not_authorized},#{auth_q                                                                                                                                                             uery =>
      {"select password from mqtt_user where username = ? limit 1",["'%u'"]},
  hash_type => md5,pool => emqx_auth_mysql,
  super_query =>
      {"select is_superuser from mqtt_user where username = ? limit 1",
       ["'%C'"]}})
(<0.2013.0>) call mysql:query(<0.1813.0>,"select password from mqtt_user where u                                                                                                                                                             sername = ? limit 1",[<<"1D001000001">>])
(<0.2013.0>) returned from mysql:query/3 -> {ok,[<<"password">>],[[null]]}
(<0.2013.0>) exception_from {emqx_auth_mysql,check,3} {error,badarg}
2021-02-05 06:41:40.091 [error] <<"mosq-czpl0HcAE73ZAqQcp3">>@10.77.1.1:39620 [H                                                                                                                                                             ooks] Failed to execute {fun emqx_auth_mysql:check/3,[#{auth_query => {"select p                                                                                                                                                             assword from mqtt_user where username = ? limit 1",["'%u'"]},hash_type => md5,po                                                                                                                                                             ol => emqx_auth_mysql,super_query => {"select is_superuser from mqtt_user where                                                                                                                                                              username = ? limit 1",["'%C'"]}}]}: {badarg,[{erlang,iolist_to_binary,[undefined                                                                                                                                                             ],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,604}]},{emqx_passwd,hash,2,[{fil                                                                                                                                                             e,"emqx_passwd.erl"},{line,59}]},{emqx_passwd,check_pass,2,[{file,"emqx_passwd.e                                                                                                                                                             rl"},{line,41}]},{emqx_auth_mysql,check_pass,2,[{file,"emqx_auth_mysql.erl"},{li                                                                                                                                                             ne,85}]},{emqx_auth_mysql,check,3,[{file,"emqx_auth_mysql.erl"},{line,43}]},{emq                                                                                                                                                             x_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,164}]},{emqx_hooks,do_run_                                                                                                                                                             fold,3,[{file,"emqx_hooks.erl"},{line,143}]}]}
2021-02-05 06:41:40.092 [warning] <<"mosq-czpl0HcAE73ZAqQcp3">>@10.77.1.1:39620                                                                                                                                                              [Channel] Client mosq-czpl0HcAE73ZAqQcp3 (Username: 'undefined') login failed fo                                                                                                                                                             r not_authorized
`

**Comment by KrYpToDeN** [comment] 2021-02-09 23:39
Hello, @HJianBo

I think, the trouble is in SQL query,

Could you hep me. please?

**Comment by HJianBo** [comment] 2021-02-11 10:08
Sorry for the late reply @KrYpToDeN. We can see that cn, dn are correctly retrieved:
```erl
cn => <<"1D001000001">>, dn => <<"CN=1D001000001,O=CanHoc Company,L=Moscow,ST=MO,C=RU">>
```

The real reason for the error is that the client's Password is undefined, but `emqx-auth-mysql` uses it to compare with the results of the query.

For the moment, a temporary solution is to see if you need to use password matching (which in most cases you do). Then, your client should pass a password to the emqx broker.

Also, I think it's a flaw in the code that doesn't take into account some null values.

**Comment by KrYpToDeN** [comment] 2021-02-11 11:16
> Sorry for the late reply @KrYpToDeN. We can see that cn, dn are correctly retrieved:
> 
> ```erlang
> cn => <<"1D001000001">>, dn => <<"CN=1D001000001,O=CanHoc Company,L=Moscow,ST=MO,C=RU">>
> ```
> 
> The real reason for the error is that the client's Password is undefined, but `emqx-auth-mysql` uses it to compare with the results of the query.
> 
> For the moment, a temporary solution is to see if you need to use password matching (which in most cases you do). Then, your client should pass a password to the emqx broker.
> 
> Also, I think it's a flaw in the code that doesn't take into account some null values.

Hello, @HJianBo .

The problem also is that MQTT doesn't alow us to user password without username.
Using username is bad idea, because we try to use cetrs => it makes no sense to use certs. But we need it..

Could you please check it in further version?
We will be very happy if we can use it in nearly future.

Thank you.
 
P.S. also could you suggest us another way to use two-way certificates auth?

**Comment by HJianBo** [comment] 2021-02-13 09:18
If this is the case, why do we need to enable the emqx-auth-mysql plugin? As long as the SSL two-way handshake is successful, the device will be proven to be legitimate.

**Comment by KrYpToDeN** [comment] 2021-02-13 09:22
> If this is the case, why do we need to enable the emqx-auth-mysql plugin? As long as the SSL two-way handshake is successful, the device will be proven to be legitimate.

Hello, @HJianBo 

We need realtime ACL settings. MySQL - i think the best way to control it.
Could you check it in further version, please?

**Comment by HJianBo** [comment] 2021-02-13 09:26
If you don't need authentication, just comment out these lines:

```
#auth.mysql.auth_query = select password from mqtt_user where username = '%C' limit 1
#auth.mysql.super_query = select is_superuser from mqtt_user where username = '%u' limit 1
```

**Comment by KrYpToDeN** [comment] 2021-02-13 11:16
> If you don't need authentication, just comment out these lines:
> 
> ```
> #auth.mysql.auth_query = select password from mqtt_user where username = '%C' limit 1
> #auth.mysql.super_query = select is_superuser from mqtt_user where username = '%u' limit 1
> ```

Thank you, @HJianBo 

We will try this way, soon.

Tell me, please, if we else want to connect via admin account (username + password) to read all user topics from our scripts.
Probably via REST api.

Can we do it, if we will disable auth check in mysql plugin?

**Comment by HJianBo** [comment] 2021-02-14 11:12
Yes, you can.

**Comment by KrYpToDeN** [comment] 2021-02-15 09:16
> If you don't need authentication, just comment out these lines:
> 
> ```
> #auth.mysql.auth_query = select password from mqtt_user where username = '%C' limit 1
> #auth.mysql.super_query = select is_superuser from mqtt_user where username = '%u' limit 1
> ```

Hello, @HJianBo 

In this way, if allow_anonymous is false, we got:

[Channel] Client mosq-w9BZd68fFDULipcKd7 (Username: 'undefined') login failed for not_authorized

**Comment by KrYpToDeN** [comment] 2021-02-16 12:44
Hello, @HJianBo 

Could you hep me to solve my problem and close this issue?

We are interesting in your project, we are looking for enterprise version. But we need it to work with our needs.

We are waiting for your help, thanks.

**Comment by HJianBo** [comment] 2021-02-18 03:19
> [Channel] Client mosq-w9BZd68fFDULipcKd7 (Username: 'undefined') login failed for not_authorized

The `Username` is actually set up, but there is a problem with the printing here. This has been fixed in 4.3.0. Don't worry, it just a BUG for log printing.

In addition, the authentication failure is caused by the fact that you have turned off allow_anonymous and no authentication plugin gives the client authorization.

There are two solutions here:

1. Turn on allow_anonymous, if a successful SSL connection proves that the client has full legal access to the system.

2. if the CN in the certificate is fixed, turn off allow_anonymous, and enable emqx_auth_username to grant access to the fixed CN client.

**Comment by KrYpToDeN** [comment] 2021-03-06 09:28
> 2\. emqx_auth_username

Hello, @HJianBo 

Thank you for your answer, we tried use it with emqx_auth_username.
As with mysql_auth we can't auth if we use:
`listener.ssl.external.peer_cert_as_username = cn`
and we don't use password.

If we set some password in MQTT client and set the same password in plugin -> it's work good.
But, we also can auth without ssl (certs), using only our username (common_name) and our password.
In this way SSL connection is no sense, because we can auth without it.

The problem is that plugins (username, mysql) can't work without user password (two way SSL should work without password on the right).

Can you add to plugins possibility to work it without password in SSL mode?
or SSL is useless in another way.

**Comment by HJianBo** [comment] 2021-03-09 02:44
> The problem is that plugins (username, mysql) can't work without user password (two way SSL should work without password on the right).

yes, you are right. There is an option `.bypass_auth_plugins` to skip authentication steps. This option is configurable in the zone only, so you need to create a new configuration zone to put it.  
```
## Allow the zone's clients to bypass the authentication step
##
## Value: true | false
zone.your_ssl_zone.bypass_auth_plugins = true
```

In 4.3, this is only a temporary solution. I converted your requirement to another feature request issue, and we will discuss there if we need to add a new feature

**Closed** 2023-10-09 11:10 UTC
Labels: BUG
