### ISSUE TITLE
Dropping messages after unsubscribe to a topic with # at the end

### ISSUE THREAD

**Issue by marcAnfuso** [emqx/emqx#11635] opened 2023-09-19 13:17 UTC
### What happened?

Example:
We have many clients listening/suscribed to a topic like 'building/123/hipboard/123/action', each one with the values of their respectives buildings/hipboards.
We have a main service listening/suscribed to: building/+/hipboard/+/action.
When some of us starts to listen to this topic but suscribing to: 'building/+/hipboard/+/action/#'
and then I unsubscribe, all other clients still receiving your messages, but the main service listening to 'building/+/hipboard/+/action' stop receiving messages. We suspect that EMQX believes that by stopping listening to the topic with the /# at the end, it believes that there are no subscribers and drops the messages.

When we resubscribe again with /# at the end, it is fixed and the main service starts to listen to their messages again.

### What did you expect to happen?

Continuously receive messages on the topic building/+/hipboard/+/action

### How can we reproduce it (as minimally and precisely as possible)?

Subscribe some clientes to a topics like building/123/hip/123/something
Subscribe a client to a topic: building/+/hip/+/something/#
Unsuscribe the last client with the topic /# at the end
Check if the other clients are receiving their messages
Check if your client (with the topic with wildcards) is listening all messages 

### EMQX version

sysdescr  : EMQX
version   : 5.0.26
datetime  : 2023-09-18T21:09:31.012974128+00:00
uptime    : 3 hours, 3 minutes, 27 seconds

### OS version

Docker image: emqx/emqx:5.0.26

### Log files

<details>
`sysinfo.txt:
========================================================
    /opt/emqx/bin/emqx_ctl broker
========================================================
sysdescr  : EMQX
version   : 5.0.26
datetime  : 2023-09-18T21:13:52.913904463+00:00
uptime    : 3 hours, 7 minutes, 48 seconds

========================================================
    /opt/emqx/bin/emqx eval 'emqx_node_dump:sys_info()'
========================================================
#{otp_version => <<"24.3.4.2-3">>,release => "5.0.26"}

========================================================
    uname -a
========================================================
Linux master-emqx-0 5.10.186-179.751.amzn2.x86_64 #1 SMP Tue Aug 1 20:51:38 UTC 2023 x86_64 GNU/Linux

========================================================
    uptime
========================================================
 21:13:54 up 4 days,  8:45,  0 users,  load average: 0.97, 1.23, 1.29

========================================================
    free
========================================================
               total        used        free      shared  buff/cache   available
Mem:        16369536     3704372      290556       49512    12374608    12382040
Swap:              0           0           0

========================================================
    netstat -tnl
========================================================
Unavailable

========================================================
    /opt/emqx/bin/emqx_ctl plugins list
========================================================
{
  
}

========================================================
    /opt/emqx/bin/emqx_ctl vm all
========================================================
cpu/load1               : 1.05
cpu/load5               : 1.23
cpu/load15              : 1.28
memory/total            : 158369384
memory/processes        : 54246152
memory/processes_used   : 54227456
memory/system           : 104123232
memory/atom             : 1999233
memory/atom_used        : 1977314
memory/binary           : 3104848
memory/code             : 46620286
memory/ets              : 23109000
process/limit           : 2097152
process/count           : 1600
io/max_fds              : 1048576
io/active_fds           : 0
ports/count             : 326
ports/limit             : 1048576

========================================================
    /opt/emqx/bin/emqx_ctl listeners
========================================================
ssl:default
  listen_on       : :8883
  acceptors       : 16
  proxy_protocol  : true
  running         : true
  current_conn    : 0
  max_conns       : 5000000
  shutdown_count  : []
tcp:default
  listen_on       : :1883
  acceptors       : 16
  proxy_protocol  : true
  running         : true
  current_conn    : 269
  max_conns       : 5000000
  shutdown_count  : [{idle_timeout,18},{keepalive_timeout,232},{takenover,813},{tcp_closed,11929},{expired,67},{malformed_packet,3},{discarded,39960},{protocol_error,190},{bad_username_or_password,196},{client_identifier_not_valid,358},{not_authorized,7}]
ws:default
  listen_on       : :8083
  acceptors       : 16
  proxy_protocol  : true
  running         : true
  current_conn    : 0
  max_conns       : 5000000
  shutdown_count  : []
wss:default
  listen_on       : :8084
  acceptors       : 16
  proxy_protocol  : true
  running         : true
  current_conn    : 0
  max_conns       : 5000000
  shutdown_count  : []`

</details>

**Comment by zmstone** [comment] 2023-09-19 15:04
Thank you @marcAnfuso.
I'll look into this ASAP.

**Comment by marcAnfuso** [comment] 2023-09-19 15:07
> Thank you @marcAnfuso. I'll look into this ASAP.

Thank you! We can't reproduce this issue. It's only happening on just ONE topic on PRODUCTION environment.
We have our main app depending on our client to stay suscribed to the topic with '/#' in the end. If some of us disconnect our client, the main app just stop receiving messages until we reconnect.

**Comment by zmstone** [comment] 2023-09-19 19:16
> > Thank you @marcAnfuso. I'll look into this ASAP.
> 
> Thank you! We can't reproduce this issue. It's only happening on just ONE topic on PRODUCTION environment. We have our main app depending on our emqx-client to stay suscribed to the topic with '/#' in the end. If some of us disconnect our emqx-client, the main app just stop receiving messages until we reconnect.

By the look of it, it seems to be a race condition. 
I'll try to reproduce it first.
A few more questions to help my investigation:
* Are you running a cluster?
* how many nodes?
* how are the clients and the main app distributed over the nodes in the cluster?

**Comment by zmstone** [comment] 2023-09-20 06:10
> Our main app is listening with "share", something like: $share/main-app/building/+/hipboard/+/action

This is a very important piece of information, thank you.

**Comment by zmstone** [comment] 2023-09-20 15:38
also, by any chance you have more than 1024 subscribers on the same topic?

**Comment by marcAnfuso** [comment] 2023-09-20 15:50
> Hi again @marcAnfuso Did you happen to observe any node re-join events in the logs prior to the missing route happens? Would be good if you can share the logs as well as some correlation events in the log or tell us around what time you have started noticing the message drop.

Give me some time to collect logs and I'll share it with you. Thank you!

> also, by any chance you have more than 1024 subscribers on the same topic?

Mmm, I dont think so.

**Comment by zmstone** [comment] 2023-09-20 16:19
Thanks.
did you happen to have changed this config: `broker.perf.route_lock_type` ?

**Comment by zmstone** [comment] 2023-09-21 07:04
@marcAnfuso  another question, all three nodes are `core` nodes, right ? you are not running any `replicant` nodes in the cluster?

**Comment by zmstone** [comment] 2023-09-21 07:15
And which MQTT client (sdk/library) are you using ?

**Comment by zmstone** [comment] 2023-09-21 11:03
I have been investigating together with the team today and in the past 2 days as well.
It is quite puzzling to all of us, the root cause is yet to be identified.
 
A quick summary of the issue so far.

# reports

For transparency, similar issues have been reported from 3 different users.
1. v5.0.26 (this issue)
2. e5.0.2 (an enterprise customer)
3. v5.1.1 (reported in our Chinese [forum](https://askemq.com/t/topic/5731/22))

# direct cause of message drops

There is seemingly to be a missing index entry for a wildcard route.
To be more specific, `emqx_route` table stores the mapping from topics to routes.

To confirm it, one can execute `emqx remote_console` command to attach to an Erlang console,
then evaluate the below Erlang expressions to verify if data integrity is broken:

## Inspect routes
`ets:lookup(emqx_route, <<"the problematic topic">>).` (mind the dot at the end)
For example
```
v5.0.26(emqx@node1.emqx.io)66> ets:lookup(emqx_route, <<"b/+/h/+/a">>).
[#route{topic = <<"b/+/h/+/a">>,
        dest = 'emqx@node3.emqx.io'}]
v5.0.26(emqx@node1.emqx.io)67> ets:lookup(emqx_route, <<"b/+/h/+/a/#">>).
[#route{topic = <<"b/+/h/+/a/#">>,
        dest = 'emqx@node3.emqx.io'}]
```

## verify if index of the routes are missing

`emqx_trie:match(<<"the publishing topic">>).` (mind the dot at the end)
For example:
```
v5.0.26(emqx@node1.emqx.io)69> emqx_trie:match(<<"b/1/h/2/a">>).
[<<"b/+/h/+/a/#">>,<<"b/+/h/+/a">>]
```

If there is a missing index, the `emqx_trie:match` expression may return empty list or less matches than expected.
For instance, if `<<"b/+/h/+/a">>` is not included, then the message will not be delivered to this subscribers listening to this topic.

# Potential root cause

By the look of it, it is essentially a broken atomic-transaction promise from Mnesia the built-in database in Erlang/OTP. There is no evidence to blame Mnesia on it though, the application level code is equally suspicious. 

# Next steps

* It would be really helpful if we can find a stable way to reproduce this issue.
* We can add a data integrity audit in the code where route updates are skipped due to existing route found, this might help to recover from a broken state, but will leave the cause unidentified.
* Consider upgrading to `v5.2.1` or `e5.2.1` with configuration `broker.routing.storage_schema = v2`. 

## A few remarks on `broker.routing.storage_schema = v2`

* This is still a hidden config in v5.2, so it's not documented yet.
* It requires a full cluster restart (not rolling restart) in order for it to take effect after upgraded from 5.0 or 5.1.
* This config will make EMQX start using a conflict-free data structure, so it's free from data integrity issues.
* `v2` will become the default config value starting from EMQX 5.4

**Comment by marcAnfuso** [comment] 2023-09-21 13:14
> Thanks. did you happen to have changed this config: `broker.perf.route_lock_type` ?

Hello! First of all, thank you so much for your time.

And, No, I don't think so. We didnt change that config.



> @marcAnfuso another question, all three nodes are `core` nodes, right ? you are not running any `replicant` nodes in the cluster?

Yes, three nodes are core nodes. There's no 'replicant' nodes in the cluster.



> And which MQTT client (sdk/library) are you using ?

We (devs) are using MQTTX for Ubuntu.
Our main app (Python&Flask) is using 'paho-mqtt==1.6.1'.

**Comment by gbrehmer** [comment] 2023-12-10 19:19
I think we have the same behavior/problem.

We are running 5 code nodes (no replicant) with 5.0.26 since one week and saw already multiple times high amount of dropped messages. Currently I don't have so much deep details when its occurring, because normally we try to fix the problem asap instead of analyzing the current status. But we will try to reproduce the issue again.

Last time it occurs we restarted our main backend service. what does this mean:

setup:
- two pods and both are subscribing to the same topics
- 15 client connections per pod
- real sessions without clean startup (= offline messages, etc.)
- each client connection subscribes to 14 wildcard topics, e.g. `home/1/#`, `home/2/#`, ...
- example topics are: `home/131/8126234/K86ja7q59oO74IGXGTsJfsd/ch/1/temp/actual`
- (in addition each device client also have one wildcard topic (currently 25k wildcard subscriptions)
  - device wildcard subscription: e.g. `home/131/8126234/K86ja7q59oO74IGXGTsJfsd/job/+/status`
  - because of this we have the following indexes ( :question: are those indexes correctly defined :question:)
```
            index_specs = [
              [1,2],
              [1,2,3,4,5,7,8,9]
```
- for redeployment an additional pod will be started for each running pod
- I found a problem in our current setup:
  - before using emqx 5 and k8s we were using fixed VMs with stable hostnames -> and we are using the hostname as a part of the clientid -> but now within k8s, we got a new hostname with each deployment. So after deployment the old session is still there which is probably receiving a lot of offline messages and two more sessions are created -> we will try to change the client-id template so it can be reused after backend service redeployment

we fixed the dropped-message-problem by restarting all 5 emqx core pods (not all in parallel)

**Comment by zmstone** [comment] 2024-01-24 08:44
Hi @gbrehmer 
Given your descriptions, we cannot conclude if this is the same cause as the issue reported originally in this thread.

I would recommend upgrading to version 5.4.1

I'm closing this issue now.
Please feel free to open new issues, preferably focusing on one specific topic.

**Closed** 2024-01-24 08:50 UTC
Labels: BUG
