### ISSUE TITLE
Forwards of mqtt bridge is not working

### ISSUE THREAD

**Issue by oakfire** [emqx/emqx#2566] opened 2019-05-24 08:11 UTC
#### Environment

- OS: Docker/alpine
- Erlang/OTP: 
- EMQ: v3.1.1

#### Description

I use docker to run two emqx services named 'emqx1' and 'emqx2',  and set a mqtt bridge to emqx2  in emqx1 ,  subscribes by the bridge is working, but forwards by the bridge is not working.
----
 我在官网下载了 v3.1.1 的 docker 版本， 用docker跑起来两个emqx服务，分别为 emqx1 和 emqx2, 我在其中 emqx1 设置了下 mqtt bridge 连到 emqx2, 但测试下来发现 forwards 不起作用， subscribe  是起作用的，即  emqx1 能收到使用 bridge 订阅 emqx2的消息，但是 emqx2  收不到 emqx1 转发的消息。

**Comment by zxsoft** [comment] 2019-05-24 09:14
I'v met just the same issue as you do, but I'm not using the docker version. So I think it's a issue of emqx v3.1.1 itself, not the docker wrapper.

**Comment by HJianBo** [comment] 2019-05-25 06:11
Hi guys, could you paste the related configure options to there?

**Comment by oakfire** [comment] 2019-05-27 02:26
> Hi guys, could you paste the related configure options to there?

OK.  I start  the two services by:
```
docker run -d --name emqx1  -p 1883:1883 -p 18083:18083 emqx/emqx:v3.1.1-amd64
docker run -d --name emqx2  -p 2883:1883 -p 18084:18083 emqx/emqx:v3.1.1-amd64
``` 
 then  `docker exec -it emqx1 sh` to edit emqx1's  emqx.conf file, add
```
# 172.17.0.8 is my emqx2 ip of docker net, you can set to 172.17.0.1:2883 if your docker host is not MacOS, or just <your host ip>:2883.
bridge.aws.address = 172.17.0.8:1883
bridge.aws.proto_ver = mqttv4
bridge.aws.client_id = bridge_emqx1
bridge.aws.clean_start = true
bridge.aws.username = user
bridge.aws.password = passwd
bridge.aws.ssl = off
bridge.aws.forwards = forward/#
bridge.aws.mountpoint = bridge/emqx1/
bridge.aws.subscription.1.topic =sub/#
bridge.aws.subscription.1.qos = 1
```
and `docker restart  emqx1`  to make bridge enabled.  The testing codes write by node.js, using the latest npm package `mqtt`:

```
const mqtt = require('mqtt');
const c1_url = 'mqtt://127.0.0.1:1883';
const c2_url = 'mqtt://127.0.0.1:2883';
const now = function(){
    return ~~(new Date().getTime() / 1000);
}
const c1 = mqtt.connect(c1_url, {
    clientId: 'c1',
    clean: true,
});

c1.on('connect', () => {
    setInterval( () => {
        let data = {
            timestamp: now(),
        };
        c1.publish('forward/c1', JSON.stringify(data),{qos:1}, err => {
            if(!err){
                console.log('c1 forward sended');
            }else{
                throw(err);
            }
        });
    }, 1000);

    c1.subscribe('sub/#');
    c1.on('message', (topic, msg) => {
        console.log(`c1 rev topic: ${topic}; msg: ${msg}`);
    });
});

const c2 = mqtt.connect(c2_url, {
    clientId: 'c2',
    clean: true,
});

c2.on('connect', () => {
    setInterval( () => {
        let data = {
            timestamp: now(),
        };
        c2.publish('sub/c1', JSON.stringify(data),{qos:1}, err => {
            if(!err){
                console.log('c2 sub sended');
            }else{
                throw(err);
            }
        });
    }, 1000);

    c2.subscribe('bridge/#', (err, granted) => {
        if(err){
            throw(err);
        }
    });
});
c2.on('message', (topic, message) => {
    console.log(`c2 rev topic: ${topic}, msg: ${message}`);
});
```

and the result missing `c2 rev topic ...`: 

```
c2 sub sended
c1 forward sended
c1 rev topic: sub/c1; msg: {"timestamp":1558923800}
c2 sub sended
c1 forward sended
c1 rev topic: sub/c1; msg: {"timestamp":1558923801}
c1 forward sended
c2 sub sended
c1 rev topic: sub/c1; msg: {"timestamp":1558923802}
...
```

**Comment by Gilbert-Wong** [comment] 2019-05-27 02:28
Thanks for your feedback, I'll check it soon.

**Comment by Gilbert-Wong** [comment] 2019-05-30 09:43
Hi, @oakfire, did you disable the config entry `bridge.aws.mountpoint = bridge/emqx1/`, if you do not disable it , you should let your c2 to subscribe topic `bridge/emqx1/sub/#`.

**Comment by oakfire** [comment] 2019-05-30 09:57
> Hi, @oakfire, did you disable the config entry `bridge.aws.mountpoint = bridge/emqx1/`, if you do not disable it , you should let your c2 to subscribe topic `bridge/emqx1/sub/#`.

No, I let c2 to subscribe  `brudge/#` already, which include `bridge/emqx1/sub/#`.  You would reproduce the problem if follow my steps above.

**Comment by Gilbert-Wong** [comment] 2019-05-30 09:59
Sorry I have tested it with mosquitto, and I cannot reproduce the problem you encountered.

**Comment by oakfire** [comment] 2019-05-30 10:26
> Sorry I have tested it with mosquitto, and I cannot reproduce the problem you encountered.

Thanks, But I meet the same problem  just now, using mqttbox instead

**Comment by alisoam** [comment] 2019-06-04 10:20
I experienced the same issue for rabbitmq bridge, even when I disable bridge.example.mountpoint.

**Comment by tradingtrace** [comment] 2019-06-08 15:01
I reproduced this issue followed @oakfire steps.
I fix it by adding this config in `etc/emqx.conf`:
```shell
bridge.aws.max_inflight_batches = 8
```

@Gilbert-Wong Maybe the default value of [`max_inflight_batches`](https://github.com/emqx/emqx/blob/5025b2f65d1c1d53ff2e0a50d6a16221ce2124d3/priv/emqx.schema#L1811) could be `{default, 8}` just the same as `-define(DEFAULT_SEND_AHEAD, 8).` in [emqx_bridge.erl](https://github.com/emqx/emqx/blob/5025b2f65d1c1d53ff2e0a50d6a16221ce2124d3/src/emqx_bridge.erl#L119)

**Comment by Gilbert-Wong** [comment] 2019-07-11 02:35
Thanks for your advice, @tradingtrace.

**Comment by turtleDeng** [comment] 2019-11-20 09:19
Thank you for your participation, I will close this issue.

**Closed by turtleDeng** 2019-11-20 09:19 UTC
Labels: Support
