### ISSUE TITLE
segfault at 5c error 4 in beam.smp

### ISSUE THREAD

**Issue by ma3sa10** [emqx/emqx#4867] opened 2021-05-26 01:22 UTC
**Environment**

- EMQX Version : 2.3.11
- Erlang/OTP Release : R20/9.0
- OS : Amazon Linux 2

EMQ is work as MQTT broker and clustered two nodes.

**Issue**

A emqttd.service is crashed when segfault happened. This issue is happened frequently but I couldn't identify that cause.

**Logs**

/var/log/messages

> May 18 17:17:52 ip-192-168-2-10 kernel: 3_scheduler[23224]: segfault at 5c ip 00000000005b9440 sp 00007f9f20d38bb0 error 4 in beam.smp[400000+331000]

/usr/local/emqttd/log/console.log

> 2021-05-18 17:17:49.527 [warning] <0.31197.1912>@emqttd_session:handle_cast:530 Session(xxxxxxxxx_30051): kickout <0.32384.2892>
> 2021-05-18 17:18:06.032 [info] <0.1082.0> Application lager started on node 'emq@192.168.2.10'

/usr/local/emqttd/log/crash.log

> 2021-05-18 17:17:42 =ERROR REPORT====
> SSL: certify: ssl_connection.erl:476:Fatal error: handshake failure
> 2021-05-18 17:18:18 =ERROR REPORT====
> SSL: hello: tls_handshake.erl:178:Fatal error: insufficient security - no_suitable_ciphers

/usr/local/emqttd/log/error.log

> 2021-05-18 17:17:42.608 [error] <0.15560.1920> SSL: certify: ssl_connection.erl:476:Fatal error: handshake failure
> 2021-05-18 17:18:18.252 [error] <0.1538.0> SSL: hello: tls_handshake.erl:178:Fatal error: insufficient security - no_suitable_ciphers

I would like to solve this issue. Is there any knowledge regarding this ?

Regards,

**Comment by DDDHuang** [comment] 2021-05-26 05:52
This is a Erlang OTP 20 ssl issue. There are two solutions:
1 Use HAProxy trans ssl connection
2 Upgrade EMQ X  Broker to version to 4

**Comment by ma3sa10** [comment] 2021-05-26 06:09
@DDDHuang 
Thanks a lot for your reply. Is there any reference regarding a Erlang OTP 20 ssl issue that makes segfault ?
I would like to reproduce this issue activity. 

Regards,

**Comment by terry-xiaoyu** [comment] 2021-05-27 01:53
I don't know the root cause either, but I saw such problem on OTP 21.1.x too, when I was using DTLS. I solved the issue by upgrading the erlang OTP to 22.3.x.

I think it may be hard for you to upgrade the OTP because emqx 2.x cannot be built on OTP > 20. So using Haproxy to handle the SSL connections is a better choice.

**Comment by qzhuyan** [comment] 2021-07-06 09:29
@ma3sa10 I think the issue is resolved, thus I close this ticket. 
feel free to reopen it when you need more help.

**Closed by qzhuyan** 2021-07-06 09:29 UTC
Labels: Support
