### ISSUE TITLE
[Dashboard] Replicant Connection Number is Wrongly Displayed

### ISSUE THREAD

**Issue by Estheriii** [emqx/emqx#12680] opened 2024-03-12 03:22 UTC
### What happened?

same issure as https://github.com/emqx/emqx/issues/12177
but my clients are already set clean_start = true and Session-Expiry-Interval to 0, 
but connections still can not remove by it self

### What did you expect to happen?

After all connections are disconnected, the dashboard displays 0 connections

### How can we reproduce it (as minimally and precisely as possible)?

The error appeared by letting the cluster run for more than one day and connecting / disconnecting a large amount of client, during this period, one core node was restarted once

### Anything else we need to know?

![截图 2024-03-12 11-16-32](https://github.com/emqx/emqx/assets/32813533/3e089b68-fe97-43c6-8be4-990a35aa33c1)
The client that remains on the dashboard after being disconnected for a long time（over 12 hours）
![图片](https://github.com/emqx/emqx/assets/32813533/0e729232-69c7-4e69-a2e3-c69d39325c3b)
all my clients are configured in same clean_start = true and Session-Expiry-Interval to 0, 
These connections that cannot be successfully cleared have strange protocols
### EMQX version

<details>

```console
sysdescr  : EMQX
version   : 5.0.21-g921ce502
datetime  : 2024-03-12T03:19:35.928067136+00:00
uptime    : 18 hours, 19 minutes, 56 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux replica-cluster-bb49df858-gd2l7 4.15.0-171-generic #180-Ubuntu SMP Wed Mar 2 17:25:05 UTC 2022 x86_64 GNU/Linux
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment] 2024-03-12 09:03
Version 5.0.21 is quite old, and it was the first minor version to include replicant support. We've merged several replicant-related bugfixes and improvements since after that. 
Is this issue also reproducible on more recent EMQX versions, like 5.5, 5.4, etc.?

**Closed** 2024-05-20 17:20 UTC
Labels: BUG, #triage/wait
