### ISSUE TITLE
Not receiving messages after a load test

### ISSUE THREAD

**Issue by manas-chaudhari** [emqx/emqx#1880] opened 2018-10-03 10:28 UTC
#### Environment

- OS: Ubuntu
- Erlang/OTP: R20/9.0 
- EMQ: 2.3.11

#### Description

I am observing that after a fan out load test, message routing is getting stuck for the topic used in load test. 
I am using a cluster of 5 c5.4xlarge machines, and the load test sets up 1M subscribers on a single topic and 1 publisher that publishes twice per minute for 5 minutes after all subscribers are set up.

The test runs well for the first time. I see 10M messages consumed. I saw mean latency of 6s. However, when I run the same test again, no messages are getting consumed. I confirmed this by doing a manual sub & pub on the same topic on one of the nodes using mosquitto_pub/mosquitto_sub. Pubsub on other topic works though. 

On adding a trace on the topic, I can see `PUBLISH` logs. So, messages are reaching the node.
On adding a trace on the subscriber client, I can see `RECV SUBSCRIBE`, `SEND SUBACK`. But, no `SEND PUBLISH`. 

Running a load test on a different topic works successfully (once). I have observed this issue on a single node also. On restarting the service, it had got resolved.

What might be happening here? How can I debug this further?

**Comment by manas-chaudhari** [comment] 2018-10-04 09:05
I observed that the `emqttd_ctl routes list` shows the load test topic even after the test has finished. Also, when the load is at the peak, pubsub works, and it gets stuck exactly when the load test is finished. Maybe the sudden disconnections of all clients are causing that topic to get stuck?

**Comment by manas-chaudhari** [comment] 2018-10-15 10:15
The tests done earlier were at a ramp up rate of 5k. There was no ramp down. All clients were disconnecting together. Also, earlier, I wasn't checking in case broker was recovering after certain time.

I setup the ramp down of connections, and also tried variations in the ramp rate. I observed that the broker *did* recover in around 5 minutes in case of 100k subscriptions. 

Observations:

1. Even after all clients disconnected, the topic was visible in the routes for around 5 minutes. After 5 minutes, it disappeared, with broker resuming functionality normally. Lets refer to this 5 minute period as `stuck window`.
1. During the stuck window, if there is a new subscription (on same/different topic), it doesn't appear in the routes until the stuck window ends. Messages get received on the subscription only after the stuck window ends.
1. If there is was already a subscription on another topic before the stuck window started, it *receives* messages in the stuck window. So, only new subscriptions get blocked in the stuck window.
1. During the stuck window, the web dashboard displays `undefined/undefined/...` on the overview page in `Erlang Processes`, `CPU Info`, `Memory` tabs and empty value in `MaxFds`.
1. The duration of stuck window seems to be proportional to the number of subscriptions. In case of 50k subscriptions, the stuck window was around 1 minute.


It seems that some work might be getting queued at the time of disconnect, which is blocking the routing setup for all further subscriptions. 
What could be the issue here? 

Here are the configs for reference:

emq.conf
```
mqtt.allow_anonymous=true

## Erlang Process Limit
node.process_limit = 2097152

## Sets the maximum number of simultaneously existing ports for this system
node.max_ports = 1048576

## Size of acceptor pool
listener.tcp.external.acceptors = 64

## Maximum number of concurrent clients
listener.tcp.external.max_clients = 1000000
```

/etc/sysctl.conf
```
net.ipv4.ip_local_port_range=1024   60999
fs.file-max=1048576
```

/etc/security/limits.conf
```
*       -       nofile  1048576
```

**Comment by Gilbert-Wong** [comment] 2018-10-15 15:47
Hi, can you provide your hardware information which would help us reproduce the problem you mentioned?

**Comment by jinfahua** [comment] 2018-10-16 01:18
> Hi, can you provide your hardware information which would help us reproduce the problem you mentioned?

I supplied you the hardware info...

**Comment by manas-chaudhari** [comment] 2018-10-18 04:58
Sorry, missed this message.

I tested on a c5.4xlarge machine on AWS.
vCPU: 16
Memory: 32GB

Load was generated from 4 m4.xlarge machines.
vCPU: 4
Memory: 16GB

Kindly let me know if you need anything specific.

**Comment by jinfahua** [comment] 2018-10-21 07:41
@manas-chaudhari We are working on the issue, will let you know if having any update.

**Comment by jinfahua** [comment] 2019-01-18 05:52
@manas-chaudhari The problem was fixed in the latest version, please check it out. Feel free to let us know if having any problems.

**Comment by manas-chaudhari** [comment] 2019-01-18 06:18
Cool. I will check it out.

**Closed** 2019-01-25 05:46 UTC
Labels: Benchmark
