### ISSUE TITLE
ACL problem in MySQL authentication

### ISSUE THREAD

**Issue by ztg1** [emqx/emqx#3854] opened 2020-11-27 06:33 UTC
我使用的免费版，看到有msql的认证插件，按照官方文档配置了，可以实现用户密码认证登录，可以就是acl权限认证没起到到作用
我的配置方式和这边文章一个样：https://blog.csdn.net/qq_37949192/article/details/105908717

**Comment by tigercl** [comment] 2020-11-30 00:47
@ztg1 Sorry for not replying to you in time. It is recommended that you read the documentation on the official website according to your emqx version: https://docs.emqx.io/broker/latest/en/advanced/acl-mysql.html. You can also use the trace command to trace your client first, so that you can view all events that occurred in the emqx after the client is connected.

**Comment by k32** [comment] 2021-06-16 15:26
Likely a duplicate of https://github.com/emqx/emqx/issues/3057

**Closed by k32** 2021-06-16 15:26 UTC
Labels: Support
