### ISSUE TITLE
Crash report 3 node cluster behind Haproxy

### ISSUE THREAD

**Issue by rjbaat** [emqx/emqx#1883] opened 2018-10-08 07:15 UTC
#### Environment

- OS: Linux
- Erlang/OTP: R20/9.1.5 
- EMQ: 2.3.11

#### Description

Hi all, there was a error with a restart occurring on all 3 nodes. the cluster is behind a HAProxy load balancer. 

This is the crash report:

```
[error] CRASH REPORT Process <0.5361.50> with 0 neighbours crashed with reason: proxy_proto_timeout in esockd_connection:upgrade/1 line 122
(emqtt-broker-1@xxx)1> 03:03:33.315 [error] Supervisor 'esockd_connection_sup - <0.1467.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,true},{max_clientid_len,1024},...]) at <0.5361.50> exit with reason proxy_proto_timeout in esockd_connection:upgrade/1 line 122 in context connection_crashed (emqtt-broker-1@xxx)1> 
```
Anyone know what the problem is?

**Comment by Eluso** [comment] 2019-03-25 07:39
Hi rjbaat,
Sorry to reply to you so late,I have try use 3.1-beta.3 can't reproduce your error.

**Comment by turtleDeng** [comment] 2019-04-29 15:00
We will close this issue and you can reopen if there are any problems.

**Closed by turtleDeng** 2019-04-29 15:00 UTC
Labels: Support
