### ISSUE TITLE
erlang_vm_memory_processes_bytes_total grows too fast and triggers the OOM

### ISSUE THREAD

**Issue by Gypsying** [emqx/emqx#8765] opened 2022-08-19 13:38 UTC
### What happened?

**Cloud enviroment**
Emqx-4.3.15 deployed as a statefulset to implement the distributed cluster in k8s enviroment.
> The statefulset is constituted by 16 pods which the pod resource is 10core10g limit.
> Base the k8s' coredns to implement the service discovery.

**Edge enviroment**
We have one million clients to connect the emqx cluster by mqttssl, and run very well for long time.
> clients --> LB --> emqx cluster
> The LB just do reverse proxy, not include ssl offload.

**Crash**
But recent the cluster broken suddenly, 
and the **`erlang_vm_memory_processes_bytes_total`** grows too fast, all the pods were killed by k8s because of OOM.

All pods occupied memory grows too fast:
![image](https://user-images.githubusercontent.com/17995262/185626573-a1f3aab9-a488-4503-a0d5-bfc157ed9e2b.png)

and one of the instance's **`erlang_vm_memory_processes_bytes_total`**:
![image](https://user-images.githubusercontent.com/17995262/185625832-0e1388ce-2c69-4012-8d18-68905f29afde.png)

### What did you expect to happen?

The emqx-4.3.15 cluster has run very well for two months nearly,
And publish 2w~3w messages per minute all the time:
![image](https://user-images.githubusercontent.com/17995262/185627876-06d1f298-5c5e-4d0c-a920-186af0a4707f.png)

### Anything else we need to know?

The emqx cluster just use the default value of **`etc/vm.args`**.

And other envs i configured below:
```
- name: EMQX_ZONE__INTERNAL__ALLOW_ANONYMOUS
  value: "false"
- name: EMQX_LISTENER__TCP__EXTERNAL__MAX_CONN_RATE
  value: "500"
- name: EMQX_LISTENER__SSL__EXTERNAL__MAX_CONN_RATE
  value: "500"
- name: EMQX_ZONE__EXTERNAL__PUBLISH_LIMIT
  value: "100,10s"
- name: EMQX_LISTENER__TCP__EXTERNAL__RATE_LIMIT
  value: "100KB,10s"
- name: EMQX_LISTENER__SSL__EXTERNAL__RATE_LIMIT
  value: "100KB,10s"
- name: EMQX_CLUSTER__AUTOCLEAN
  value: "2h"
- name: EMQX_LISTENER__TCP__EXTERNAL__ACCEPTORS
  value: "64"
- name: EMQX_LISTENER__SSL__EXTERNAL__ACCEPTORS
  value: "64"
- name: EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS
  value: "102400"
- name: EMQX_LISTENER__SSL__EXTERNAL__MAX_CONNECTIONS
  value: "102400"
- name: EMQX_LISTENER__WS__EXTERNAL__MAX_CONNECTIONS
  value: "102400"
- name: EMQX_LISTENER__WSS__EXTERNAL__MAX_CONNECTIONS
  value: "102400"
```

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQ X Broker
version   : 4.3.15
```

</details>

### OS version

<details>

```
K8s' Host OS: CentOS 8.2
Arch: x86_64
Kernel-release: 4.18
```

</details>

### Log files
The logs of crash datatime was lost unfortunately, there is some logs after some minutes:

<details>
2022-08-18T11:51:13.941972895+08:00 stdout F 2022-08-18T03:51:13.918022+00:00 [error] <this_is_my_clientid>@<ip>:39764 crasher: initial call: emqx_connection:init/4, pid: <0.32455.7>, registered_name: [], error: {internal_error,[{rpc,mc_results,7,[{file,"rpc.erl"},{line,906}]},{rpc,multicall,5,[{file,"rpc.erl"},{line,776}]},{ekka_locker,acquire_locks,4,[{file,"ekka_locker.erl"},{line,153}]},{emqx_cm_locker,trans,3,[{file,"emqx_cm_locker.erl"},{line,49}]},{emqx_channel,process_connect,2,[{file,"emqx_channel.erl"},{line,493}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,662}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,362}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,368}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,326}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}, ancestors: [<0.6533.0>,<0.6532.0>,esockd_sup,<0.6258.0>], message_queue_len: 4, messages: [{'DOWN',#Ref<0.3151578150.3186622474.125329>,process,<46243.9853.4>,{#Ref<0.3151578150.3186622474.125327>,return,{true,['emqx@xx.xx.xx.xx']}}},{'DOWN',#Ref<0.3151578150.3186622474.125328>,process,<46242.17624.13>,{#Ref<0.3151578150.3186622474.125327>,return,{true,['emqx@xx.xx.xx.xx']}}},{'DOWN',#Ref<0.3151578150.3186622474.125330>,process,<46235.15548.17>,{#Ref<0.3151578150.3186622474.125327>,return,{true,['emqx@xx.xx.xx.xx']}}},{timeout,#Ref<0.3151578150.3186622474.125323>,emit_stats}], links: [<0.6533.0>], dictionary: [{guid,{1660794643807894,230176004800199,0}},{incoming_bytes,84},{'$logger_metadata$',#{clientid => "this_is_my_clientid",peername => "<ip>:39764"}},{recv_pkt,1}], trap_exit: false, 
status: running, heap_size: 6772, stack_size: 28, reductions: 25122; neighbours:

_
2022-08-18T11:51:13.942111826+08:00 stdout F 2022-08-18T03:51:13.935946+00:00 [error] supervisor: 'esockd_connection_sup - <0.6445.0>', errorContext: connection_crashed, reason: {internal_error,[{rpc,mc_results,7,[{file,"rpc.erl"},{line,906}]},{rpc,multicall,5,[{file,"rpc.erl"},{line,776}]},{ekka_locker,acquire_locks,4,[{file,"ekka_locker.erl"},{line,153}]},{emqx_cm_locker,trans,3,[{file,"emqx_cm_locker.erl"},{line,49}]},{emqx_channel,process_connect,2,[{file,"emqx_channel.erl"},{line,493}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,662}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,362}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,368}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,326}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}, offender: [{pid,<0.1370.8>},{name,connection},{mfargs,{emqx_connection,start_link,[[{deflate_options,[]},{max_conn_rate,500},{active_n,100},{zone,external},{rate_limit,{102400,10}},{proxy_address_header,<<>>},{proxy_port_header,<<>>},{supported_subprotocols,[]}]]}}]

2022-08-18T11:51:35.747691768+08:00 stderr F [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
2022-08-18T11:51:35.747704491+08:00 stderr F [os_mon] memory supervisor port (memsup): Erlang has closed
</details>

**Comment by thalesmg** [comment] 2022-08-19 14:11
Hi @Gypsying !

Thank you for the detailed report.

The following excerpt from the logs:

```
reason: {internal_error,[{rpc,mc_results,7,[{file,"rpc.erl"},{line,906}]},{rpc,multicall,5,[{file,"rpc.erl"},{line,776}]}
```

Indicates that the broker hit a [known OTP 23.2.7.2 bug](https://github.com/erlang/otp/issues/5346).  EMQX version 4.3.18 has an updated OTP version (23.3.4.9) that has this fixed.  It's recommended to upgrade, if possible.

**Comment by Gypsying** [comment] 2022-08-22 02:17
> Hi @Gypsying !
> 
> Thank you for the detailed report.
> 
> The following excerpt from the logs:
> 
> ```
> reason: {internal_error,[{rpc,mc_results,7,[{file,"rpc.erl"},{line,906}]},{rpc,multicall,5,[{file,"rpc.erl"},{line,776}]}
> ```
> 
> Indicates that the broker hit a [known OTP 23.2.7.2 bug](https://github.com/erlang/otp/issues/5346). EMQX version 4.3.18 has an updated OTP version (23.3.4.9) that has this fixed. It's recommended to upgrade, if possible.


Well, i will upgrade the new version, but i am curious above:

- What reason will trigger this BUG?  
> 4.3.15 has running for two months very well.

- Why the **`erlang_vm_memory_processes`** occupied momery so fast?  

- From the [diagram](https://user-images.githubusercontent.com/17995262/185625832-0e1388ce-2c69-4012-8d18-68905f29afde.png) we can see that **`erlang_vm_memory_processes`** will **`free memory`** period, so what do the momery size used depends on?

**Comment by terry-xiaoyu** [comment] 2022-08-23 01:47
That is a known issue in OTP 23.2, which will stuck the connection process, there will be more and more messages be blocked in the mailbox (erlang process mailbox) so the process memory usage increases.

**Comment by Gypsying** [comment] 2022-08-23 02:15
Well, but i am curious what reason will trigger this BUG?

**Comment by qzhuyan** [comment] 2022-08-23 10:26
Mostly unstable network or too small dist port buffer size. 

I close the ticket for now since we are sure it is caused by OTP bug which is fixed in later versions.

**Closed by qzhuyan** 2022-08-23 10:26 UTC
Labels: BUG
