### ISSUE TITLE
[warning] ekka_mnesia: still waiting for table(s)

### ISSUE THREAD

**Issue by chiris414362444** [emqx/emqx#4863] opened 2021-05-25 03:03 UTC
When persistence is enabled in the cluster, the pod may not restart normally after trying to delete pod or statefulsets.  Log print [warning] ekka_mnesia: still waiting for table(s).
**The steps are as follows:**
1. helm install emqx .
2. After all pods are running, execute any of the following commands：
   kubectl delete sts emqx   /  helm delete emqx  /  kubectl delete pod emqx-0 emqx-1 emqx-2

**Log as follws: **
cluster.discovery = "k8s"
cluster.k8s.address_type = "hostname"
cluster.k8s.apiserver = "https://kubernetes.default.svc:443"
cluster.k8s.app_name = "emqx"
cluster.k8s.namespace = "default"
cluster.k8s.service_name = "emqx-headless"
cluster.k8s.suffix = "svc.cluster.local"
listener.ssl.external.acceptors = "32"
listener.ssl.external.max_connections = "102400"
listener.tcp.external.acceptors = "64"
listener.tcp.external.max_connections = "1024000"
listener.ws.external.acceptors = "16"
listener.ws.external.max_connections = "102400"
listener.wss.external.acceptors = "16"
listener.wss.external.max_connections = "102400"
log.to = "console"
node.max_ets_tables = "2097152"
node.max_ports = "1048576"
node.name = "emqx@emqx-0.emqx-headless.default.svc.cluster.local"
node.process_limit = "2097152"
rpc.port_discovery = "manual"
Exec: /opt/emqx/erts-11.1.8/bin/erlexec -noshell -noinput +Bd -boot /opt/emqx/releases/4.3.1/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir "/opt/emqx/data/mnesia/emqx@emqx-0.emqx-headless.default.svc.cluster.local" -config /opt/emqx/data/configs/app.2021.05.25.02.42.07.config -args_file /opt/emqx/data/configs/vm.2021.05.25.02.42.07.args -vm_args /opt/emqx/data/configs/vm.2021.05.25.02.42.07.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- foreground
Root: /opt/emqx
Starting emqx on node emqx@emqx-0.emqx-headless.default.svc.cluster.local
2021-05-25T02:42:40.028375+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:43:10.029531+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:43:40.030417+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:44:10.031350+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:44:40.032431+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:45:10.033348+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:45:40.034396+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:46:10.035369+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:46:40.036420+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:47:10.037602+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:47:40.038394+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:48:10.039399+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:48:40.040492+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:49:10.041793+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:49:40.042384+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-05-25T02:50:10.043387+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]

Charts:  [charts/emqx](https://github.com/emqx/emqx/tree/master/deploy/charts/emqx)
AppVersion: 4.3.1
Kubernetes version: v1.19.4

Reference issue: [3993](https://github.com/emqx/emqx/issues/3993)

**Comment by qzhuyan** [comment] 2021-05-25 07:54
@chiris414362444 
If I understand correctly, you delete 3 pods at the same time then k8s sts will redeploy three pods by reusing the PVC.
The problem is when deleting pods in parallel, the schema may get corrupted since there will be no source of truth, or nodes have wrong info about which node has the latest copy of data. This is out of control from eqmx point of view.

A workaround is try to scale down the number of pods to one then delete the last pod or sts.

```kubectl scale statefulset --replicas= .... ```

**Comment by chiris414362444** [comment] 2021-05-26 02:53
@qzhuyan Thank you for your reply. You understand it correctly. There is no problem to delete pods through scale, but it will bring inconvenience to upgrade deploy. Can you support deleting pods in parallel in the future?

**Comment by qzhuyan** [comment] 2021-05-27 07:40
@chiris414362444 i
Can you describe what is your upgrade deployment, what do you want to achieve? 

if you do the` helm upgrade` chart, it is a rolling upgrade and it should be supported.

**Comment by ctellechea2001** [comment] 2021-07-23 17:57
@k32 @qzhuyan Did you found the solution? If you need to reproduce the error you can run the following steps:

- Install minikube
- Run: **helm install my-emqx emqx/emqx --set service.type=NodePort --set persistence.enabled=true**
- Run **minikube stop** that command simulate that all pods are stopped together at the same time.
- Run: **minikube start**
- After that all the pods are going to be stopped.

Exec: /opt/emqx/erts-11.1.8/bin/erlexec -noshell -noinput +Bd -boot /opt/emqx/releases/4.3.5/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir "/opt/emqx/data/mnesia/my-emqx@my-emqx-0.my-emqx-headless.emqx.svc.cluster.local" -config /opt/emqx/data/configs/app.2021.07.23.17.51.25.config -args_file /opt/emqx/data/configs/vm.2021.07.23.17.51.25.args -vm_args /opt/emqx/data/configs/vm.2021.07.23.17.51.25.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- foreground
Root: /opt/emqx
Starting emqx on node my-emqx@my-emqx-0.my-emqx-headless.emqx.svc.cluster.local
2021-07-23T17:51:58.350855+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:52:28.351871+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:52:58.352872+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:53:28.353902+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:53:58.354912+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]
2021-07-23T17:54:28.355920+00:00 [warning] ekka_mnesia: still waiting for table(s): [emqx_resource,mqtt_app,emqx_rule,emqx_banned,mqtt_admin]

**Comment by k32** [comment] 2021-07-23 18:40
Hello,
We're discussing a change to the helm chart that allows all the nodes to start at the same time. This will allow to avoid the deadlock when the first node infinitely waits for the other node, preventing it from start.

**Comment by ctellechea2001** [comment] 2021-07-26 13:31
Ok @k32 , Just to help you we configure the parallel pod management policy

diff --git a/deploy/charts/emqx/templates/StatefulSet.yaml b/deploy/charts/emqx/templates/StatefulSet.yaml
index f8271d1..b73c971 100644
--- a/deploy/charts/emqx/templates/StatefulSet.yaml
+++ b/deploy/charts/emqx/templates/StatefulSet.yaml
@@ -9,6 +9,7 @@ metadata:
     app.kubernetes.io/instance: {{ .Release.Name }}
     app.kubernetes.io/managed-by: {{ .Release.Service }}
 spec:
**+  podManagementPolicy: "Parallel"**      
   serviceName: {{ include "emqx.fullname" . }}-headless
   {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
   volumeClaimTemplates:

Results:

carlos@(minikube:emqx):~/Documents/Hipcam/Deployments/emqx/charts/emqx-rel/deploy/charts$ k get pods
NAME        READY   STATUS              RESTARTS   AGE
my-emqx-0   0/1     ContainerCreating   0          3s
my-emqx-1   0/1     Running             0          3s
my-emqx-2   0/1     ContainerCreating   0          3s

NAME        READY   STATUS    RESTARTS   AGE
my-emqx-0   0/1     Running   0          9s
my-emqx-1   0/1     Running   0          9s
my-emqx-2   0/1     Running   0          9s

NAME        READY   STATUS    RESTARTS   AGE
my-emqx-0   1/1     Running   0          59s
my-emqx-1   0/1     Running   0          59s
my-emqx-2   0/1     Running   0          59s

You can see that only pods 0 is working and the other two pods are failing

NAME        READY   STATUS    RESTARTS   AGE
my-emqx-0   1/1     Running   0          107s
my-emqx-1   0/1     Running   1          107s
my-emqx-2   0/1     Running   1          107s


kubectl exec my-emqx-0 -- emqx_ctl cluster status
Cluster status: #{running_nodes =>
                      ['my-emqx@my-emqx-0.my-emqx-headless.emqx.svc.cluster.local'],
                  stopped_nodes => []}
carlos@(minikube:emqx):~/Documents/Hipcam/Deployments/emqx/charts/emqx-rel/deploy/charts$ 

Logs:

021-07-26 13:30:17.783 [warning] global: 'my-emqx@my-emqx-1.my-emqx-headless.emqx.svc.cluster.local' failed to connect to 'my-emqx@my-emqx-2.my-emqx-headless.emqx.svc.cluster.local'

2021-07-26 13:30:27.678 [error] ** Generic server mnesia_subscr terminating 
** Last message in was {'EXIT',<0.1422.0>,killed}
** When Server state == {state,<0.1422.0>,
                               #Ref<0.1578579666.3391488004.219048>}
** Reason for termination ==
** killed

2021-07-26 13:30:27.678 [error] ** Generic server mnesia_monitor terminating 
** Last message in was {'EXIT',<0.1422.0>,killed}
** When Server state == {state,<0.1422.0>,[],[],true,[],undefined,[],[]}
** Reason for termination ==
** killed

2021-07-26 13:30:27.678 [error] ** Generic server mnesia_recover terminating 
** Last message in was {'EXIT',<0.1422.0>,killed}
** When Server state == {state,<0.1422.0>,undefined,undefined,undefined,0,
                               false,true,[]}
** Reason for termination ==
** killed

**Comment by Fidenz-Lasithh** [comment] 2021-08-13 09:43
Hello @k32,
In which version we can expect the fix for this?

**Comment by qzhuyan** [comment] 2021-09-03 08:04
@Fidenz-Lasithh 
In the next 4.3 release, which will be 4.3.8

**Closed by qzhuyan** 2021-09-03 08:04 UTC
Labels: Support, backlog

**Comment by samip5** [comment] 2021-12-21 22:48
This is also happening when you rollout restart the cluster, but don't delete the pvcs with nfs-client as storage.
When all of the pods are terminated, the pvc's stay.

Only after removing all pvcs that emqx provisioned, it will come back up successfully.
All pods are on seperate nodes.
