### ISSUE TITLE
~10ms latency on publishing and receiving message on the same machine on windows

### ISSUE THREAD

**Issue by Zelmoghazy** [emqx/emqx#12942] opened 2024-04-28 19:38 UTC
### What happened?

I wrote a very simple script to test emqx 

```python
import time
import threading
from datetime import datetime
import paho.mqtt.client as mqtt

previous_timestamp = 0;

def on_connect(mqttc, obj, flags, rc):
    print("rc: " + str(rc))

def on_message(mqttc, obj, msg):
    global previous_timestamp
    current_datetime = datetime.now()
    current_timestamp_milliseconds = int(current_datetime.timestamp() * 1000)
    print(current_timestamp_milliseconds-previous_timestamp)
    previous_timestamp = current_timestamp_milliseconds

def on_subscribe(mqttc, obj, mid, granted_qos):
    print("Subscribed: " + str(mid) + " " + str(granted_qos))

def on_log(mqttc, obj, level, string):
    print(string)

mqttc = mqtt.Client()
mqttc.on_message   = on_message
mqttc.on_connect   = on_connect
mqttc.on_subscribe = on_subscribe

def publish_message(client):
    while True:
        message = "Testing latency"
        client.publish("readings", message)
        time.sleep(0.1)

mqttc.connect("192.168.1.100", 1883, 60)
mqttc.subscribe("readings", 0)

publish_thread = threading.Thread(target=publish_message, args=(mqttc,))
publish_thread.start()

mqttc.loop_forever()
```

I essentially just publish and subscribe to the same topic

### What did you expect to happen?

a constant 100ms interval between publishing and receiving the message , but it was more like from 110 to 123 
I tried the same thing using node-red and the same latency is observed , something must be wrong because sending a message every 100 ms is not that fast a 10ms latency is very  high 
I am using emqx 5.3.2 on windows

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
sysdescr  : EMQX
version   : 5.3.2
datetime  : 1970-07-18T13:02:10.992746128+03:00
uptime    : 9 minutes, 23 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment] 2024-04-29 08:23
> I tried the same thing using node-red and the same latency is observed

Can you elaborate on this part? Do you observe ~10ms latency with node-red as well?

**Comment by Zelmoghazy** [comment] 2024-04-29 09:03
> client side buffering.

'''
listeners.tcp.my_tcp_listener_name {
    bind = 1883 
    tcp_options {
        nodelay = true
    }
}
'''
I added this to my configuration file to attempt to disable nagle's algorithm,  but It doesnt seem to change anything , is there a way to test that ?

**Comment by ieQu1** [comment] 2024-04-29 10:49
My question was: do you observe the same end-to-end latency with _both_ EMQX and node-red? If so, it could be a problem with the load generator (i.e. paho client does buffering on its own).

**Comment by Zelmoghazy** [comment] 2024-04-29 11:15
> do you observe the same end-to-end latency with _both_ EMQX and node-red?

yes using both the python script and node-red , I observe same ~10ms latency , the broker is on the same machine

wire shark trace using python script
![Wireshark_KwmZzqydRh](https://github.com/emqx/emqx/assets/99360533/ec4e52f4-5fb6-4f63-8473-6ac2e8623eb8)

wireshark trace using node-red
![image](https://github.com/emqx/emqx/assets/99360533/59eb9211-62d4-4c9e-ac37-f678ee6ef74e)


> In my tests (1 pub -> 1 sub using emqtt client on Linux), the average round-trip latency is ~0.5 ms.

hmm can you confirm latency stays the same at a high frequency , like sending a small packet every 100ms

**Comment by ieQu1** [comment] 2024-04-29 11:26
> hmm can you confirm latency stays the same at a high frequency , like sending a small packet every 100ms

I used the following script `./emqttb --pushgw @pub --pubinterval 100ms -N 1 --metadata -t foo/%n @sub -N 1 --parse-metadata -t foo/#` (`emqttb` is a wrapper for `emqtt` that turns it into a scriptable loadgen) which essentially emulates your setup. Results look like this:

![e2e](https://github.com/emqx/emqx/assets/99872536/91861398-41f9-497e-9432-69f0a0439a5d)

**Comment by ieQu1** [comment] 2024-05-03 09:59
I close this ticket, because:
- We highlighted some causes for the increased latency.
- In the original test the packets go through the LAN (`192.168.1.100`), it adds network latency that we cannot control
- My attempts to reproduce the problem in a more controlled environment (packets are routed through `lo`) weren't successful
- Windows build is intended for local prototyping only, we don't tune it for high throughput/low latency.

**Closed by ieQu1** 2024-05-03 09:59 UTC
Labels: BUG, windows
