### ISSUE TITLE
** Generic server <0.30775.5> terminating 

### ISSUE THREAD

**Issue by w664744729** [emqx/emqx#2664] opened 2019-07-01 09:05 UTC
** {function_clause,
       [{emqx_ws_connection,websocket_handle,
            [pong,
             {state,undefined,undefined,
                 {{127,0,0,1},43178},
                 {{127,0,0,1},8093},
                 15000, 
                 {pstate,external,#Fun<emqx_ws_connection.1.123301540>,
                     {{127,0,0,1},43178},
                     undefined,4,<<"MQTT">>,<<"mqttjs_22043a0e">>,false,
                     <0.30767.5>,undefined,undefined,undefined,<0.30770.5>,
                     true,#{},134217728,undefined,undefined,60,undefined,
                     false,false,true,true,
                     #{msg => 0,pkt => 1},
                     #{msg => 0,pkt => 1},
                     true,
                     {1561,715675,185860}},
                 {none,#{max_packet_size => 134217728,version => 4}},
                 {keepalive,#Fun<emqx_ws_connection.2.123301540>,29,45,
                     {keepalive,check},
                     #Ref<0.3532761563.2322595841.17863>,0},
                 true,undefined,undefined}],
            [{file,"src/emqx_ws_connection.erl"},{line,159}]},
        {cowboy_websocket,handler_call,6,
            [{file,"src/cowboy_websocket.erl"},{line,454}]},
        {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
2019-06-28 17:55:39.225 [error] Ranch listener 'mqtt:ws' had connection process started with cowboy_clear:start_link/4 at <0.30772.5> exit with reason: {function_clause,[{emqx_ws_connection,websocket_handle,[pong,{state,undefined,undefined,{{127,0,0,1},43184},{{127,0,0,1},8093},15000,{pstate,external,#Fun<emqx_ws_connection.1.123301540>,{{127,0,0,1},43184},undefined,4,<<"MQTT">>,<<"mqttjs_22043a0e">>,false,<0.30772.5>,undefined,undefined,undefined,<0.30775.5>,true,#{},134217728,undefined,undefined,60,undefined,false,false,true,true,#{msg => 0,pkt => 1},#{msg => 0,pkt => 1},true,{1561,715709,181158}},{none,#{max_packet_size => 134217728,version => 4}},{keepalive,#Fun<emqx_ws_connection.2.123301540>,29,45,{keepalive,check},#Ref<0.3532761563.2322595841.18510>,0},true,undefined,undefined}],[{file,"src/emqx_ws_connection.erl"},{line,159}]},{cowboy_websocket,handler_call,6,[{file,"src/cowboy_websocket.erl"},{line,454}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
2019-06-28 17:55:39.225 [error] mqttjs_22043a0e ** Generic server <0.30775.5> terminating 
** Last message in was {'EXIT',<0.30772.5>,
                        {function_clause,
                         [{emqx_ws_connection,websocket_handle,
                           [pong,
                            {state,undefined,undefined,
                             {{127,0,0,1},43184},
                             {{127,0,0,1},8093},
                             15000,
                             {pstate,external,
                              #Fun<emqx_ws_connection.1.123301540>,
                              {{127,0,0,1},43184},
                              undefined,4,<<"MQTT">>,<<"mqttjs_22043a0e">>,
                              false,<0.30772.5>,undefined,undefined,undefined,
                              <0.30775.5>,true,#{},134217728,undefined,
                              undefined,60,undefined,false,false,true,true,
                              #{msg => 0,pkt => 1},
                              #{msg => 0,pkt => 1},
                              true,
                              {1561,715709,181158}},
                             {none,
                              #{max_packet_size => 134217728,version => 4}},
                             {keepalive,#Fun<emqx_ws_connection.2.123301540>,
                              29,45,
                              {keepalive,check},
                              #Ref<0.3532761563.2322595841.18510>,0},
                             true,undefined,undefined}],
                           [{file,"src/emqx_ws_connection.erl"},{line,159}]},
                          {cowboy_websocket,handler_call,6,
                           [{file,"src/cowboy_websocket.erl"},{line,454}]},
                          {proc_lib,wake_up,3,
                           [{file,"proc_lib.erl"},{line,259}]}]}}
** When Server state == {state,15000,true,local,<<"mqttjs_22043a0e">>,
                            undefined,undefined,undefined,1,0,#{},false,
                            {emqx_inflight,32,{0,nil}},
                            20000,undefined,
                            {mqueue,true,1000,0,0,none,infinity,
                                {queue,[],[],0}},
                            #{},100,300000,undefined,0,undefined,true,
                            undefined,0,0,
                            {1561,715709,181381},
                            0,undefined,undefined}
** Reason for termination ==

**Comment by Gilbert-Wong** [comment] 2019-07-03 01:31
Hi, @w664744729, could you please tell me the version of the emqx you use?

**Comment by w664744729** [comment] 2019-07-03 01:33
3.0版本

**Comment by Gilbert-Wong** [comment] 2019-07-03 01:44
It should be resolved in the latest version of emqx. You can try it. Hope my answer could help you.

**Comment by dario-collavini** [comment] 2019-07-09 08:36
Hi @Gilbert-Wong. Do you have any clue on what the issue could be? I'm incurring in it and I do not understand if the problem is from my side or it may be related to the old version of emqx that I'm using (v3.0.0)

**Comment by Gilbert-Wong** [comment] 2019-07-17 03:56
@dario-collavini here is the fix commit: https://github.com/emqx/emqx/commit/46e2886db5fddd75ecc0ea65f62a10c0d12b6aa3.  It is the bug of the websocket implementation.

**Closed by Gilbert-Wong** 2019-07-17 03:56 UTC
Labels: BUG
