### ISSUE TITLE
Cant connect telegraf ( subscriber ) to emqx

### ISSUE THREAD

**Issue by vacquah** [emqx/emqx#5865] opened 2021-09-30 21:51 UTC
### Subject of the support
Describe your issue here.
I am looking to send mqtt data from the broker to telegraf.  I am able to connect other subscribers , like mqttbox, to the broker. But somehow, using the telegraf mqtt input plugin, there is no connection. I am able to use the same plug ( another instance ) to connect to Vernemq without any issues. 

Error/Warning printout if any. 
none
### Your environment
emqx 4.3.8 helm install
Kubernetes k8s cluster with 3 master , 3 worker nodes and haproxy loadbalancing the api server 

For EMQ X 4.3 or newer, please provide the log archive generated by [node_dump tool](https://github.com/emqx/emqx/blob/master/bin/node_dump) 

Otherwise please provide below info:
- EMQ X version (e.g. `emqx_ctl status`):
- If cluster (e.g. 3 X 4Core16GB):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

### LOG File

Missing log file can delay the handling of the issue.

**Comment by qzhuyan** [comment] 2021-10-01 13:04
@vacquah would be helpful if you could provide some debug logs?

**Comment by jli113** [comment] 2022-01-04 09:14
I'm having the same problem here, telegraf mqtt works for local mqtt broker, not working for emqx.

**Comment by zmstone** [comment] 2022-01-04 10:05
@jli113 could you enable debug level log to inspect what happened to the client ?
see log level config here: https://docs.emqx.io/en/broker/v4.3/getting-started/log.html#log-trace

**Comment by jli113** [comment] 2022-01-06 04:31
2022-01-04T15:06:47.627255+08:00 [warning] Telegraf-Output-izmBI@218.13.14.204:20295 [Channel] The PUBREL PacketId 372 is not found.
2022-01-04T15:06:47.643986+08:00 [warning] Telegraf-Output-61nXV@218.13.14.204:20289 [Channel] The PUBREL PacketId 1211 is not found.
2022-01-04T15:06:47.648773+08:00 [warning] Telegraf-Output-dWAnn@218.13.14.204:20294 [Channel] The PUBREL PacketId 1961 is not found.
2022-01-04T15:06:47.648912+08:00 [warning] Telegraf-Output-umTux@218.13.14.204:20288 [Channel] The PUBREL PacketId 178 is not found.
2022-01-04T15:06:47.650801+08:00 [warning] Telegraf-Output-KndnU@218.13.14.204:20299 [Channel] The PUBREL PacketId 265 is not found.
2022-01-04T15:06:47.653090+08:00 [warning] Telegraf-Output-nJSHK@218.13.14.204:20298 [Channel] The PUBREL PacketId 1646 is not found.
2022-01-04T15:06:47.678727+08:00 [warning] Telegraf-Output-7poLe@218.13.14.204:20291 [Channel] The PUBREL PacketId 1145 is not found.
2022-01-04T15:06:47.699013+08:00 [warning] Telegraf-Output-QmrIK@218.13.14.204:20292 [Channel] The PUBREL PacketId 1272 is not found.
2022-01-04T15:06:47.703540+08:00 [warning] Telegraf-Output-mnu78@218.13.14.204:20302 [Channel] The PUBREL PacketId 6717 is not found.
2022-01-04T15:56:44.892216+08:00 [warning] MzAyNzYzMjc1NDM3NzQzNzk5NDU3NTcyNzE2MDk1MDc4NDA@218.13.14.204:20311 [Channel] Client MzAyNzYzMjc1NDM3NzQzNzk5NDU3NTcyNzE2MDk1MDc4NDA (Username: 'undefined') login failed for not_authorized
2022-01-04T15:56:45.947876+08:00 [warning] MzAyNzYzMjc1NjMyNDc4ODgyNDEzNTM1NzA1NzgwNzE1NTC@218.13.14.204:20312 [Channel] Client MzAyNzYzMjc1NjMyNDc4ODgyNDEzNTM1NzA1NzgwNzE1NTC (Username: 'undefined') login failed for not_authorized
2022-01-04T15:56:48.006929+08:00 [warning] MzAyNzYzMjc2MDEyMzA2MTk3MzI4MzcwNzU0MTM5NTg2NTG@218.13.14.204:20313 [Channel] Client MzAyNzYzMjc2MDEyMzA2MTk3MzI4MzcwNzU0MTM5NTg2NTG (Username: 'undefined') login failed for not_authorized
2022-01-04T15:56:52.064483+08:00 [warning] MzAyNzYzMjc2NzYwNzg5ODQ3ODgxODgzODIwNTkwMzY2NzC@218.13.14.204:20314 [Channel] Client MzAyNzYzMjc2NzYwNzg5ODQ3ODgxODgzODIwNTkwMzY2NzC (Username: 'undefined') login failed for not_authorized
2022-01-04T16:00:22.137562+08:00 [warning] MzAyNzYzMzE1NTEyNDM1ODY1Nzg1MTc5NDczODk0NDQwOTG@218.13.14.204:20315 [Channel] Client MzAyNzYzMzE1NTEyNDM1ODY1Nzg1MTc5NDczODk0NDQwOTG (Username: 'undefined') login failed for not_authorized
2022-01-04T16:00:23.195896+08:00 [warning] MzAyNzYzMzE1NzA3NjYzNDc2ODA3OTEwNTA4NjA4ODgwNjE@218.13.14.204:20316 [Channel] Client MzAyNzYzMzE1NzA3NjYzNDc2ODA3OTEwNTA4NjA4ODgwNjE (Username: 'undefined') login failed for not_authorized
2022-01-04T16:00:25.251104+08:00 [warning] MzAyNzYzMzE2MDg2Nzg0NjUwMzU5NjAzOTU1MzMxODkxMjA@218.13.14.204:20317 [Channel] Client MzAyNzYzMzE2MDg2Nzg0NjUwMzU5NjAzOTU1MzMxODkxMjA (Username: 'undefined') login failed for not_authorized
2022-01-04T16:00:29.307545+08:00 [warning] MzAyNzYzMzE2ODM1MDY1NTcxMTk1NzQ2OTUzODEwNDExNTC@218.13.14.204:20318 [Channel] Client MzAyNzYzMzE2ODM1MDY1NTcxMTk1NzQ2OTUzODEwNDExNTC (Username: 'undefined') login failed for not_authorized
2022-01-04T16:00:37.362442+08:00 [warning] MzAyNzYzMzE4MzIwOTMxNDM3MjUxNzczOTQxNDUzMjkxNTC@218.13.14.204:20319 [Channel] Client MzAyNzYzMzE4MzIwOTMxNDM3MjUxNzczOTQxNDUzMjkxNTC (Username: 'undefined') login failed for not_authorized
2022-01-04T16:02:10.572704+08:00 [warning] MzAyNzYzMzM1NTE1MTgyMzU1NjYwODQ5OTAwODU2OTM0NDA@218.13.14.204:20320 [Channel] Client MzAyNzYzMzM1NTE1MTgyMzU1NjYwODQ5OTAwODU2OTM0NDA (Username: 'undefined') login failed for not_authorized
2022-01-04T17:02:31.783685+08:00 [error] 218.13.14.199:22391 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet_header,4,false,3,true},<<"T / HTTP/1.1\r\nHost: 114.55.38.98:1883\r\nConnection: k"...>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,204}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<"GET / HTTP/1.1\r\nHost: 114.55.38.98:1883\r\nConnection: keep-alive\r\nUpgrade-Ins"...>>
2022-01-04T17:02:32.928387+08:00 [error] 218.13.14.199:22392 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet_header,4,false,3,true},<<"T / HTTP/1.1\r\nHost: 114.55.38.98:1883\r\nConnection: k"...>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,204}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<"GET / HTTP/1.1\r\nHost: 114.55.38.98:1883\r\nConnection: keep-alive\r\nCache-Contr"...>>
2022-01-04T17:43:38.212425+08:00 [warning] Telegraf-Output-Y13b6@218.13.14.204:20337 [Channel] The PUBREL PacketId 2460 is not found.
2022-01-04T18:03:27.960868+08:00 [warning] MzAyNzY0Njc3OTU2MzU5OTY2ODAzNzA1OTAwOTI0OTI4MDA@128.14.209.242:39622 [Channel] Client MzAyNzY0Njc3OTU2MzU5OTY2ODAzNzA1OTAwOTI0OTI4MDA (Username: 'undefined') login failed for not_authorized
2022-01-04T20:16:31.053337+08:00 [warning] MqttClient@184.105.247.195:44674 [Channel] Client MqttClient (Username: 'undefined') login failed for not_authorized
2022-01-04T20:29:29.018046+08:00 [warning] CENSYS@162.142.125.43:56246 [Channel] Client CENSYS (Username: 'undefined') login failed for not_authorized
2022-01-04T21:43:58.894862+08:00 [warning] nmap@164.90.201.209:37755 [Channel] Client nmap (Username: 'undefined') login failed for not_authorized
2022-01-04T21:44:06.291827+08:00 [error] 164.90.201.209:33721 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet_header,0,false,0,false},<<254,83,77,66,64,0,0,0,0,0,0,0,0,...>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,204}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<0,110,254,83,77,66,64,0,0,0,0,0,0,0,0,0,0,0,0,...>>
2022-01-04T21:44:09.953390+08:00 [error] 164.90.201.209:41231 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet_header,4,false,3,true},<<"T / HTTP/1.1\r\nHost: 114.55.38.98:1883\r\nUser-Agent: M"...>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,204}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<"GET / HTTP/1.1\r\nHost: 114.55.38.98:1883\r\nUser-Agent: Mozilla/5.0 (compatible"...>>
2022-01-04T21:44:13.625649+08:00 [error] 164.90.201.209:42073 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_utf8_string,[<<0>>],[{file,"emqx_frame.erl"},{line,459}]},{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,205}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<18,1,0,26,0,0,0,0,0,0,11,0,6,1,0,17,0,1,255,...>>
2022-01-04T21:44:21.518103+08:00 [error] 164.90.201.209:54699 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_utf8_string,[<<1,0,238>>],[{file,"emqx_frame.erl"},{line,459}]},{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,205}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<22,3,1,0,238,1,0,0,234,3,3,96,127,122,129,249,155,147,85,...>>
2022-01-05T00:02:34.146229+08:00 [warning] [65,173780]@42.240.141.27:43906 [Channel] Client Aðª (Username: 'Aðª') login failed for not_authorized
2022-01-05T00:08:20.744831+08:00 [error] 113.92.131.168:64562 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_packet,[{mqtt_packet_header,4,false,3,true},<<"T / HTTP/1.1\r\nHost: 114.55.38.98:1883\r\nUser-Agent: M"...>>,#{max_size => 1048576,strict_mode => false,version => 4}],[{file,"emqx_frame.erl"},{line,204}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<"GET / HTTP/1.1\r\nHost: 114.55.38.98:1883\r\nUser-Agent: Mozilla/5.0 (Windows NT"...>>
2022-01-05T03:47:06.705403+08:00 [warning] [65,173780]@8.142.145.206:57148 [Channel] Client Aðª (Username: 'Aðª') login failed for not_authorized
2022-01-05T04:49:11.324366+08:00 [error] 47.103.38.141:45003 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_utf8_string,[<<3,0,136>>],[{file,"emqx_frame.erl"},{line,459}]},{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,205}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<22,3,3,0,136,1,0,0,132,3,3,97,212,178,199,149,66,199,248,...>>
2022-01-05T10:30:21.487783+08:00 [warning] [Ctl] CMD acl is overidden by {emqx_acl_mnesia_cli,cli}
2022-01-05T11:28:00.128764+08:00 [warning] MqttClient@184.105.247.196:41180 [Channel] Client MqttClient (Username: 'undefined') login failed for not_authorized
2022-01-05T12:15:02.629999+08:00 [error] 185.216.140.168:63706 [MQTT] , Parse failed for function_clause, [{emqx_frame,parse_utf8_string,[<<0>>],[{file,"emqx_frame.erl"},{line,459}]},{emqx_frame,parse_packet,3,[{file,"emqx_frame.erl"},{line,205}]},{emqx_frame,parse_frame,4,[{file,"emqx_frame.erl"},{line,181}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,625}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,618}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,364}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,328}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<18,1,0,94,0,0,1,0,0,0,36,0,6,1,0,42,0,1,2,...>>

>

**Comment by zmstone** [comment] 2022-01-06 08:20
Are all the clients from telegraph? 
if not, could you point out which one?

**Comment by jli113** [comment] 2022-01-06 08:25
> Are all the clients from telegraph? if not, could you point out which one?

Not all are from Telegraf, I have shortened the log.

**Comment by zmstone** [comment] 2022-01-06 08:26
Thank you for the updated logs 
There are only a few warnings
What’s the observed/expected behavior one the client side?

**Comment by jli113** [comment] 2022-01-06 08:50
[outputs.mqtt] Wrote batch of 139 metrics in 7.262254819s
[outputs.mqtt] Buffer fullness: 139 / 10000 metrics

**Comment by zmstone** [comment] 2022-01-06 09:36
> [outputs.mqtt] Wrote batch of 139 metrics in 7.262254819s
[outputs.mqtt] Buffer fullness: 139 / 10000 metrics

Is this the expected behaviour ?
What's the logs from the client which behaved not as expected ?

`PUBREL PacketId ... is not found` warning from EMQ X side indicates the client is not behaving per MQTT specification.
This warning does not cause the client to disconnect though.

**Comment by jli113** [comment] 2022-01-06 09:49
What do you mean by client behaviour?
I used telegraf to send data, "[outputs.mqtt] Wrote batch of 139 metrics in 7.262254819s; [outputs.mqtt] Buffer fullness: 139 / 10000 metrics" is the log from telegraf. If the message has been successfully sent, the buffer fullness should be 0/10000.
It works fine when testing with mosquitto broker.

**Comment by zmstone** [comment] 2022-01-06 12:52
I mean what does it log when connecting to emqx

**Comment by jli113** [comment] 2022-01-08 03:27
2022-01-08T03:18:35Z D! [agent] Connecting outputs
2022-01-08T03:18:35Z D! [agent] Attempting connection to [outputs.mqtt]
2022-01-08T03:18:35Z D! [agent] Successfully connected to outputs.mqtt
2022-01-08T03:18:35Z D! [agent] Starting service inputs
2022-01-08T03:18:40Z D! [inputs.postgresql_extensible] Column: last_reset = <nil>: <nil>
··· many inputs ···
2022-01-08T03:19:31Z D! [outputs.mqtt] Wrote batch of 414 metrics in 25.408928559s
2022-01-08T03:19:31Z D! [outputs.mqtt] Buffer fullness: 414 / 10000 metrics

**Comment by mkashwin** [comment] 2022-02-14 14:20
I was playing around with EMX & Telegraf and have the similar issue
The telegraf client is connected but not subscribed to any topics

as a temporary workaround, I went to the dashboard -> clients
selected the telegraf user and  manually added the subscription to the topics

**Comment by zmstone** [comment] 2024-02-10 11:20
Closing this issue due to lack of input.

For anyone who encounters the issue as originally reported, please use the debug/trace (from dashboard UI) to trace the telegraf client and share the logs in a new issue.

For "The telegraf client is connected but not subscribed to any topics", it seems to be the client not sending SUBSCRIBE requests to EMQX?
The workaround is to setup a auto-subscribe.

**Closed by zmstone** 2024-02-10 11:20 UTC
Labels: Support, #triage/accepted
