### ISSUE TITLE
Exception log: Failed to execute {emqx_web_hook,on_client_connect,[{undefined}]}: {error,undef,[{emqx_web_hook,on_client_connect

### ISSUE THREAD

**Issue by kun964726743** [emqx/emqx#10012] opened 2023-02-21 10:51 UTC
### What happened?

[error] 9966CL6E037848@117.28.110.154:46898 [Hooks] Failed to execute {emqx_web_hook,on_client_connect,[{undefined}]}: {error,undef,[{emqx_web_hook,on_client_connect,[#{clean_start => true,clientid => <<"9966CL6E037848">>,conn_mod => emqx_connection,conn_props => #{},connected_at => 1676972751904,expiry_interval => 0,keepalive => 400,peercert => [],peername => {{117,28,110,154},46898},proto_name => <<"MQTT">>,proto_ver => 4,receive_maximum => 32,sockname => {{172,18,32,149},8883},socktype => proxy,username => <<"CL6E037848">>},success,#{},{undefined}],[]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,214}]},{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,193}]},{emqx_channel,handle_out,3,[{file,"emqx_channel.erl"},{line,1775}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,656}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,356}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,362}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,320}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}

### What did you expect to happen?

What does this log mean？

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by ieQu1** [comment] 2023-02-22 20:34
Duplicate of https://github.com/emqx/emqx/issues/10017 ?

**Closed** 2023-03-30 10:56 UTC
Labels: BUG
