### ISSUE TITLE
EMQX won't start: validation error in data bridge config (reconnect_interval is unmatched)

### ISSUE THREAD

**Issue by alexdelprete** [emqx/emqx#9948] opened 2023-02-10 00:21 UTC
### What happened?

I have 1 node EMQX, in a LXC container with Proxmox. I upgraded some days ago from v5.0.15 via apt-get (with packagecloud repo). Everything seemed to go ok, the service restarted fine.

Today I needed to reboot the server, and EMQX wouldn't restart. I checked the logs and found this:

```console
-- Journal begins at Wed 2022-09-28 03:05:04 CEST. --
feb 09 23:37:27 emqx emqx[2049]: EXEC: /usr/lib/emqx/erts-12.3.2.2/bin/erlexec -noshell -noinput +Bd -boot /usr/lib/emqx/releases/5.0.16/start -boot_var RELEASE_LIB /usr/lib/emqx/lib -boot_var ERTS_LIB_DIR /usr/lib/emqx/lib -mode embedded -config /var/lib/emqx/configs/app.2023.02.09.23.37.26.config -args_file /var/lib/emqx/configs/vm.2023.02.09.23.37.26.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- foreground -emqx_data_dir /var/lib/emqx
feb 09 23:37:29 emqx bash[2093]: [os_mon] memory supervisor port (memsup): Erlang has closed
feb 09 23:37:29 emqx bash[2094]: [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
feb 09 23:37:31 emqx bash[1795]: {"Kernel pid terminated",application_controller,"{application_start_failure,emqx_machine,{{shutdown,{failed_to_start_child,emqx_machine_boot,{'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},#{kind => validation_error,path => \"bridges.mqtt.weewx-tempest-bridge_emqx\",reason => unknown_fields,schema_module => emqx_conf_schema,unknown => \"reconnect_interval\",unmatched => \"clientid_prefix,ingress,...\",unshown_errors => 2}}}}},[{emqx_machine_boot,start_one_app,1,[{file,\"emqx_machine_boot.erl\"},{line,89}]},{lists,foreach,2,[{file,\"lists.erl\"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,\"emqx_machine_boot.erl\"},{line,38}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,414}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,384}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1250}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,350}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}}},{emqx_machine_app,start,[normal,[]]}}}"}
feb 09 23:37:31 emqx bash[1795]: Kernel pid terminated (application_controller) ({application_start_failure,emqx_machine,{{shutdown,{failed_to_start_child,emqx_machine_boot,{'EXIT',{{failed_to_start_app,emqx_conf,{emqx_conf,{bad_return,{{emqx_conf_app,start,[normal,[]]},#{kind => validation_error,path => "bridges.mqtt.weewx-tempest-bridge_emqx",reason => unknown_fields,schema_module => emqx_conf_schema,unknown => "reconnect_interval",unmatched => "clientid_prefix,ingress,...",unshown_errors => 2}}}}},[{emqx_machine_boot,start_one_app,1,[{file,"emqx_machine_boot.erl"},{line,89}]},{lists,foreach,2,[{file,"lists.erl"},{line,1342}]},{emqx_machine_boot,post_boot,0,[{file,"emqx_machine_boot.erl"},{line,38}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1250}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}
feb 09 23:37:31 emqx bash[1795]:
feb 09 23:37:31 emqx bash[1795]: Crash dump is being written to: log/erl_crash.dump...
feb 09 23:37:31 emqx systemd[1]: emqx.service: Main process exited, code=exited, status=1/FAILURE
```

So in `cluster-override.conf` I removed the `reconnect_interval = "15s"` line, and finally EMQX restarted fine.

As a final test, I went into the UI, in the data bridge settings, and in the Reconnect Interval field I set 15. When I saved the config, this error msg appeared (similar to the logs above):

![image](https://user-images.githubusercontent.com/7027842/217968214-048d687e-15dc-4c90-a291-e27d4f2c03ec.png)

So the questions are:

- the `reconnect_interval` field from UI should be removed?
- when I upgraded from 5.0.15 to 5.0.16 everything went fine, how was that possible if that setting was in the config?

I also discovered another issue:

```console
❯ emqx_ctl broker
Node 'emqx@127.0.0.1' not responding to pings.
ERROR: node_is_not_running!
```

I don't have a cluster setup, one node only, and in emqx.conf the node.cookie is set anyway. What could be the issue?

Thanks for the support.

### What did you expect to happen?

The service to start ignoring that setting

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
❯ ./bin/emqx_ctl
Node 'emqx@127.0.0.1' not responding to pings.
ERROR: node_is_not_running!
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by tigercl** [comment] 2023-02-13 02:45
@alexdelprete Thanks for your feedback, this is indeed a bug, I have reported it to the development team.

But about the problem with `emqx_ctl broker`, I couldn't reproduce it, can you provide more information? For example your configuration.

**Comment by zhongwencool** [comment] 2023-02-14 06:36
Fixed by https://github.com/emqx/emqx/pull/9946 , release in 5.0.17

**Comment by alexdelprete** [comment] 2023-02-14 12:46
> kill emqx's pid and restart the node will be ok.

I restarted the server, it didn't work. If there's a specific procedure to solve this please let me know and I'll test it.

**Comment by zmstone** [comment] 2024-02-02 17:41
> Sometimes I can't connect with emqx_ctl and emqx remote_console even though the node is alive.
kill emqx's pid and restart the node will be ok.

Not sure if this still persists in the latest v5.

I'm closing this issue since the config file compatibility issue is resolved.

**Closed by zmstone** 2024-02-02 17:41 UTC
Labels: BUG
